### ISSUE TITLE
Implement VNC protocol fence extensions to help with latency/responsiveness

### ISSUE THREAD

**Issue by kanaka** [kanaka/noVNC#159]
From discussion here: https://github.com/kanaka/noVNC/issues/23

From @astrand:

-----------------------------
A proxy is only a band aid, if you cannot solve it for real in the server and client. When it comes to latency, you might be interested in reading what my collegue at Cendio has written here: http://sourceforge.net/apps/mediawiki/tigervnc/index.php?title=VNC_Latency_Considerations

The proposed solution has been integrated into TigerVNC, with very good result. The protocol changes has also been included in the community version of the protocol, se: http://sourceforge.net/apps/mediawiki/tigervnc/index.php?title=Main_Page#RFB_Protocol

My suggestion is that we should add support for these mechanisms to noVNC.

---------------------------

**Comment by DirectXMan12** [comment]
I think we can actually close this as of #623 🎉
