### ISSUE TITLE
Fail to start WebSockets proxy

### ISSUE THREAD

**Issue by srquentin** [kanaka/noVNC#246]
Hi all,

I'm new to noVCN, and I've got issue to my first connection:

When I launch >./utils/launch.sh --vnc localhost:5901

I encounter some error shown below.

wsproxy.py: line 1 : websockify : command not found.
Fail to start WebSockets proxy.

Could you please tell me how to solve this problem? Thanks a lot!

**Comment by ljxiong313** [comment]
Hi~
I'm new to noVNC, i downloaded files from github,  and i found no websockify.py or websockify directory in utils, is the launch.sh instead of  it ?

**Comment by DirectXMan12** [comment]
Currently, launch.sh will try to either use a system-installed websockify or download websockify if it can't find it under utils.  We switched to this system to avoid having to manually keep noVNC's bundled copy of websockify in sync (i.e. we no longer bundle websockify).

**Comment by ljxiong313** [comment]
Thanks for DirectXMan12, and i have solved this problem.
