### ISSUE TITLE
onMouseDisable(e) in input.js does not work properly

### ISSUE THREAD

**Issue by Cervajz** [kanaka/noVNC#256]
Hi guys,

I've noticed that all clicks anywhere on page with the "noVNC canvas" does not work for my own links. This is caused by bad design of the condition inside onMouseDisable (input.js).

First this:

https://github.com/kanaka/noVNC/blob/master/include/input.js#L612

```javascript
pos = Util.getEventPosition(e, conf.target, conf.scale);
```

For "conf.target" the pos.x/y will be always 0 if mouse is outside target (which is canvas) from top/left side or will be value of widht-1/height-1 of target if mouse pos is bigger than taget width/height. 

Then the condition will be always true:

https://github.com/kanaka/noVNC/blob/master/include/input.js#L614

```javascript
  if ((pos.x >= 0) && (pos.y >= 0) &&
        (pos.x < conf.target.offsetWidth) &&
        (pos.y < conf.target.offsetHeight))
```

As a solution I suggest use this to get absolute positon:

```javascript
  pos = Util.getEventPosition(e, document, conf.scale);
```

Then it's necessary to change condition like this:

```javascript
  if ((pos.x >= conf.target.offsetLeft) && (pos.y >= conf.target.offsetTop) &&
        (pos.x < conf.target.offsetWidth + conf.target.offsetLeft) &&
        (pos.y < conf.target.offsetHeight + conf.target.offsetTop))  
```

**Comment by DirectXMan12** [comment]
Closing due to no response.  @emmar's fix should work in the general case.
