### ISSUE TITLE
Can't show Chinese VM name correctly

### ISSUE THREAD

**Issue by hlwanghl** [kanaka/noVNC#311]
We are using noVNC in our project Kimchi. Refer to the original issue: https://github.com/kimchi-project/kimchi/issues/88.

Reproduce:
 1. Create a VM with name "虚拟机-Ubuntu-13_04-01".
 2. Start it.
 3. Connect it via VNC.

Read the text in center of the top line.

Executed:
 Connected (unencrypted) to: QEMU (èææº-Ubuntu-13_04-01)

Expected:
 Connected (unencrypted) to: QEMU (虚拟机-Ubuntu-13_04-01)

**Comment by DirectXMan12** [comment]
see #365 .
