### ISSUE TITLE
Transport endpoint is not connected after session started

### ISSUE THREAD

**Issue by pbmzero** [kanaka/noVNC#334]
I have 20 different workstations and at any given moment one or two of them have a problem where I connect, authenticate, succeeds, begins renders about 3 or 4 blocks of the remote screen then frezees for 60 seconds, disconnects. The freeze always happens at the same spot. The problem usually goes away if i retry a couple times but sometimes it never fixes it. When it starts happening, it seems to happen in all browsers i attempt (Chrome, Firefox IE11) so it's probably more about the communication. If i restart the webscokets proxy there is a good chance it might fix it but there are times when it does not. The VNC server is up, i can connect directly to it through the IP address directly while this is ongoing.   This has been going on for several months.  It looks like it disconnects right after sending the keyboard layout profile (if i look at the communication with wireshark)

Chrome:Version 31.0.1650.63 m (Win 7, 32)
NoVnC: 5.3.4?  (Ubuntu 10.04 LTS 32)
TightVncServer: tightvnc-2.6.4-setup-32bit (Win 7, 32) with mirror driver installed

Output from the ws server:
  1: 64.40.246.182: Plain non-SSL (ws://) WebSocket connection
  1: 64.40.246.182: Version hybi-13, base64: 'False'
  1: 64.40.246.182: Path: '/websockify'
  1: connecting to: 10.160.0.61:5900
  1: handler exception: [Errno 107] Transport endpoint is not connected

Output from the chrome debug console:
New state 'Authentication', was 'Security'. Msg: Authenticating using scheme: 2 util.js:110
New state 'SecurityResult', was 'Authentication'. util.js:110
New state 'ClientInitialisation', was 'SecurityResult'. Msg: Authentication OK util.js:110
New state 'ServerInitialisation', was 'ClientInitialisation'. Msg: Authentication OK util.js:110
Screen: 1920x1080, bpp: 32, depth: 24, big_endian: 0, true_color: 1, red_max: 255, green_max: 255, blue_max: 255, red_shift: 16, green_shift: 8, blue_shift: 0 util.js:109
Setting viewport to full display region util.js:108
New state 'normal', was 'ServerInitialisation'. Msg: Connected (unencrypted) to:  util.js:110
Ignoring empty message util.js:108
First FBU latency: 172 util.js:109
>> set_cursor util.js:108
<< set_cursor util.js:108
>> WebSock.onclose util.js:108
WebSocket on-close event util.js:110
>> Keyboard.allKeysUp util.js:108
<< Keyboard.allKeysUp util.js:108
New state 'failed', was 'normal'. Msg: Server disconnected (code: 1006) util.js:111
Error while connected. util.js:111
<< WebSock.onclose util.js:108
>> Keyboard.allKeysUp util.js:108
<< Keyboard.allKeysUp util.js:108
New state 'disconnected', was 'failed'. util.js:110

**Comment by atomless** [comment]
I'm seeing the same error code 1006. I can connect to a ubuntu machine but connecting to an os x machine throws the error 1006. As described above it looks like it connects briefly and then disconnects. It is not intermittent for me at all, it happens every time. Tweaking the MTU has zero effect. Could you please can you reopen this issue? I don't think this is a network issue. This same error happens even when the network is not involved, when the python websockify proxy, the js client and the vnc source are on the same os x machine.

**Comment by kanaka** [comment]
1006 just means the connection was closed without receiving a close frame. It's one of the generic WebSocket error numbers (they are limited in order to prevent internal network scanning via the browser). The specific problem that @pbmzero was seeing "Transport endpoint is not connected" from websockify (the 1006 happens for many different issues).

@atomless can you post the websockify output that you see for this (that will point to which side of websockify the problem is occurring. Your javascript log (use logging=debug) would also be helpful. Also, using the exact same VNC server, are you able to connect from that same system with a native VNC client (i.e. to the same port that websockify is targeting)?

**Comment by DirectXMan12** [comment]
Closing due to no response.

**Comment by pbmzero** [comment]
@atomless  to clarify the possible cause and resolution, there was a site-to-site VPN where it was adding additional packet overhead to the VNC protocol leg (RFB?) 

VPN adds overhead to the packets, the VNC "RFB" packet added overhead to each packet which caused packet chunking. Packet chunking means the packet had to be split into two parts because it exceeded the MTU size, then reassembled.  I was able to control the network in this regard and remove the chunking by increasing the MTU to accommodate.

I'd further suggest trying websockify at the destination and having websockets traverse the network rather than TCP packets.
