### ISSUE TITLE
Add support for tcpwrappers.

### ISSUE THREAD

**Issue by dragz** [kanaka/noVNC#354]
Is it possible to add support for tcp wrappers?

Right now I'm using stunnel to encrypt  the connection and since it supports tcp wrappers I can also automatically whitelist ip-adresses based on successful ssh-logins on my servers.  It would be nice to be able to do that directly in novnc/websockify.

Best regards and thanks for a great piece of software,
Roy.

**Comment by DirectXMan12** [comment]
Websockify now has support for passing tokens via the query string, and filtering based on those.  That's probably not quite what you're looking for, but it should provide a way to only allow certain connections.
