### ISSUE TITLE
Keyboard events gets out of focus in iframe when click outside

### ISSUE THREAD

**Issue by pavan79** [kanaka/noVNC#360]
use noVNC to embed in my webpage using iframe. When page loads first time , both mouse and keyboard works perfectly , but when I click outside iframe area (i.e. anywhere in webpage) I am unable to get keyboard events and if I type anything it doesn't captured. 

However mouse events are working fine but keyboard event couldn't captured , but after I reload the entire page it works again.

Anyone facing same issue?

**Comment by samhed** [comment]
I assume this was fixed.
