### ISSUE TITLE
Consider dropping base64/text support (was: IE11 incorrectly falls back to base64 websockets)

### ISSUE THREAD

**Issue by jalfd** [kanaka/noVNC#375]
IE11 generates a SecurityError when trying to connect to localhost (for the Binary Websockets check). This means we never get a WebSocket object, and so we can't find the `binaryType` property, and as a result, we fall back to text-based websockets, despite IE11 actually supporting binary websockets.

It seems that IE11 *does* allow connections to 127.0.0.1, so we could simply replace 'localhost' with '127.0.0.1'.

Thoughts?

**Comment by DirectXMan12** [comment]
Doing some housecleaning -- we removed support for any IE < 10 in #488

**Comment by darkshadowray** [comment]
Hello!

 

New message, please read <http://www.andreaovallealcaldesa.com/dare.php?prr2>

 

ckl@GMX.AT

**Comment by darkshadowray** [comment]
Hello!

 

You have a new message, please read <http://evolutionmediainc.net/aluminum.php?1u>

 

ckl@GMX.AT

**Comment by darkshadowray** [comment]
Hello!

 

You have a new message, please read <http://hj99.net/missing.php?65>

 

ckl@GMX.AT
