### ISSUE TITLE
Mouse position incorrect on rescale

### ISSUE THREAD

**Issue by hamiltont** [kanaka/noVNC#398]
I see a number of issues already, but just in case no one has reported this one here goes. I start my scale at 1.0, any every time I scale down the translate moves my canvas too far to the top left. 

For browsers that support transform-origin, it seems to be a more reliable solution than manually calculating the transform values. For example, this works in FF and chrome for my use case (it updates display and mouse to ensure your internal variables are safe - the real fix is updating transform-origin and removing translate from the transform property. 

```
      function vncUpdateScale(amount) {
        var origscale = rfb.get_display()._scale;
        var origx = rfb.get_display().absX(0);
        var origy = rfb.get_display().absY(0);
        
        var update = origscale + amount;
        rfb.get_display().set_scale(update);
        var newScale = rfb.get_display()._scale;
        console.log('Updated display scale from ' + origscale + ' to ' + newScale);
        
        // Update mouse to reflect new scale
        var origMscale = rfb.get_mouse().get_scale();
        rfb.get_mouse().set_scale(newScale);
        var newMscale = rfb.get_mouse().get_scale();
        console.log('Updated mouse scale from ' + origMscale  + ' to ' + newMscale);
        
        // Fix CSS properties
        var target = rfb.get_target();
        $(target).css( "transform", 'scale(' + newScale + ')' );
        $(target).css( "transform-origin", 'top left' );
      }
```

Console output: 

```
Updated display scale from 1 to 0.95 
Updated mouse scale from 1 to 0.95 
Updated display scale from 0.95 to 0.8999999999999999 
Updated mouse scale from 0.95 to 0.8999999999999999 
```

**Comment by samhed** [comment]
Is this fixed now that #451 is merged?

**Comment by hamiltont** [comment]
@samhed not sure. I don't have time to test this ATM unfortunately

**Comment by samhed** [comment]
I will assume that this is fixed now, I have not encountered any issues with the new scaling code.
