### ISSUE TITLE
Long press to right-click on touch devices?

### ISSUE THREAD

**Issue by samhed** [kanaka/noVNC#417]
Currently on touch devices noVNC will present a toggle button in the top control bar:
![](https://raw.githubusercontent.com/kanaka/noVNC/master/images/mouse_right.png)

The user has to press the button to toggle between which mouse button he or she wants to send.

An alternative would be to use a long-press touch to right click. I would like to gather some opinions regarding this, what do you guys prefer?

**Comment by samhed** [comment]
I like the current behavior and can't think of a better alternative atm.

**Comment by kanaka** [comment]
Yep, one problem is that long-click might be used by an application on the server-side. We could make a hot-key that would switch modes, but we would probably need to make it configurable just in case it collided with something the user actually wants to send.

**Comment by Russell-Jones-OxPhys** [comment]
Pop up a menu that says "right click|send long click"? Or make the button toggle between long press to long press and long press to right click modes. I'd suggest a pic for each mode, a finger on a tablet and the one above.

**Comment by DirectXMan12** [comment]
> Pop up a menu that says "right click|send long click"? Or make the button toggle between long press to long press and long press to right click modes. I'd suggest a pic for each mode, a finger on a tablet and the one above.

I actually really like this idea -- long-press has become the defacto replacement for right-click on mobile devices (phones and tablets), and allowing right-clicks without having to go and press a separate button would be nice.

**Comment by samhed** [comment]
How could such a menu be realized graphically? I already think that we are close to having too many buttons in the control-bar on touch devices.

**Comment by DirectXMan12** [comment]
> How could such a menu be realized graphically?

Don't do a menu -- just replace the click-selector-button with a long-press-to-right-click button (although we may still need a click-selector button to select middle click).

**Comment by samhed** [comment]
Hm, and I think we need the "no button selected" mode as well, see #281 

Maybe there is some way we can integrate this long-press-toggle behavior with the current click-selector-button?

Or possibly something similar to what we have for the extra keys on small screens:

![small-open](https://cloud.githubusercontent.com/assets/4117162/7856230/c2a50f20-0527-11e5-8e73-8f3192b95456.png)

**Comment by samhed** [comment]
I'm satisfied with my idea of having a long-press-to-right-click built in to a future more generic toggle for touch gestures. It's not something I will get to work on right know, so if you have any ideas w.r.t this I wrote down some basis for discussion in our google groups page: https://groups.google.com/forum/#!forum/novnc
