### ISSUE TITLE
Error trying to connect to UltraVNC Repeater using noVNC

### ISSUE THREAD

**Issue by abelarteaga** [kanaka/noVNC#422]
Hi all

I am trying to use noVNC in a project in conjunction with https://code.google.com/p/uvncrepeater/ (UltraVNC Repeater).
I already have running the repeater and everything works just fine using the server (as a windows service and as a single click application) and client as a single click application.

However I would like to access my computers from a web-based client, it is when noVNC comes into the picture, I have setup websockify and I am using the launch.sh script to do so. 
I am using CentOS on a VPS server and executing launch.sh in this way:

    ./utils/launch.sh --listen 6080 --vnc my_public_ip:5901 --web /home/sgni/public_html/soporte/inc/gui/noVNC/ > /home/sgni/websockify.log 2>&1

and the log says it is running.

    Starting webserver and WebSockets proxy on port 6080
    WebSocket server settings:
      - Listen on :6080
      - Flash security policy server
      - Web server. Web root: /home/sgni/public_html/soporte/inc/gui/noVNC
      - No SSL/TLS support (no cert file)
      - proxying from :6080 to XX.XX.XX.XX:5901
    Press Ctrl-C to exit

    WARNING: no 'numpy' module, HyBi protocol will be slower

but when I try to connect with a browser to see any VNC server connected to the repeater I see this output in the websockify.log

    fixed-203-219-22.iusacell.net - - [23/Oct/2014 19:40:57] XX.203.219.22: Plain non-SSL (ws://) WebSocket connection
    fixed-203-219-22.iusacell.net - - [23/Oct/2014 19:40:57] XX.203.219.22: Version hybi-13, base64: 'False'
    fixed-203-219-22.iusacell.net - - [23/Oct/2014 19:40:57] connecting to: XX.XX.XX.XX:5901
    fixed-203-219-22.iusacell.net - - [23/Oct/2014 19:40:59] code 400, message Bad request syntax ('\x88\x8f\xfdR.\x89\xfe\xbaz\xe8\x8f5K\xfd\xdd1B\xe6\x8e7J')

and this output on the repeater log.

    UltraVnc Thu Oct 23 19:40:57 2014 > routeConnections(): new viewer connecting, accepting...
    UltraVnc Thu Oct 23 19:40:57 2014 > acceptConnection(): connection accepted ok from ip: XX.XX.XX.36
    UltraVnc Thu Oct 23 19:40:57 2014 > acceptConnection(): pv = RFB 000.000
    UltraVnc Thu Oct 23 19:40:57 2014 > writeExact(): start
    UltraVnc Thu Oct 23 19:40:57 2014 > writeExact(): returning normally
    UltraVnc Thu Oct 23 19:40:57 2014 > nonBlockingRead(): start
    UltraVnc Thu Oct 23 19:40:58 2014 > nonBlockingRead(): returning normally
    UltraVnc Thu Oct 23 19:40:58 2014 > checkIdCode(): 10005 is not IdCode string
    UltraVnc Thu Oct 23 19:40:58 2014 > parseHostAndPort() start: id = 10005
    UltraVnc Thu Oct 23 19:40:58 2014 > parseHostAndPort() end: host = 10005, port = 5900
    UltraVnc Thu Oct 23 19:40:58 2014 > openConnectionToVncServer(): connecting to 0.0.39.21:5900
    UltraVnc Thu Oct 23 19:40:58 2014 > connectWithTimeout(): Error connecting 22 (Invalid argument)
    UltraVnc Thu Oct 23 19:40:58 2014 > openConnectionToVncServer(): connectWithTimeout() failed.
    UltraVnc Thu Oct 23 19:40:58 2014 > acceptConnection(): openConnectionToVncServer() failed

btw.. I do see some strange output like in this line.

    UltraVnc Thu Oct 23 19:40:58 2014 > openConnectionToVncServer(): connecting to 0.0.39.21:5900

I dont know about that IP and Port, since I am using 5901.

I am using the repater to allow connection in both mode 1 and 2.

Any Idea about what could be the cause of this ?

**Comment by monkey-jsun** [comment]
Any update on this issue?  I seem to hit the same one right now.

root@ip-10-199-74-172:/home/ubuntu# 24.130.93.86 - - [07/May/2015 23:40:50] 24.130.93.86: Plain non-SSL (ws://) WebSocket connection
24.130.93.86 - - [07/May/2015 23:40:50] 24.130.93.86: Version hybi-13, base64: 'False'
24.130.93.86 - - [07/May/2015 23:40:50] 24.130.93.86: Path: '/websockify'
24.130.93.86 - - [07/May/2015 23:40:50] connecting to: localhost:5901
24.130.93.86 - - [07/May/2015 23:40:56] code 400, message Bad request syntax ('\x82\xd6\x93\xbc\x81K\x93\xbc\x81K\xb3\xa4\x81J\x93C\x81\xb4\x93C\x91C\x93\xbc\x81K\x91\xbc\x81F\x93\xbc\x81J\x93\xbc\x81LlC\x7f\xb7\x93\xbc\x81N\x93\xbc\x81I\x93\xbc\x81KlC~jlC~ZlC~\xadlC~BlC~klC\x7f\x80lC\x7f\x87\x90\xbc\x81K\x93\xbc\x85\xfb\x908\x88\x8f\xb9\xdepg\xba6$\x06\xcb\xb9\x15\x13\x99\xbd\x1c\x08\xca\xbb\x14')

**Comment by abelarteaga** [comment]
monkey-jsun,

Yes, it was a mistake from my side, check in the no-vnc options to connect to your server, try without the path: /winsockify..

from vnc_auto.html type of connection I am just sending port for websockify 6080, repeaterid you want to connect to and host.

hope it works for you
