### ISSUE TITLE
noVNC authentication error message

### ISSUE THREAD

**Issue by Abdul-Anshad-A** [kanaka/noVNC#423]
While trying to connect to VM console running on ESXi, If I enter a wrong password on noVNC client, latest chrome browser( Version 39.0.2171.95 m) is struck on message "Authentication scheme 2". But , if I try the same on firefox version 34 it displays "server disconnected code 1006" message.

Why is the chrome browser showing different behaviour ? Also, instead of displaying authentication failure message it displays "server disconnected".

I even tried the same procedure of entering wrong password on vnc viewer, It says server disconnected abruptly instead of displaying a authentication failure.

**Comment by samhed** [comment]
When trying to reproduce this I came accross this bug #467 but before the message is "gone" (due to the bug) I do see "Authentication failure" in both Chrome and Firefox. So I'm not sure about your description...

**Comment by DirectXMan12** [comment]
I'm closing this since @samhed could not reproduce, and there was no response from the original reporter.
