### ISSUE TITLE
noVNC re-writing <title>

### ISSUE THREAD

**Issue by arjitc** [kanaka/noVNC#425]
Hey,
I seem to be having an issue once all the noVNC .js files finish loading, they seem to re-write the <title> set by my page, could you tell me where this piece of code is (the one which re-writes the <title> to noVNC) ?

Thanks!

**Comment by samhed** [comment]
https://github.com/kanaka/noVNC/blob/master/include/ui.js#L654

**Comment by arjitc** [comment]
I edited out the line to the following, still re-writes to noVNC. Perhaps any other file with the same code in it?

    document.title = name + " ";

**Comment by DirectXMan12** [comment]
There are only two places that `document.title` is set -- one in `include/ui.js`, and the other in `vnc_auto.html`.  Did you base your page on `vnc.html` or `vnc_auto.html` (which doesn't use `ui.js`)?

**Comment by arjitc** [comment]
Hmm, weird this still happens and the <title> is renamed to noVNC when the noVNC console is launched

**Comment by arjitc** [comment]
Ah found it and commented it out

> //document.title = unescape(WebUtil.getQueryVar('title', 'noVNC'));
