### ISSUE TITLE
AltGR seems not workin with spanish keyboard

### ISSUE THREAD

**Issue by eduardbc** [kanaka/noVNC#429]
Hi,

I have been trying novnc with spanish language, some keys works but it apparently sends Alt instead of AltGR so characters like |@ can't be written.
I tested it with the latest version too. There is a similar isue reported before: 

https://github.com/kanaka/noVNC/issues/345

I testes it with 
firefox-34.0-1.fc19.x86_64
google-chrome-stable-36.0.1985.125-1.x86_64

Thanks

**Comment by DirectXMan12** [comment]
I suspect that this is a duplicate of #345, which has already been fixed.  Have you tried with the latest version of noVNC (0.5.1)?

**Comment by DirectXMan12** [comment]
I'm unable to reproduce this with v0.5.1.  Closing.
