### ISSUE TITLE
IOS ssl error

### ISSUE THREAD

**Issue by spambas** [kanaka/noVNC#437]
Suddenly when connecting through wss:// phones and tablets using IOS (i guess safari, need to confirm other browsers) give me an error in the output of websockify. Usually I get this output:

***.***.***.***: SSL/TLS (wss://) WebSocket connection
***.***.***.***: Version hybi-13, base64: 'True'
connecting to: localhost:*****

Now i get this:
_ssl.c:510: EOF occurred in violation of protocol

**Comment by samhed** [comment]
I don't have any issues with noVNC or websockify in iOS.

What happens? Can you connect? Are you seeing any errors in the JavaScript console?

**Comment by spambas** [comment]
Right now I only have an Ipad 1 to check it. I do not know if this ever worked, but richt now it gives me an error in both safari and chrome:

code 400, message Missing Sec-WebSocket-Version header. Hixie protocols not supported.

Still need to test the new ipad with chrome

**Comment by DirectXMan12** [comment]
closing due to no response.

**Comment by rogaha** [comment]
I'm getting the same error only from Safari: 

``_ssl.c:510: EOF occurred in violation of protocol``
