### ISSUE TITLE
keysyms.lookup() does nothing

### ISSUE THREAD

**Issue by ibc** [kanaka/noVNC#438]
In https://github.com/kanaka/noVNC/blob/master/include/keysymdef.js:

```
var keysyms = (function(){
    "use strict";
    var keynames = null;
   var codepoints = {"32":32,"33":33,"34":34,"35":35,"36", ...};

    function lookup(k) { return k ? {keysym: k, keyname: keynames ? keynames[k] : k} : undefined; }
    return {
        fromUnicode : function(u) { return lookup(codepoints[u]); },
        lookup : lookup
    };
})();
```

Note that `keynames` is always null, so `lookup(k)` **always** returns `{keysym: k, keyname: k}`. So what is the purpose of the `lookup()` function?

**Comment by ibc** [comment]
OK, I suppose that depends on how `utils/parse.js` is executed.

**Comment by DirectXMan12** [comment]
Yes, keynames is really only used for debugging.  If you wish, you can generate a keynames object, and get key names in debug output.

**Comment by ibc** [comment]
Clear. Thanks.
