### ISSUE TITLE
Does DES really work?

### ISSUE THREAD

**Issue by ibc** [kanaka/noVNC#439]
```
RFB.genDES('12345678', "This is the message to encrypt!!");

=> "This is the mess"
```

According to http://www.tero.co.uk/des/test.php it should return *0x05c9c4cafb9937d95bbfbedfc5d77f19a6cd5a5dab188a33dfd8979fc4b7b2be*.

**Comment by ibc** [comment]
Basically it just returns the first 16 chars of the given text.

**Comment by astrand** [comment]
The VNC authentication scheme is limited to 16 bytes. Perhaps the existing DES code uses this fact, and perhaps the calling code even depends on this?

**Comment by ibc** [comment]
OK, may you please provide any input (key and text) that produces a coherent output?

**Comment by ibc** [comment]
The fact is that passing "1234567812345678" as both `password` and `challenge` to `RFB.genDES()` also produces "1234567812345678" as output. Honestly I do not think this is working at all.

**Comment by kanaka** [comment]
@ibc if it didn't work, you wouldn't be able to authenticate with VNC servers at all. You aren't calling with the right types. DES.encrypt takes two arrays. RFB.DES takes an string and an array (which you can see if you look at the definition of genDES).

```
RFB.genDES("blah", [1,2,34]);
[181, 75, 21, 234, 243, 160, 78, 4, 44, 160, 233, 94, 64, 30, 39, 189]
```

Also, please note that the DES implementation that the VNC protocol uses is not standard DES.

**Comment by ibc** [comment]
Oh, clear, thanks a lot.
