### ISSUE TITLE
Unused variables in rfb.js

### ISSUE THREAD

**Issue by ibc** [kanaka/noVNC#440]
So many in the whole code, but those worry me:

https://github.com/kanaka/noVNC/blob/master/include/rfb.js#L896

* srvMsg
* clientMsg
* encoding

**Comment by ibc** [comment]
This is, it is required to call `this._sock.rQshiftStr(16);` but just don't assign the returned value to an unused variable:

```
var i;
for (i = 0; i < numServerMessages; i++) {
	this._sock.rQshiftStr(16);
}

for (i = 0; i < numClientMessages; i++) {
	this._sock.rQshiftStr(16);
}

for (i = 0; i < numEncodings; i++) {
	this._sock.rQshiftStr(16);
}
```

**Comment by DirectXMan12** [comment]
Actually, the correct thing to do here would be to use `rQskipBytes()`.  Can you submit a PR against the ones that you've found (if it's something that's not clear what we're skipping, please add a comment with what it does).  Alternatively, can you provide a list of the instances that you found?

**Comment by kanaka** [comment]
@ibc assigning return values to unused variables is actually sometimes used in dynamic/JIT languages (especially Lisps) as a form of document what the nature of the return value (and not using it implies the function has a side-effect). All decent JITs will optimize that away. But in this case it was probably unintentional. As @DirectXMan12 noted, this could be rQskipBytes with comment indicating what is being skipped.

**Comment by ibc** [comment]
Hi, I'm sorry but I cannot document what is being skipped since I don't know the nature of such a data.

```
                for (i = 0; i < numServerMessages; i++) {
                    var srvMsg = this._sock.rQshiftStr(16);
                }

                for (i = 0; i < numClientMessages; i++) {
                    var clientMsg = this._sock.rQshiftStr(16);
                }

                for (i = 0; i < numEncodings; i++) {
                    var encoding = this._sock.rQshiftStr(16);
                }
```

I assume those are some received messages to be ignored (and hence their names).
