### ISSUE TITLE
Please, no getElementById within the code

### ISSUE THREAD

**Issue by ibc** [kanaka/noVNC#446]
https://github.com/kanaka/noVNC/blob/master/include/display.js#L229

```
var cb = document.getElementById('noVNC-control-bar');
```

No please, really not. Don't force me to have a specific HTML element with "id=noVNC-control-bar". Please not. Yo have added that because ui.js and base.css use such an HTML element, but that is just the demo application, not the library. Please don't mix them.

Consider the case in which I want to have two isolated and 100% separated noVNC displays in the same web app.

Please, don't do that.

**Comment by ibc** [comment]
Note that `RFB` requires `Display`, so at the end `Display` is part of the core "library". If it needs to have a reference to an HTML element then let it to be passed via API/configuration.

**Comment by samhed** [comment]
Thanks for pointing it out. Apologies for being careless!

I'm in the process of changing a few more things in display.js, I will submit a new PR where I will include a fix for this issue.

**Comment by ibc** [comment]
So thanks!

**Comment by ibc** [comment]
Hi, any update about this? :)

**Comment by samhed** [comment]
Working on it

**Comment by ibc** [comment]
Thanks a lot!

**Comment by ibc** [comment]
:+1:
