### ISSUE TITLE
make failing (rebind.c missing)

### ISSUE THREAD

**Issue by drwahl** [kanaka/noVNC#449]
I am getting the following error:

user@foo:~/git/noVNC/utils [master] $ make
make: *** No rule to make target `rebind.o', needed by `rebind.so'.  Stop.

It looks like the file 'rebind.c' is missing.  Looking through the history, it appears this commit removed it:

6f5148648bd0e0ffa7ad00474c230f5f1ff4e39f

Based on the commit message, I suspect this was an accident.

**Comment by DirectXMan12** [comment]
Actually, the makefile should have been removed as well.  I missed it.  Thanks for the report, though!
