### ISSUE TITLE
Disconnect/Reconnect Issues

### ISSUE THREAD

**Issue by DirectXMan12** [kanaka/noVNC#452]
Commit 155d78b39933a396d2555376f4e70f976c30b86d unregisters certain event listeners (namely, 'open') that are only registered in the RFB constructor.  Since the RFB object is reused between disconnects and reconnects, meaning that the reconnect operation doesn't continue past the websocket opening.

If we create a new RFB object each time, in certain cases, the keyboard (and mouse) do not seem to be ungrabbed.

Some profiling in chrome seems to indicate that there are a couple other event handler leaks as well (I've been unable to track down which handlers these are, so they may be from something life setInterval).

**Comment by DirectXMan12** [comment]
Ok, so, the keyboard not being ungrabbed seems to occur when there is some delay between clicking disconnect, and the RFB object finishing up the disconnect (this can either be caused by relying on the disconnect timer, or in certain Chrome versions, where there's a multi-second lag between calling `close()` on a WebSocket and receiving the onclose event).

Consider:

1. RFB instance 1 is asked to disconnect, updating the UI to show the connect button.
2. We press connect, and RFB instance 2 is launched, and is the current instance, according to the UI
3. RFB instance 1's disconnect triggers, calling the UI's `onUpdateState` method, making the UI think that the current RFB instance (2) has disconnected.  However, RFB instance 2 is still running fine.
4. We press connect, and create a RFB instance 3, and thus now have multiple concurrent RFB instances in play (instances 2 and 3).

If we create a new instance in the UI's `disconnect` method, we still see the bad UI, but not the duplicate key events, since instance 3 never gets created (because `UI.disconnect` was never called).  This creates other problems.

If we just make `off` a no-op instead of creating a new RFB instance for each connection, we see similar behavior, where a newly started session can be suddenly disconnected if the previous session hadn't received a timeout or close event.

Note that in Firefox, the time between 'disconnect' and the onclose event is so small that I'm unable to easily reproduce this without fudging things (so the issue is only readily apparent in Chrome).

**Comment by DirectXMan12** [comment]
Fixing the underlying problem of being able to start a new session while the old is disconnecting should be fairly easy to fix if we just don't show the connect dialog box until we actually get a "disconnected" or "fatal" (which is where we update which button shows, anyway).  If we pair this with creating a new RFB object on connect, this should solve the issue (it would be wise to call `off` in the disconnect timer handler, though, just in case we receive a disconnect timer event *and then* receive a close event).

@kanaka, @samhed , @astrand : thoughts?

**Comment by samhed** [comment]
Good find! I was just about to type that exact suggestion, sounds good to me :+1:

**Comment by kanaka** [comment]
@DirectXMan12 We might still want a longer timer that fires if no event ever happens. I feel like I saw a recent bug that firefox doesn't always fire the close event. But anyways, I concur with the plan.
