### ISSUE TITLE
Remove the 'debian' directory

### ISSUE THREAD

**Issue by DirectXMan12** [kanaka/noVNC#453]
@kanaka: do you know if anyone is actively using this directory?  I suspect it's not actually all that useful or necessary (both Debian and Ubuntu seem to have their own version of the packaging).

**Comment by kanaka** [comment]
@DirectXMan12 I think it has probably served its purpose (to serve as template for packagers). I think @abligh was the main person who proposed fixes to that directory. @abligh are you still using the novnc/debian directory for anything. Forsee any problems if we drop it?

**Comment by abligh** [comment]
I suspect it may have bitrotted. I have a fixed up version somewhere that I use which you are welcome to, but I think most people would be better served by using the Debian or Ubuntu one (as I haven't tested it in every novnc situation). I'd be happy to see it go.
