### ISSUE TITLE
RFB._onUpdateState() never defined

### ISSUE THREAD

**Issue by ibc** [kanaka/noVNC#455]
I'm trying to figure out how the app can be notified about errors or connect/disconnect events in the RFB instance.

The only I see is that when something happens `_updateState()` is called, which at the end calls to `_onUpdateState()`:

```
if (oldstate === 'failed' && state === 'disconnected') {
  this._onUpdateState(this, state, oldstate);
} else {
  this._onUpdateState(this, state, oldstate, statusMsg);
}
```

But the fact is that `_onUpdateState` is defined **nowhere**:

```
$ ack _onUpdateState

include/rfb.js
531:                this._onUpdateState(this, state, oldstate);
533:                this._onUpdateState(this, state, oldstate, statusMsg);

tests/test.rfb.js
424:                client.set_onUpdateState(sinon.spy());
429:                var onUpdateState = client.get_onUpdateState();


$ ack set_onUpdateState

tests/test.rfb.js
424:                client.set_onUpdateState(sinon.spy());
```

This must throw an error for sure, doesn't it?

BTW: Why is so difficult for the app to be notified about RFB events? Could a good set of documented events be passed to the RFB constructor? My app really needs to be notified about the RFB status (to reconnect or warn the user or whatever) and I do not want to mangle the internal code of noVNC for that.

**Comment by ibc** [comment]
I want to imagine that, in order to use noVNC, I have to create a `RFB` instance by passing some config params and well documented event listeners ("connected", "disconnected", "error", "data received", etc etc).

And then the `RFB` prototype provides me with some API methods for whatever. And I may want to use some "noVNC helpers" within my app (those provided by the `Utils` module).

Is that? or am I totally wrong in my expectations?

**Comment by ibc** [comment]
I've found my self replacing `this._onUpdateState` with `this.onUpdateState`:

https://github.com/eface2face/noVNC-node/commit/d8f42a79494f27ed0720b255af31b92e6707953d

**Comment by samhed** [comment]
the callback _onUpdateState is created by make_property in util.js. The underscore prior to the name is there to indicate a private varible.

In your app where you create the RFB object you can attach a function to the onUpdateState callback, and in that callback you will get access to the rfb state.

Take a look at how we do it in ui.js if you need an example.

**Comment by ibc** [comment]
opps, sorry, my fault.
