### ISSUE TITLE
API documentation?

### ISSUE THREAD

**Issue by ibc** [kanaka/noVNC#456]
Hi, rather than looking at HTML demos, is it expected to provide a nice API documentation for the core libraries? I mean: RFB constructor, etc.

**Comment by kanaka** [comment]
It might have gotten a bit out of date but it's here: https://github.com/kanaka/noVNC/wiki/ModulesAPI

**Comment by ibc** [comment]
Thanks. BTW have you considered having the doc in a repo folder so it is 100% related to the current code status? For example:

https://github.com/theturtle32/WebSocket-Node/blob/master/docs/index.md

**Comment by kanaka** [comment]
@ibc I think I considered it but I can't recall why I didn't go that route. Perhaps because I wanted it easier to edit, but now that pull requests can be generated by editing files directly in the interface, that's not a relevant reason anyways.
