### ISSUE TITLE
If no target if given to RFB all get broken

### ISSUE THREAD

**Issue by ibc** [kanaka/noVNC#460]
Just try to not provide the `RFB` without a proper "canvas" target. It will fail everywhere:

* It will try to call `this._sock.close()` but the WS socket does not exist due the `Display` error.
* If a try/catch is set, then it will fail due to "Uncaught TypeError: Cannot read property 'get_render_mode' of null" which happens at the end of the RFB constructor:

```
  var rmode = this._display.get_render_mode();

  this._updateState('loaded', 'noVNC ready: ' + rmode);
}
```

This is, even if "state:fatal" was already emitted, the RFB constructor continues.

This must be really more robust.

**Comment by ibc** [comment]
Even if some of those errors are mitigated (with try/catch + return) the RFB will still emit "state:connect".

**Comment by ibc** [comment]
It is much better to really throw an error in the constructor if the Display fails, so the app won't call ' connect()`  on the aborted `RFB` instance. And better not to emit "state:failed" at all if the error happens while in the constructor. This is really more natural:

```
        try {
            this._display = new Display({target: this._target});
        } catch (exc) {
            Util.Error("Display exception: " + exc);
            throw(exc);  // We are done. It failed, period.
        }
```

A library should not emit anything if it fails during the constructor. That's what try/catch is for in the user app.

**Comment by ibc** [comment]
Hi, any update about this? I'm pretty sure of what I'm suggesting: Please don't call events if something throws an error in the class constructor.

**Comment by aruiz** [comment]
I'm being hit by the same error. @ibc has a point here

**Comment by DirectXMan12** [comment]
Hey, sorry, I've been a bit busy.  I thing you're correct here -- throwing an exception is probably a good idea.  It's probably also a good idea to add a comment making it clear that no setup should occur before this point, as it will not be torn down on the exception.  @kanaka , thoughts?

**Comment by kanaka** [comment]
Yes, I agree that's better behavior.
