### ISSUE TITLE
Repeated tiles on Android

### ISSUE THREAD

**Issue by czo** [kanaka/noVNC#462]
I try to connect noVNC with websockify to Xen HVM VNC server. It's seems to working fine from my Mac and iPhone, but not from my Android with Chrome. I checked also with Browser.apk, and that produces the same problem. 

It's seems to repeating tiles multiple times, before drawing the next tile. When i comment out everything except RAW, i get repeated lines. 

Everything works fine on Android 5.0.1 x64-64 Emulator. Tested on CM12 (4.4.4) HP Touchpad.

Anyone had seen this problem before?

![screenshot_2015-02-28-18-41-32](https://cloud.githubusercontent.com/assets/11247547/6427316/33f84a34-bf7d-11e4-8490-274a4635cb6f.png)
![screenshot_2015-02-28-19-07-57](https://cloud.githubusercontent.com/assets/11247547/6427317/3421d912-bf7d-11e4-9cd8-916dfcc70c1c.png)

**Comment by samhed** [comment]
Hm, no this is not something I've seen before. I test noVNC with android quite frequently.

**Comment by czo** [comment]
Maybe, this is a bug with my device, can you help me to figure this out?

**Comment by samhed** [comment]
Hm, I don't know.. You should start by trying to investigate the differences between your device and the android emulator (where it works fine). Is the server set up exactly the same on both?

**Comment by czo** [comment]
I had time to check with multiple android devices. It's seems fine all of these devices, so i think, it's seems to a problem with mine. I have an originally webos based tablet with unofficial cyanogenmod installed, so i close this bug, because i cant reproduce this with devices other than my tablet.
