### ISSUE TITLE
Authentication errors are not displayed

### ISSUE THREAD

**Issue by samhed** [kanaka/noVNC#467]
Since e543525 which was merged as of #458 we create a new RFB object after authentication failiure and do thus loose the rfb_state. The error just flashes by in the status bar and you can see it in the javascript console.

**Comment by samhed** [comment]
@DirectXMan12 How do you think we should solve this?

**Comment by DirectXMan12** [comment]
Ok, so the reason that I chose to create a new RFB object on close and not on open is that the UI currently depends on the RFB object being created when the UI initializes (it updates the status bar once the constructor finishes and moves to the "loaded" state, etc).  We could rework how that part of the UI works such that the RFB object gets created on initialization, and the status bar defaults to having a class of `noVNC_status_normal` with some initial boilerplate text).  Thoughts?

**Comment by samhed** [comment]
Yep, that sounds good!

**Comment by kanaka** [comment]
Works for me.
