### ISSUE TITLE
some confused about websockify

### ISSUE THREAD

**Issue by liuqiangqiang8** [kanaka/noVNC#468]
About websockify this class, I have a puzzled, I hope there are good man to give me the answer.
It handle http request by way of sub-processes.
It is more appropriate than using multiple threads?

**Comment by DirectXMan12** [comment]
The issue is that Python has Global Interpreter Lock (GIL).  This means that only one thread can actually be executing Python code at any given time.  In contrast, since each subprocesses has its own instance of the Python interpreter, multiple processes can run Python code simultaneously.

**Comment by liuqiangqiang8** [comment]
Multi-process sounds very good. 
In a multi-process, I use 10 chrome client to connect novnc server, the result is Child process creation and destruction frequent。

I have two puzzled：
1.Primary process may appear the phenomenon of suspended animation
2.Frequent child thread creation and destruction, it may affect the stability of the operating system?
