### ISSUE TITLE
Display#autoscale(): mouse pointer does not match

### ISSUE THREAD

**Issue by ibc** [kanaka/noVNC#471]
I retrieve the size of the shared target in the `onFBResize` event, let's say 800x600 px. Then I call to `rfb.get_display().autoscale(400, 300)`. This happens:

* The canvas element is resized to 400x300, ok.
* The shared mouse pointer does not match the local mouse pointer at all.

Do I miss something? I expected this to be handled by the `autoscale()` method.

**Comment by JamieMcDonnell** [comment]
I am having the same issue - I am scaling the canvas based on window.width / window.height. I size the canvas initially when sharing starts, then call rfb.get_display().autoscale($(window).width(), $(window).height(), false) on window.resize event.

The canvas is scaled as expected (both upscaled and downscaled) but the mouse pointer positions do not match between the host and the client.

Is there a scale setting that is missing in autoscale to resolve the cursor position?

**Comment by ibc** [comment]
OK, it seems that the following is required:

```
var ratio = rfb.get_display().autoscale(width, height, downscaleOnly);

rfb.get_mouse().set_scale(ratio);
```

Guys, don't take me wrong, but it is so hard to know how noVNC works due the terrible lack or real and updated API documentation. Trying to figure out how things work by checking the included demo application is not very comfortable.

**Comment by kanaka** [comment]
@ibc this is brand new functionality (at least, in a working state worth documenting that is), but yes we should add it to the API docs: https://github.com/kanaka/noVNC/wiki/ModulesAPI @ibc as you run into API issues that are missing from the docs, could you update the API wiki documentation? That would be really helpful.

**Comment by DirectXMan12** [comment]
@kanaka : do you think it's worth it to have a folder with some markdown API docs, so that whenever we add functionality, we can update the docs it the same commit?  These would include a sample usage of the new feature, so that it would be clear how to use it.

We could then have a "always include a documentation update" rule just like we have a "always include unit tests" rule.

**Comment by ibc** [comment]
I suggested the same, but it was not accepted: #456

Yes, I agree. Having the doc in a docs/ folder within the repo is a good think because:

* It allows to unify commits and API documentation.
* It allows the user to check the documentation for a specific Git release, something that is imposible with a wiki.

**Comment by ibc** [comment]
>  @ibc as you run into API issues that are missing from the docs, could you update the API wiki documentation?

I'd would do it @kanaka, but:

* I do not have write access to the wiki, and
* I strongly prefer approach #456 so I can maintain my noVNC fork and make PR including code and doc updates.

**Comment by DirectXMan12** [comment]
I think, in #456 @kanaka suggested that going that route would be fine now, so I think that's how we should move forward with this.  @kanaka , sound good to you?

**Comment by kanaka** [comment]
yep, good with me.

**Comment by ibc** [comment]
OK, let me make a PR in the next days.
