### ISSUE TITLE
Mouse not working on Firefox/Mac

### ISSUE THREAD

**Issue by proctar** [kanaka/noVNC#472]
Hi,

It seems like noVNC is not catching/getting/forwarding the mouse input on Firefox 36.0.1, MAC OS.
There is a QEMU/KVM server behind, running Android 4.41 x86.

MAC OS Chrome/Safari work well.
WIN7 Firefox works well.

On Mac OS / Firefox, mouse events don't do anything.

No visible error in JS logs.

**Comment by DirectXMan12** [comment]
Is the working Win 7 Firefox also 36.0.1?

**Comment by proctar** [comment]
Firefox 36.0.4.

**Comment by fabian-z** [comment]
Have you tried with a new Firefox profile? This was the culprit for me in #481

**Comment by proctar** [comment]
Good catch, that was it. Creating a new firefox profile solved the problem... Not sure what's wrong with my default profile tough.

**Comment by fabian-z** [comment]
Check my corrected comment in #481, this may be the dom.w3c_touch_events.enabled setting in about:config.
I don't remember changing it manually too, maybe this was default for former versions of Firefox.

**Comment by proctar** [comment]
You're right, "dom.w3c_touch_events.enabled" was set to 1, but I never changed that manually before.

I changed it back to 0, reloaded my page, and noVNC was then able to catch mouse events.
