### ISSUE TITLE
Microsoft Surface: trackpad does not work (but touch screen does work)

### ISSUE THREAD

**Issue by ibc** [kanaka/noVNC#476]
Testing noVNC in a Surface computer (which has both a touch screen and a trackpad).

The screen touch does work (I can navigate and interact in the shared canvas, and I see "onMouseButton" events in the noVNC logs), but the trackpad does not work at all. It seems that it has been "disabled" given that a touch device has been detected.

How to enable both?

**Comment by ibc** [comment]
Here is the "problem" right?
https://github.com/kanaka/noVNC/blob/master/include/input.js#L332

**Comment by ibc** [comment]
I've "fixed" it by adding a new option "enableMouseAndTouch" in the RFB constructor in my noVNC fork:

https://github.com/eface2face/noVNC-node/commit/d60a0b9e9f652487e7bd0f131598815405851117

**Comment by DirectXMan12** [comment]
Hey, can you weigh in on #369 and/or submit a PR?  The changes look good, and it would be great if you could throw in a UI update in the PR.

**Comment by samhed** [comment]
Connecting a mouse to an android tablet works fine in noVNC. Both mouse clicks and touches work

**Comment by ibc** [comment]
> Hey, can you weigh in on #369 and/or submit a PR? The changes look good, and it would be great if you could throw in a UI update in the PR.

I'm sorry, but I have no time to contribute to the original project. I'm coding all the improvements and fixes I can in my [fork](https://github.com/eface2face/noVNC-node/) because I need a properly "browserifable" noVNC library that exposes nothing to `window`.

> Connecting a mouse to an android tablet works fine in noVNC. Both mouse clicks and touches work.

May be, but that is not true in a Microsoft Surface device. Tested.

**Comment by samhed** [comment]
Fixed by 4b20f2364c3924e89ccedf7eda56af322e5e9e1e
