### ISSUE TITLE
rfb.testMode undefined in vnc_playback.html and vnc_perf.html

### ISSUE THREAD

**Issue by ZabelTech** [kanaka/noVNC#479]
Hello,

in addition to #477
i just forked your repo to try to port it to clojure/clojurescript mainly for learning that language.
So i tried get the playback working first. 
First thing, in the [wiki] (https://github.com/kanaka/noVNC/wiki/Performance-notes#session-recording-and-playback) it says the capture is expected at tests/data but you have to put in include/
Now then it load it but throws an exception that rfb.testMode is undefined. 
I fgreped the repo but it is defined nowhere, so this is not supported anymore?

**Comment by samhed** [comment]
Check my answer in #477

**Comment by samhed** [comment]
On second thought, I'll leave this open until the fix is merged.
