### ISSUE TITLE
Touch input is always chosen for Firefox

### ISSUE THREAD

**Issue by fabian-z** [kanaka/noVNC#481]
I have an issue where Firefox will always choose touch input in [include/input.js](https://github.com/kanaka/noVNC/blob/master/include/input.js#L335) (around line 300, in the grab/ungrab functions), regardless of the presence of a real touch input.

The corresponding line seems to be
```
if ('ontouchstart' in document.documentElement) {
...
}
```
which always returns true for me in Firefox, although I have no touch device (and I am not running with developers touch simulation). The problem is not specific to a VNC server and only occurs with Firefox (latest v. 37.0.2), but not with Chromium or Opera.

Please see [this blog](http://www.stucox.com/blog/you-cant-detect-a-touchscreen/#touch-apis) for a possible explanation. (Checking for the existance of Touch APIs vs. checking for a used touch input)

It is worth mentioning that the latest master exposes multiple issues with Firefox for me, but I was able to get noVNC working with Firefox with commit 3b4fd00 and v0.5.1 by commenting out the problematic ontouchstart expression completely to force mouse events.

May be related to #369 & #476 & most likely related to  #472

**Comment by samhed** [comment]
What client platform are you using? I have tested Firefox on Fedora 20 and on Windows 8.1, and I am not seeing your issue.

**Comment by fabian-z** [comment]
This happens on an up to date ArchLinux (x86_64, Kernel 3.19.3-3) system for me. Indeed the issue is not bubbling up if tried on a Windows system.

**Comment by fabian-z** [comment]
I just tried and was unable to reproduce the issue with a fresh Firefox profile. It might have been an addon or some Firefox settings which caused the problem - still to investigate.
Sorry for the noise, this can be closed.
