### ISSUE TITLE
problem with vnc.js ?

### ISSUE THREAD

**Issue by plabanowski** [kanaka/noVNC#484]
Hello,
I do not know if it's a problem or not. but some implementation loss is quite vnc.js blocker.
removing vnc.js is normal?

**Comment by samhed** [comment]
Could you elaborate what you mean? vnc.js?

**Comment by plabanowski** [comment]
this file is missing ./novnc/include/vnc.js . if this is nomaly ! 
sorry for the noise

**Comment by samhed** [comment]
vnc.js was removed back in 2012 :)
