### ISSUE TITLE
Stream/Show noVNC screen using Python/Django to a web page without exposing the port or URL

### ISSUE THREAD

**Issue by gowthamsadasivam** [kanaka/noVNC#489]
I have noVNC server running in my **localhost:port** and also have a **Django** web application running on port **80**. I wanted to **stream/show** this noVNC screen (localhost:port/vnc_auto.html) to one of the web pages which can be seen by the users after they login to the Django web application. I can't embed the vnc page without exposing the port to public IP, if I do that it'll be insecure and anyone with the IP:port can open the noVNC screen.

I wanted to know, ***Is there a service/tool/way to stream/show the noVNC screen to the users through the Django/Python web page without exposing IP:Port to public?***

**Comment by DirectXMan12** [comment]
I know this comes a bit late, but you could use the new websockify token plugin API to accomplish something like this.
