### ISSUE TITLE
noVNC on Android 4.0.4 works only with Firefox

### ISSUE THREAD

**Issue by cis-oip** [kanaka/noVNC#492]
On my tablet PC noVNC client works only with Firefox (Firefox for Android). With other browsers (Opera, Chrome, native browser etc.) noVNC causes internet-browser crash.

My tablet PC: Huawei MediaPad 10 Link, Android 4.0.4

**Comment by DirectXMan12** [comment]
It doesn't look like the built-in browser supports websockets on Android 4.0.4 (http://caniuse.com/#search=websockets), since Android 4.0.4 is quite old at this point.  Which version of Chrome are you using?

**Comment by cis-oip** [comment]
Not working with:
* Chrome 42.0.2311.111 (Blink 537.36, JavaScript V8 4.2.77.15)
* Opera 29.0.1809.92697

Works perfect with Firefox 38.0.5 (for Android) on the same device.

The strangest thing - in Chrome and Opera noVNC client may works about 1 second (draw once remote desktop), then crashes browser. How I can know where is the bug?

**Comment by samhed** [comment]
You can connect your device to a PC and debug using ADB:

https://developer.chrome.com/devtools/docs/remote-debugging

**Comment by cis-oip** [comment]
I have connected device to desktop PC, run debug and got this.

**First run** it seems to be working, Chrome not crash, but screen was strange:
Screen in noVNC client: http://goo.gl/lYJvRC
Console output:
```
util.js:218 	Msg: noVNC ready: native WebSockets, canvas rendering
websock.js:231 	WebSocket connection to 'ws://./' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
util.js:218  	Msg: Starting VNC handshake
util.js:218  	Msg: Sent ProtocolVersion: 003.008
util.js:218  	Msg: Authenticating using scheme: 16
util.js:218 
util.js:218  	Msg: Authentication OK
util.js:218  	Msg: Authentication OK
util.js:218  	Msg: Connected (unencrypted) to: ai-pc
```

I closed Chrome and run it second time. When I run it **second time** - I've got Chrome crash. The console output was the same as first time:
Screenshot: http://goo.gl/HNFmDk

It was strange - first run it works (with problems, but it works!), second run it crash. The console output was the same both times.

May be I can determine the problem more precisely?

**Comment by zarmhast** [comment]
@cis-oip Just out of curiosity: are you connecting to the same machine you loaded the noVNC page from? Your log mentions ai-pc, which indicates that it is a local machine. I don't know since which Android version it was, but Chrome could not resolve machine names on local networks properly on some 4.x versions of Android. Firefox worked fine with local machines though.

Try using the IP address?

**Comment by samhed** [comment]
Closing due to no response.
