### ISSUE TITLE
How to do no-compression for best clarity for local network?

### ISSUE THREAD

**Issue by liudr** [kanaka/noVNC#494]
Hey, thanks for the great project!

I'd like to know how to set up noVNC so it will not do compression or at least loss-less compression so the viewer will see texts without the blur. The server and client/viewer are on the same local network and there are no other devices on this network so bandwidth is not an issue.

Let me first explain why I need no compression and local network. I teach electronics using Arduino. It is a USB device you plug into your computer to read sensors and run motors. The thing is, some of my students are always unable to install the hardware driver and software successfully on their own computers. It's unimaginable from tech-savoy people like ourselves but this is happening. We shouldn't just give up on them. So my solution is a computer that already has the USB device driver and software installed and ready to go. This way everyone can use the setup at home. To make this option cheap, I am using raspberry pi, a $35 single-board linux computer with no keyboard/mouser or screens. That is where noVNC comes in. The easiest way to get a student to use this set up is to have him connect a display, keyboard and mouse to it. But since most students will have laptops or even just tablets, they don't have spare displays or keyboards around them. It would be nice to run noVNC on a web browser while both raspberry pi and student laptop are connected to a wifi network, provided by a router (cheap enough). So there is no issue with bandwidth since it is local network but I do need clarity around texts since they will do programming on the browser.

**Comment by DirectXMan12** [comment]
So, only the JPEG compression is lossy compression.  You could disable JPEG compression from the noVNC side (by modifying the list of encodings in noVNC @ https://github.com/kanaka/noVNC/blob/master/include/rfb.js#L39-58 to remove the `JPEG_quality_xyz` pseudo-encodings), or, depending on your VNC server, you could disable the JPEG-based compression on the server side.  

You can re-open this if you have further questions.
