### ISSUE TITLE
Can't reconnect with new version of noVNC

### ISSUE THREAD

**Issue by MOZGIII** [kanaka/noVNC#495]
Just update to the latest version from fc00821 and it does not reconnect after the second attept.

Quick link for what changed since then:
https://github.com/kanaka/noVNC/compare/fc00821...master

I updated my code to the latest version, however it just does not work like it used to.

My reconnect code (based on `vnc_auto.html`):

```javascript
var connect_func;

function updateState(rfb, state, oldstate, msg) {
  ...
  if (state == "failed" && oldstate == "connect") {
    retry_connect();
  }
}

var reconnect_attempt = 0;
function retry_connect() {
  if(reconnect_attempt > 10) { return; }
  reconnect_attempt++;
  var reconnect_timeout = reconnect_attempt * 1000;
  console.log('Reconnecting in ' + reconnect_timeout + ' ms...');
  setTimeout(reconnect, reconnect_timeout);
}

function reconnect() {
  console.log('Attempting to reconnect...');
  if(typeof(connect_func) !== 'undefined') {
    connect_func();
  }
}

window.onload = function () {
  ...
  try {
    rfb = ...
  } catch() {...}
  connect_func = function() {
    console.log("Connecting to:", rfb, host, port, password, path);
    rfb.connect(host, port, password, path);
  }
  connect_func();
};
```

It used to correctly reconnect after some time, and now this code just hangs on the second attemt (or sth like that).

**Comment by MOZGIII** [comment]
As seen from logs, I there is no handling of subsequent reconnection requests.
![a6ceb-clip-98kb](https://cloud.githubusercontent.com/assets/265507/8096880/a4fcedc2-0fe4-11e5-9f1e-63a418980457.png)
As you can see, there is no second `on-close event`. On the previous version it was there.

**Comment by DirectXMan12** [comment]
See the changes from e543525 (we overhauled the reconnection code due to some issues with event handlers, meaning you should create a new `RFB` instance for each new connection).

**Comment by MOZGIII** [comment]
This should be fixed in the `vnc_auto.html` example then - it is implemented wrong in there.

**Comment by DirectXMan12** [comment]
I am unclear as to what you are looking at -- `vnc_auto.html` does not try to reconnect at all.

**Comment by MOZGIII** [comment]
I reviewed it again, and it seems like `vnc_auto.html` does not use (or at least include) `ui.js`. However at line 233: https://github.com/kanaka/noVNC/blob/master/vnc_auto.html#L233

```javascript
UI.updateState(null, 'fatal', null, 'Unable to create RFB client -- ' + exc);
```

That confused be a bit. Is it supposed to be like that? I think `UI` is undefined, can't check though.

**Comment by DirectXMan12** [comment]
> I reviewed it again, and it seems like vnc_auto.html does not use (or at least include) ui.js

Correct.

> However at line 233: https://github.com/kanaka/noVNC/blob/master/vnc_auto.html#L233
> ```javascript
UI.updateState(null, 'fatal', null, 'Unable to create RFB client -- ' + exc);
```
> That confused be a bit. Is it supposed to be like that? I think `UI` is undefined, can't check though.

Whoops, that's a typo.  I'll fix it.  Thanks!

**Comment by MOZGIII** [comment]
I think messed up with previous PR (it is to my fork, not the upstream), so I made a new one.
