### ISSUE TITLE
display of noVNC and virsh console not full synchronously when Linux goes into fsck rescue model

### ISSUE THREAD

**Issue by changliwei** [kanaka/noVNC#500]
When Linux System  goes into fsck rescue  model. the screen of noVNC not   full synchronously, and  perhaps web noVNC  delay some frames compare to console  output. how can solve it. 

display from  virsh console  $vm
![image](https://cloud.githubusercontent.com/assets/1563996/8253584/e99833e8-16c3-11e5-9a34-94ae6cbb5066.png)
but noVNC  stay still 
![image](https://cloud.githubusercontent.com/assets/1563996/8253554/b30e986c-16c3-11e5-8451-8d672c64e6e6.png)

**Comment by changliwei** [comment]
Web NoVNC size is 720*400

**Comment by DirectXMan12** [comment]
If you're still experiencing this issue, please reopen this bug.  If you do so, please include any debug output on your browser's console.
