### ISSUE TITLE
Mouse Pointer Disappears in IE10 and IE11

### ISSUE THREAD

**Issue by romaan** [kanaka/noVNC#501]
I connected to my Windows XP machine which runs a noVNC service via a web browser (Internet Explorer). When I move the mouse into the VNC viewer area in Internet Explorer, the mouse disappears.

This does not happen in google chrome or firefox

**Comment by samhed** [comment]
IE does not support data URI which is what we use for a local cursor in noVNC. I suspect that your server is configured to never display a cursor on the server side? Your server should display a server-side cursor unless the client can render it's own.

**Comment by romaan** [comment]
Thanks. Enabled Remote Cursor if IE and that works.
