### ISSUE TITLE
Cannot use keyboard when embedding noVNC via iframe

### ISSUE THREAD

**Issue by asmartin** [kanaka/noVNC#506]
Hello,

I am embedding noVNC 0.5.1 in another webpage using an iframe:
`<iframe id="vnc" src="noVNC/vnc_auto.html?host=myhost&port=5901&resize=true" width="825px" height="635px"></iframe>`

I am able to connect to the VNC server just fine and use the mouse, however keyboard events are not captured. In the above example, the VNC session's resolution is 800x600, so as you can see I've oversized the iframe a bit (by 25px on the width and 35px on the height). This gives a bit of extra gray space in the iframe on either side of the VNC window. I've found that if I click on this gray space on either side of the VNC window, I am then able to capture the keyboard successfully. I can reproduce this problem in both Firefox and Chrome. This issue may be related to #360. 

Please let me know what I can do to resolve this problem. Thanks!

**Comment by DirectXMan12** [comment]
It may be due to giving focus to noVNC.  Have you tried clicking on the status bar at the top of the frame?  Sometimes that's necessary, depending on the browser.  OpenStack Horizon (the OpenStack dashboard) embeds noVNC in an iframe, so it may be worth taking a look at what they do.

**Comment by jeffforbes** [comment]
By default an HTML5 canvas does not have tabstops and therefore there is no keyboard focus. When a canvas is opened in a browser window, it must inherit the focus of the parent window.
When the canvas is opened in an iframe it has no keyboard focus, this is what is causing your problem. Add the atrribute "tabindex": 0 to your canvas setup and then  in the updateState callback function, set the focus to the canvas when the state is "normal".

**Comment by asmartin** [comment]
Sorry for the delay in my response, I thought I had posted an update in July but must have only drafted it.

I attempted to use `iframe.contentWindow.focus()` called from `$(document).ready()` in the parent page; this seems to work most of the time, but not always:
````
    <script type="text/javascript">
      // focus the iframe
      function setFocusIframe() {
          var iframe = $("#vnc")[0];
          iframe.contentWindow.focus();
      }

      // set the iframe focus (must be done with setTimeout)
      function focusIframe() {
         setTimeout(setFocusIframe, 100);
      }

      $( document ).ready(function() {
         focusIframe();
      });
    </script>
````

Here's how I tried implementing your suggestion with "tabindex" and the `updateState` function:
````
            <canvas id="noVNC_canvas" width="640px" height="20px" style="tabindex:0;">
                Canvas not supported.
            </canvas>
....
        function updateState(rfb, state, oldstate, msg) {
            var s, sb, cad, level;
            s = $D('noVNC_status');
            sb = $D('noVNC_status_bar');
            cad = $D('sendCtrlAltDelButton');
            switch (state) {
                case 'failed':       level = "error";  break;
                case 'fatal':        level = "error";  break;
                case 'normal':       level = "normal"; break;
                case 'disconnected': level = "normal"; break;
                case 'loaded':       level = "normal"; break;
                default:             level = "warn";   break;
            }

            if (state === "normal") {
                document.getElementById("noVNC_canvas").focus();
                cad.disabled = false;
            } else {
                cad.disabled = true;
                xvpInit(0);
````

However this does not appear to work. Have I configured it incorrectly?

**Comment by Thalagyrt** [comment]
I'm also experiencing this, and the aforementioned fix doesn't work for me either. If there's anything I can do to help debug this, let me know!

**Comment by DirectXMan12** [comment]
If you click the title bar in `vnc_auto.html` does it work?

**Comment by asmartin** [comment]
Yes, after clicking the title bar it works as expected

**Comment by jeffforbes** [comment]
Clicking anywhere in the iframe except on the canvas will set the keyboard focus to the canvas.
Try tabindex=0 outside of the style attribute.
We are using jquery so this works for us called inside of updateState:
rfb.get_keyboard().set_focused(true);
$("#canvas").focus()   //The canvas id is passed as an attribute to rfb

**Comment by Thalagyrt** [comment]
Setting the tabindex to 0 seems to have done the trick here.

**Comment by DirectXMan12** [comment]
Ok, closing as solved.

**Comment by jeffforbes** [comment]
Well, with more testing, we are seeing  intermittent keyboard focus when the noVNC canvas is in an iframe. Focus always returns when the page is reloaded. A page reload was not effective before the above changes were made with the tabindex and setting the focus on the canvas. Of course, clicking the mouse on the black bar also corrects the keyboard focus. Any suggestions on how to investigate  this intermittent behavior? It seems to happen more often in firefox than chrome or opera; however, I have not done an exhaustive analysis.

**Comment by VoidVolker** [comment]
Same problem meet. Fixed by canvas attribute `tabindex="0"` and manual function call `canvas.focus()` on vnc tab selecting.

**Comment by dpiccone** [comment]
I have the same problem with NoVNC running in an iframe, solved through `iframe.focus()` for all the browsers but IE11 and Edge, where to get proper focus on the canvas and use the keyboard I have to click on the title.
