### ISSUE TITLE
DesktopResize & TigerVNCServer

### ISSUE THREAD

**Issue by chrism2671** [kanaka/noVNC#508]
Hello,

I think I've configured this correctly. I've got TigerVNCServer set up in the most vanilla way (defaults), Ubuntu 14.04 + XFCE.

I'm trying to get the DesktopResize functionality to work. I can resize the desktop using xrandr, and the RemoteResize function seems to work via TigerVNCViewer. I'm trying it with the default set up on novnc.com however, and it doesn't work.

Any tips on what strategy I can take to debug this?

Thanks!
Chris.

**Comment by samhed** [comment]
novnc.com is not using the latest version of noVNC. The functionality you are after is not included in the old version running on that site.

You should set up your own websockify server and present noVNC from your own machine where you can use the latest version.

**Comment by chrism2671** [comment]
Awesome thank you!
