### ISSUE TITLE
connect via proxmox api

### ISSUE THREAD

**Issue by whoim2** [kanaka/noVNC#512]
Hello! Please, help..

I use proxmox api for start vncproxy and connect to QEMU VM.
"HTTP:   	POST /api2/json/nodes/{node}/qemu/{vmid}/vncproxy"
http://pve.proxmox.com/pve2-api-doc/
API return array data:
Array
(
    [cert] => -----BEGIN CERTIFICATE-----...
-----END CERTIFICATE-----

    [user] => api@pam
    [upid] => UPID:...:api@pam:
    [port] => 5900
    [ticket] => PVEVNC:55AD5F03::LwJkR1Fc....imCg==
)

What i may connect to VM use this data?

**Comment by kanaka** [comment]
@whoim2 sorry, I don't think anybody on the noVNC team is familiar with proxmox. This sounds fairly specific to proxmox so I would try asking on the proxmox project. I'm going to go ahead and close this. If you can clarify how this relates to noVNC then we can re-open.
