### ISSUE TITLE
how to setup novnc with "https://" ?

### ISSUE THREAD

**Issue by comsyspro** [kanaka/noVNC#514]
Hi,

I installed successfully novnc on an ubuntu 14.04 server and connected with the launch.sh to a tightvnc server 2.7.10 (port 5900) which is installed on a server with windows 7. I also made a self.pem. Now I have the problem that I can't connect over "https://ubuntuserver-ip:6080/vnc.html?...". The normal URL "http://ubuntuserver-ip:6080/vnc.html?..." works fine. Is there a possibility to use novnc over a secured SSL connection with "https://" and if yes, how you can get it work?

**Comment by comsyspro** [comment]
In the meanwhile I got it work and the question can be closed.

**Comment by geostant** [comment]
@comsyspro 
Can you please elaborate what have you done ?

I would like o implement a self signed certificate as well to my remote connection.


Thanks

**Comment by samhed** [comment]
@geostant this might be helpful https://github.com/kanaka/websockify/wiki/Encrypted-Connections

**Comment by geostant** [comment]
@samhed 
Thanks,
I can see in `/var/log/novnc.log` that the certificate isn't working
`handler exception: [Errno 336265225] _ssl.c:351: error:140B0009:SSL routines:SSL_CTX_use_PrivateKey_file:PEM lib`

I'm running novnc inside a docker on my local machine (for tests, there is no domain attached)

**Comment by samhed** [comment]
I don't know what `/var/log/novnc.log` is, but I assume it is where you chose to print logging from your websocket proxy. Are you using websockify?

Works perfectly fine for me using websockify and following the instructions on that page.

**Comment by geostant** [comment]
I've figured that out.
gave  my container a static hostname (i.e. `my-domain.com`) and gave the certificate a matching common-name while generating it.

Thats it, it's secured :)

**Comment by ik-j** [comment]
Can someone plz share all the commands for starting noVNC over https. I am using the below command but it isnt working:
./launch.sh --vnc calibertest.cloudapp.net:5900 --cert /etc/ssl/certs/ca-certificates.crt

**Comment by samhed** [comment]
In what way isn't it working? Did you generate a certificate?

**Comment by ik-j** [comment]
@samhed Thanks for responding. Yes I had generated a certificate self.pem and then it worked but now I have bought an SSL certificate which I am going to try.

**Comment by ik-j** [comment]
@samhed @comsyspro I have successfully noVNC working over HTTPs using self signed certificates. I am having problem using a 3rd party SSL certificates, that has intermediate certificates as well. I combined them on a single file as suggested by noVNC official Git page but still I am unable to make it work.

I have noVNC installed on a ubuntu machine, and want to install SSL on it, there is tightVNC on a windows server which I am trying to connect to.

Help would be appreciated. :)

**Comment by samhed** [comment]
what exactly is going wrong?

**Comment by ik-j** [comment]
I am not able to make it work. Firefox js console has error like cannot connect to wss://...

**Comment by ik-j** [comment]
Actually I am a noob. I want to use noVNC over https. I have purchased SSL certs from GeoTrust. They hv given me an intermedate cert as well. I installed the certificates on a windows machine where TightVNC is installed and running. I have setup noVNC on an ubuntuVM which his hosted on windows machine as well. I am able to generate self-signed certs on ubuntu and connect to https to noVNC via self-generated certs. But I am more interested in using my purchased certs.

I am not sure what should I do to make noVNC work with https using my purchased certs. I would very much appreciate if someone can tell me the basic steps.

**Comment by ik-j** [comment]
I get errors like: handler exception: [SSL] PEM lib (_ssl.c:2699)

**Comment by qixinwuchen** [comment]
> @geostant this might be helpful https://github.com/kanaka/websockify/wiki/Encrypted-Connections

fuck you,  who is geostant

**Comment by Shiritai** [comment]
For those who use certbot (letsencrypt) and nginx as reverse proxy and want to assign novnc behind nginx, the following steps works for me:

Lets say we want to host `https://novnc.meow.com/vnc.html`, and we already host `novnc` at `localhost:1234`

1. Add `novnc.meow.com` to your domain (`meow.com` here) by for example going to Cloudflare or else
2. Edit `nginx.conf` and restart nginx service `sudo nginx -s reload`
    ```nginx
    server {
        server_name novnc.meow.com;

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_pass http://localhost:1234/vnc.html; # or http://localhost:1234
        }

        listen 80;
    }
    ```
    Some notes:
    * `Upgrade` and `Connection` are for nginx to support WebSocket
    * Use `http://localhost:1234`*`/vnc.html`* here to skip selecting `vnc.html` while accessing `https://novnc.meow.com`
3. Run `sudo certbot certonly --nginx -d novnc.meow.com` to add a new certification
4. Add the following lines to `nginx.conf` and restart nginx service `sudo nginx -s reload`
    ```nginx
    server {
        server_name novnc.meow.com;

        ...

        listen 443 ssl; # managed by Certbot
        ssl_certificate /etc/letsencrypt/live/novnc.meow.com/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/novnc.meow.com/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    }
    ```
5. Open `novnc.meow.com` and enjoy your day :)
