### ISSUE TITLE
"404 File not found" on Demo page

### ISSUE THREAD

**Issue by z3ntu** [kanaka/noVNC#515]
On [this](https://kanaka.github.io/noVNC/demo1.html) page (demo page) the page tries to get [this](https://kanaka.github.io/noVNC/noVNC/include/vnc.js) JS file which doesn't exist. Using Chrome 46.0.2478.0 dev (64-bit) on Ubuntu 15.04.

**Comment by samhed** [comment]
Duplicate of #278

**Comment by krosoftware** [comment]
Hello
Demo on site https://novnc.com/noVNC/vnc.html does not work. Is there other demo, please?

**Comment by samhed** [comment]
I answered on your other issue #1164
