### ISSUE TITLE
Unsupported auth scheme:13

### ISSUE THREAD

**Issue by realali** [kanaka/noVNC#519]
When I connect windows XP VNC server，the error is Unsupport auth scheme :13. Why?
I use VNC Viewer connect windows XP VNC server succeed.
I use noVnc connect centos 6.5 succeed.
I use middle server for websockify.

**Comment by realali** [comment]
I found there need VNC server's signature
how can I remove this signature for xp vnc server?

**Comment by samhed** [comment]
> how can I remove this signature for xp vnc server?

That question does not belong here, noVNC is a client.

**Comment by liupeng2015** [comment]
I have the same problem with you. Have you solved it?  What should I do?  Thank you !

**Comment by samhed** [comment]
The "Unsupported auth scheme"-error means that your VNC server wants to authenticate using a method that isn't supported by the noVNC client.
