### ISSUE TITLE
Wrong vertical size when using x11vnc with -ncache

### ISSUE THREAD

**Issue by derbroti** [kanaka/noVNC#525]
just an observation I just made (apologies if this is a duplicate):

When I use x11vnc with its "client-side pixel caching" (e.g. -ncache 10), the noVNC view is wrongly enlarged vertically by the buffersize.

and x11vnc does indeed just resize its framebuffer by the size of the buffer + a little more (the screen was 800x600):

    26/08/2015 17:18:05 rfbNewFramebuffer(0x1a5da70, 0x0, 800, 7200, 8, 1, 4)

Is there another size information that x11vnc is not providing or that noVNC is not parsing?

I am using master of https://github.com/LibVNC/x11vnc and libvncserver

**Comment by DirectXMan12** [comment]
Perhaps I'm missing something here, but it seems like noVNC is behaving exactly as expected (x11vnc is saying "your screen height should be 7200" and noVNC is dutifully setting the screen height to that).  Are you requesting that we automatically hide the "cache" content?  From what I can see, x11vnc basically tells the VNC clients "your screen is actually n+1 * normal height", so noVNC will show that.  If x11vnc transmits the size that it wants us to use as a special message somewhere, we could perhaps hide the extra content.

**Comment by derbroti** [comment]
I'm sorry - it was late... and I didn't read the manual. You are right noVNC is behaving perfectly fine and as far as I see x11vnc currently is not sending anything that one could use to determine the real fb size...

The only thing currently possible would be to implement a vertical cropping.

**Comment by DirectXMan12** [comment]
If you're up to it, feel free to submit a PR.

**Comment by kanaka** [comment]
Here is the description of the feature: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching Unforunately, it's not an pseudo-encoding (yet), so the client needs to guess based on the abnormally tall aspect ratio.

**Comment by DirectXMan12** [comment]
They *really* should have added a pseudo-encoding for that.  There's not a particularly good way to guess, unfortunately.

**Comment by inducer** [comment]
While the encoding end of this would be nice, could a stopgap for cropping be implemented?
