### ISSUE TITLE
UltraVNC 1.0.9.6.1 Support?

### ISSUE THREAD

**Issue by baligavinod** [kanaka/noVNC#528]
Hello,

I have been trying to get noVNC (along with websockfy) to work with an older version of UltraVNC (1.0.9.6.1). Using this version is a requirement for me. However, I am unable make noVNC work with this UltraVNC version. It seems like the VNC handshake itself is failing (refer to browser logs at end of the post)

However, with UltraVNC 1.2.0.6 everything works smooth as silk. So I just wanted to ask if older versions of Ultra VNC (and 1.0.9.6.1 in particular) are supported by noVNC/websockify?

Thanks!
Vinod

**Logs:**
```
Msg: noVNC ready: native WebSockets, canvas rendering
util.js:214 << RFB.constructor
util.js:214 >> Keyboard.allKeysUp
util.js:214 << Keyboard.allKeysUp
util.js:218 
util.js:214 >> RFB.connect
util.js:216 connecting to ws://localhost:27016/websockify
util.js:216 Detected binaryType support in WebSockets
util.js:214 << RFB.connect
util.js:214 >> WebSock.onopen
util.js:216 Server choose sub-protocol: binary
util.js:218  Msg: Starting VNC handshake
util.js:214 << WebSock.onopen
util.js:214 >> WebSock.onclose
util.js:218 WebSocket on-close event
util.js:214 >> Keyboard.allKeysUp
util.js:214 << Keyboard.allKeysUp
util.js:220  Msg: Failed to connect to server (code: 1000)
```

**Comment by DirectXMan12** [comment]
Older versions *should* be supported, although we don't really test against them regularly.  Did you see any errors in you error log?  Could you turn on the debug level and see if you get any more information?  If you are willing, a recording might be helpful in debugging this issue -- you can use the `--record` option on websockify, and then email it to me or post it somewhere.

**Comment by baligavinod** [comment]
Hello, thank you for your response. I couldn't quite get the record option working. However, I have got the websockify verbose output which is as below

Thanks!
Vinod

```
WebSocket settings:
    - proxying from localhost:27016 to 172.17
    - Running in unencrypted HTTP (ws://) mod
/websockify
 ::1: WebSocket connection
 ::1: Version 13, subprotocol: binary
 ::1: target connection error
 ::1: WebSocket client disconnected: 1000 []
```

**Comment by kanaka** [comment]
@baligavinod that error looks like websockify wasn't even able to make a socket connection to your VNC server at 172.17.21.69:8900 (i.e. not a handshake issue). The server doesn't appear to be listening on that port. Perhaps the older version is only listening on 127.0.0.1:8900 by default? Or perhaps it's not actually configured to listen on port 8900 (that's a bit unusual port for a VNC server).

**Comment by baligavinod** [comment]
Sorry my bad. Port was changed to 8900 by me during experiments and apparently it was blocked by the Windows firewall. I switched back to default 5900 port and I am able to connect to the machine (UltraVNC 1.0.9.6.1) without any trouble. noVNC works fine as well.

However, when I use a custom implementation of UltraVNC 1.0.9.6.1, I get the below error:

**noVNC Log on Google Chrome**
```
>> RFB.connect
util.js:216 connecting to ws://localhost:27016/websockify
util.js:216 Detected binaryType support in WebSockets
util.js:214 << RFB.connect
util.js:214 >> WebSock.onopen
util.js:216 Server choose sub-protocol: binary
util.js:218  Msg: Starting VNC handshake
util.js:214 << WebSock.onopen
util.js:216 Server ProtocolVersion: 003.010
rfb.js:635 CUSTOM INFO:003.010
util.js:214 >> Keyboard.allKeysUp
util.js:214 << Keyboard.allKeysUp
util.js:216 Closing WebSocket connection
util.js:220  Msg: Invalid server version 003.010Util.Error @ util.js:220
util.js:214 >> WebSock.onclose
util.js:218 WebSocket on-close event
```
**websockify log:**

```
   - proxying from localhost:27016 to 172.17.21.69:5900
   - Running in unencrypted HTTP (ws://) mode
/websockify
 ::1: WebSocket connection
 ::1: Version 13, subprotocol: binary
 ::1: connected to target
 ::1: WebSocket client disconnected: 1000 []
 ::1: target disconnected
```

So I went ahead and changed *noVNC\include\rfb.js* partially as below:

```
            switch (sversion) {
                case "000.000":  // UltraVNC repeater
                    is_repeater = 1;
                    break;
                case "003.010":  // Modified for custom UltraVNC 1.0.9.6.1
                case "003.003":
                case "003.006":  // UltraVNC
                case "003.889":  // Apple Remote Desktop
                    this._rfb_version = 3.3;
                    break;
```
After the change, although it seems to successfully establish the connection, it disconnects abruptly with the below log:

```
>> RFB.connect
util.js:216 connecting to ws://localhost:27016/websockify
util.js:216 Detected binaryType support in WebSockets
util.js:214 << RFB.connect
util.js:214 >> WebSock.onopen
util.js:216 Server choose sub-protocol: binary
util.js:218  Msg: Starting VNC handshake
util.js:214 << WebSock.onopen
util.js:216 Server ProtocolVersion: 003.010
rfb.js:635 CUSTOM INFO:003.010
util.js:218  Msg: Sent ProtocolVersion: 003.003
util.js:218  Msg: Authenticating using scheme: 2
util.js:218 
2util.js:218  Msg: Authentication OK
util.js:216 Screen: 1680x1050, bpp: 32, depth: 32, big_endian: 0, true_color: 1, red_max: 255, green_max: 255, blue_max: 255, red_shift: 16, green_shift: 8, blue_shift: 0
util.js:214 Setting viewport to full display region
util.js:218  Msg: Connected (unencrypted) to: medpc ( 172.17.21.69 )
util.js:216 First FBU latency: 928
util.js:214 >> Keyboard.allKeysUp
util.js:214 << Keyboard.allKeysUp
util.js:216 Closing WebSocket connection
util.js:220  Msg: Disconnected: unsupported encoding -232
```

```
WebSocket settings:
    - proxying from localhost:27016 to 172.17.21.69:5900
    - Running in unencrypted HTTP (ws://) mode
/websockify
 ::1: WebSocket connection
 ::1: Version 13, subprotocol: binary
 ::1: connected to target
 ::1: WebSocket client disconnected: 1000 []
 ::1: Client closed, cleaning up target
 ::1: Client closed, cleaning up target
 ::1: Client closed, cleaning up target
 ::1: Client closed, cleaning up target
 ::1: Client closed, cleaning up target
```

What could be the issue in this case?

**Comment by kanaka** [comment]
The server sent noVNC an unrecognized encoding -232. Accodring to https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#serverinit that's the pointer position pseudo-encoding. I'm not actually familiar with that pseudo-encoding and I don't see any other information about it on that page. There might be a way to prevent UltraVNC from sending that pseudo-encoding. Or you could implement it if you can find enough information about it (although if it involves actually moving the client's mouse cursor, I doubt the browser will allow that).

Also, it's curious that the server is even sending this. The server and client are supposed to negotiate supported pseudo-encodings during the initial handshake so that this doesn't happen. Perhaps a change you made has somehow broken that negotiation.

**Comment by kanaka** [comment]
I'm closing since this appears to be an issue on the server side. noVNC is responding correctly. VNC messages don't have a fixed framing definition, so unrecognized messages have to result in the connection being shutdown because the receiver has no idea how to determine how long the message is in order to ignore it.
