### ISSUE TITLE
Multiple Sessions

### ISSUE THREAD

**Issue by umardraz** [kanaka/noVNC#529]
Hello,

How I can sue this app for multiple vnc session at a time? I have created my own web application for libvirt. Now I want multiple users can access their vm's console access using this.

http://myapp.com/vnc?host=host1&port=5900
http://myapp.com/vnc?host=host2&port=5902
http://myapp.com/vnc?host=host3&port=5904
http://myapp.com/vnc?host=host4&port=5905

Is this possible I use this noVNC with my app?

Br.

Umar

**Comment by DirectXMan12** [comment]
You'll probably want to have multiple different tokens specifying host-port pairs when you run websockify.  This can be either done using a token file (using the file-based token plugin), or using a custom plugin.  Unless your target supports direct websocket connections (which newer versions of qemu do), in which case the links posted above should work.
