### ISSUE TITLE
handler exception: [Errno 1] _ssl.c:1429: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca handler exception: [Errno 1] _ssl.c:1429: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca

### ISSUE THREAD

**Issue by masoomalam** [kanaka/noVNC#530]
Server disconnected (code: 1006)

If I connect with or without https, I get this exception. 

Please help.

**Comment by DirectXMan12** [comment]
Please indicate which OS (including version), browser (including version), version of Python, and version of websockify and noVNC you are using, as well as what you are running when the error occurs (how are you launching websockify).

**Comment by jeffforbes** [comment]
This looks like the error thrown when a ssl cert with an unknown signing CA is detected. This could be either a self-signed cert or a DOD site SSL and you have not loaded the DOD CAs into your browser. 
If you are using a self-signed cert you need to make a signing CA that can then be loaded into your browser.

**Comment by DirectXMan12** [comment]
closing due to no response
