### ISSUE TITLE
vnc_auto.html - Token not being passed in the path

### ISSUE THREAD

**Issue by miguelxpn** [kanaka/noVNC#536]
It seems that the token is not being passed to the path variable which is causing token connections to fail. Is this a bug or is there something I'm missing? 

I added a line concatenating the token variable into the path variable to test and that seemed to fix the issue, if this is indeed a bug I'd be happy to create a pull request to fix it.

**Comment by DirectXMan12** [comment]
I've actually wondered about this before, but never got around to fixing it (the existing solution was just to use `?path=/websockify?token=blah`

@kanaka : Any particular reason for this?

**Comment by kanaka** [comment]
@miguelxpn @DirectXMan12 the querying of token from the query string appears to have been added in https://github.com/kanaka/noVNC/commit/4c75210a4d8946cfc35db1d18150cfab72cba61e. Doesn't look like it was ever used directly on the page (perhaps it was only ever used by a parent page in a iframe context). I have no major objection to adding it, however, we should add it to both vnc_auto.html and vnc.html/ui.js if we are going to add it. Also the right thing needs to happen if both path and token are specified (and I'm not sure what the "right" thing is here).

**Comment by miguelxpn** [comment]
@kanaka @DirectXMan12 I made another commit in the PR #537 adding it to vnc.html/ui.js as well. If both a token and a path with a token are specified I'm ignoring the new token to make sure nothing breaks for people using it the old way.

**Comment by Jigarsolanki** [comment]
I like the path route. Because that way we could consume the proxy with a client that is running on a different domain. Are there any big concern with that?
