### ISSUE TITLE
Reconnect after restart

### ISSUE THREAD

**Issue by ayonghosh** [kanaka/noVNC#539]
Is it possible to configure VNC to reconnect automatically after the remote machine has been restarted?

**Comment by kanaka** [comment]
If you are referring to getting noVNC to reconnect automatically, you'll need to extend your noVNC page (vnc_auto.html, vnc.html or your own custom) to reconnect. noVNC is designed to be integrated into larger system and making policy decisions like that is not really within its purview. Part of the reason for this is that often the instance of websockify or it's target configuration is basically set up to allow a single connection and then prevent subsequent connections to that same token/target unless the authentication/authorization mechanism of the whole system (outside noVNC itself) sets it up again.

I wouldn't be that hard though to add a handler that reconnects on disconnect, however, you'll want some sort of backoff or other mechanism to prevent continually reconnection when there really is nothing to connect to (or some other persistent error has occurred).

**Comment by ayonghosh** [comment]
Thanks, Joel.
