### ISSUE TITLE
Why is this not on npm?

### ISSUE THREAD

**Issue by rogeriochaves** [kanaka/noVNC#541]
Could you upload it to the npm registry?

**Comment by DirectXMan12** [comment]
I'd like to get #496 (or something similar) merged first.  Once that's done, it will fit with the general model of npm more.

**Comment by juanjoDiaz** [comment]
How's this going?? Any plan of getting the browserify stuff in and publish noVNC to npm??

**Comment by samhed** [comment]
Closing in favor of #675
