### ISSUE TITLE
How to integrate noVNC into existing Web server

### ISSUE THREAD

**Issue by deitch** [kanaka/noVNC#546]
I am struggling with the multitude of options as to how to integrate noVNC into an existing Web app.

I have a series of Web pages, including those requiring authentication, all served by an existing server (Apache or nginx, whichever). I generate links that:

1. start vncserver
2. open a browser page for noVNC
3. send the browser page to the new vncserver instance

When the page is closed, I shut down the vncserver

In other words, these are individual vncserver instances per session, each with its own short-lived Xvnc.

How do I integrate it in? I can take the vnc.html, modify to suit my needs, and then serve it up via Apache/nginx. But how do I integrate websockify with the existing Web server to serve it up? `ProxyPass` and a standalone websockify? Something else?

UPDATE:

I took te above approach, configured `/websockify` as `ProxyPass` (after enabling `proxy_wstunnel`) through to the standalone websockify, but I keep getting `405` errors. I put debugging messages in the websockify to dump the headers, and I get the following:

````
Host: localhost:3001
Pragma: no-cache
Cache-Control: no-cache
Origin: http://159.203.242.38
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,he;q=0.6
Sec-WebSocket-Key: wthL5A60MHfXj/+jkBBS8g==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Protocol: binary
X-Forwarded-For: 64.134.96.241
X-Forwarded-Host: 159.203.242.38
X-Forwarded-Server: 172.17.0.43
Connection: Keep-Alive
````

Notice that the `Upgrade: websocket` and `Connection: upgrade` headers have been stripped out by Apache's proxy.

How do I get this to work?

**Comment by deitch** [comment]
Update. Apache has to be set to forward **only** `ws://` or `wss://`. If `http:` or `https:` is set up too, then it gets all messed up.

Still working to get it to work, but closer.

**Comment by DirectXMan12** [comment]
I would recommend serving the actual HTML, JS, and CSS with Apache or Nginx, and then doing a ProxyPass like you suggested, and running websockify in non-hosting mode.

**Comment by deitch** [comment]
Yup, that is what I came down to in the end. It does appear to be working. I also started websockify at startup using tokens. My next challenge is getting a link click to:

* start up inc
* record the display and port
* create a token file
* launch the html page with the token embedded

Some sort of script or similar.

A simple how-to page for "here is how you run novnc from your own browser" would be great. :-)

**Comment by DirectXMan12** [comment]
P.S. If you already have infrastructure (e.g. a database of some sort) for storing the tokens, you could also use a token plugin instead of having to deal with having a separate thing write the token file.

**Comment by deitch** [comment]
It isn't too bad to write the token file, then remove it, since websockify supports the directory format (any file in a directory). My bigger issue actually is starting the vnc process. I want a separate vnc for each user/service.

To clarify: we have a Java Swing app that is used to manage configurations across several instances of a service. We are moving it all to the Web. Eventually, we will replace the Java app with one that is native Web. But for now, some way to run the Java app through a browser is perfect, and novnc really fits the bill.

So my plan was to have each user log in, pick one of the services from a list, and then click a link to launch the Java app in novnc in the browser. The Java app receives the particular path to the service instance as a command-line parameter.

So, I need to:

* set up the token in a file
* change xstartup  to match the particular path for this instance of the service
* create vnc for this particular user
* generate the Web page (or at least modify it for the token)

I could have xstartup read from the environment or somewhere, so that is easier, but I still need to start vnc for this user. I don't want 2 users using the same vnc server!
