### ISSUE TITLE
unsupported encoding 65535

### ISSUE THREAD

**Issue by qza** [kanaka/noVNC#550]
Greetings!

Currently testing VM lite VNC server with noVnc client.

This setup is working really well in 99% of the cases.

However, on some handsets, unsupported encoding 65535 is reported as an error as soon as connection is established.

Question:

Do you have any idea or guidance what could be the cause of unsupported encoding 65535 and what can be done to solve it?

Any help is appreciated!

Many thanks.

Qza

**Comment by DirectXMan12** [comment]
65535 is `0xff 0xff`, which make me think there's some sort of misread or misinterpretation of the protocol going on.  Are you proxying through websockify?  If so, can you capture a recording of the session using websockify's `--record` option?  I'm curious to see if the same session replayed multiple times (e.g. using `tests/vnc_playback.html) always hits that bug, or if it's more on noVNC's side.
