### ISSUE TITLE
Connect do a VCN server with an empty password

### ISSUE THREAD

**Issue by fzumstein** [kanaka/noVNC#551]
Hi, could you give me some hints about what changes are necessary so that `vnc_auto.html` can connect to a VNC server that has an empty password set? Currently it will only let me connect if there's an non-empty password set on the VNC server. thanks!

**Comment by DirectXMan12** [comment]
The line in you would need to change is this line: https://github.com/kanaka/noVNC/blob/master/include/rfb.js#L737

I'm curious to know which client is using VNC auth and then expecting an empty password... it should probably just be using "no auth" instead.

**Comment by fzumstein** [comment]
Thanks a lot for the hint! [This](https://hub.docker.com/r/brokertron/open-gateway/~/dockerfile/) is what I am targeting. But you're right, it might be better to change things on the VNC server side...

**Comment by DirectXMan12** [comment]
From the linked Dockerfile:
>  ```
> # set an empty VNC password
> RUN echo | vncpasswd -f > /etc/vnc-passwd
>  ```

... That line should probably be changed to just disable the VNC password auth instead.
