### ISSUE TITLE
websocketproxy

### ISSUE THREAD

**Issue by yanzixiang** [kanaka/noVNC#552]
https://github.com/kanaka/websockify does not has an .net implementation,
can i use https://github.com/lifeemotions/websocketproxy on the vnc server,
and use noVNC to connect to it ?

what is the diffirence between websockify and websocketproxy ?

**Comment by DirectXMan12** [comment]
You should be able to use any WebSocket proxy tool with noVNC.  The only restriction is that the proxy must support binary WebSocket connections.  The proxy should respond to WS and WSS connections on the on the path specified by the "path" setting in noVNC (by default, `/websockify`)

**Comment by yanzixiang** [comment]
I think i missunderstood the porpurse of https://github.com/lifeemotions/websocketproxy,
I should use https://github.com/rickparrish/FleckProxy,
I have succeed in getting an websocket endpoint,
but when i tried to use noVNC to connect to the VNC server(REALVNC SERVER),
I get an error(1006),
i think maybe i should ask,
which VNC server is tested on WINDOWS using noVNC ?
https://github.com/kanaka/noVNC/issues/553
