### ISSUE TITLE
NoVNC error 1006

### ISSUE THREAD

**Issue by nttm1010** [kanaka/noVNC#554]
Hi.
I am trying to connect to my windows xp vnc server via web based vnc client noVNC but it doesn't working (error code:1006) at http://kanaka.github.io/noVNC/noVNC/vnc.html. With VncViewer client on Ubuntu 14.4 is fine.
Os: Windows xp
Vnc remote port: 9999
Vnc server version: tightvnc
Browser: iceweasel (based on firefox)
![tp-2](https://cloud.githubusercontent.com/assets/11404827/11321833/11ee3618-90c6-11e5-8664-5a9e5fd7449d.jpg)
![tp-1](https://cloud.githubusercontent.com/assets/11404827/11321834/1afd122e-90c6-11e5-82d2-6f1bfb47b4e5.jpg)

**Comment by DirectXMan12** [comment]
Looks like you're having trouble connecting to websockify.  Which version of websockify are you running?  Do you have the requisite ports open on your firewall?  As I understand it, your setup has websockify forwarding websocket connections on 17523 to VNC on 9999?
