### ISSUE TITLE
How to connect integrated noVNC to websockify

### ISSUE THREAD

**Issue by Ziris85** [kanaka/noVNC#562]
Good Evening,

This is mostly a question about how to do something I'm trying to do rather than an issue, so if this not the right place to put this, I can request this elsewhere.

So I have this working to a degree, but I think I can do better with it however. Currently, I have a user go to a PHP script I've written that does various authentication stuffs, and among other things, it retrieves the token and VNC password. Once it's done doing its thing, it redirects the user to an nginx-proxied URL, appending the token and password to the URI. This works - the window pops up and the remote VNC console is displayed. 

What I would _like_ to do is pull the noVNC stuff in to the aforementioned script. For one, running the built-in webserver in websockify seems redundant when I have a perfectly-fine nginx server capable of handling that. For another, since I have the token and password in the script, it'd be nice to pass that directly to websockify without having to append it to a URL bar. This I have not been able to get working, and I believe my issues lie with lacking an understanding of what the `host`, `port`, and `path` variables are used for. When I run websockify in the foreground in this setup, I don't even see an attempt at a connection, so I most likely am not using these properly. Correct me if I'm wrong, but the `host` and `port` variables should be directed to where websockify is running, correct? So if I have it running on 127.0.0.1:1234, I would set those to match that, correct? And the `path` variable I've honestly been confused about all along, though in the above working scenario, the URI is just set to `path=`, using the default in the script of `websockify`. What function does the path variable play?

Might I be able to get some assistance clarifying what those should be pointing towards? And in relation to all that above stuff, is it actually possible to pass the token and pass directly to websockify by, say, making the following adjustment:

```
            token = WebUtil.getQueryVar('token', null);

TO

            token = "<?php echo $tok;?>";
```
Or will none of this work as I am imagining it will?

Any help I can get with this would be greatly appreciated. Thanks in advance.

**Comment by Ziris85** [comment]
Nevermind on this. I've learned a little more about how the process works and I've gotten set up now.

**Comment by yunets** [comment]
How to connect integrated noVNC to websockify？can you show me the some code？I am use react to integrated noVNC ，Any help I can get with this would be greatly appreciated. Thanks in advance.
