### ISSUE TITLE
ctrl-w on Chrome closes browser window

### ISSUE THREAD

**Issue by kosmasgiannis** [kanaka/noVNC#573]
Hi there, 

I am using noVNC to access an X11 display with an xterm application.
When I use the latest Chrome (47.0.2526) on Ubuntu 12.04 and press ctrl-w the window closes. 
In Firefox it works fine.

Is this a known issue? 

Please let me know if/how I can help to further debug this issue. 

Giannis

**Comment by patrakov** [comment]
It is a known issue. Unfortunately, Chrome developers are not going to allow applications to change the default reaction to Ctrl+W. See https://bugs.chromium.org/p/chromium/issues/detail?id=33056 and https://bugs.chromium.org/p/chromium/issues/detail?id=119881 . So, I think, the only realistic way forward is to present such troublesome key combinations as tool buttons, like noVNC already does with ctrl-alt-del.

**Comment by samhed** [comment]
Correct. I think what @patrakov suggested sounds like a good feature. Perhaps the ctrl-alt-del button can be expanded in the same way the Ctrl, Alt, Tab, Esc buttons are presented on touch devices with low resolution?

See #284 for screenshots of what I talk about.

**Comment by samhed** [comment]
But yeah, since this problem only seems to exist on Chrome, such a solution should be limited and only shown when needed. We have some special features for specific browsers, it all depends on if you can detect this or not. A simple useragent check is not good enough in my opinion.

**Comment by patrakov** [comment]
The problem exists not only on Chrome. There are os-level keyboard shortcuts such as alt-f2 (which brings up the run dialog in GNOME or MATE) that can't be used from withing a browser. IMHO showing Alt and Ctrl buttons unconditionally, in a way similar to what #284 proposes, would be the neatest possible way to solve this.

**Comment by samhed** [comment]
@patrakov Forgot to mention it here when the change was made, but buttons such as Alt and Ctrl are now displayed unconditionally.
