### ISSUE TITLE
Check noVnc status

### ISSUE THREAD

**Issue by sbellver** [kanaka/noVNC#574]
We can't login to noVnc from time to time, it's not clear why.

Is any way to check novnc status? We currently check ours servers with nagios, but we cannot find notching about noVnc status

Is any way to enable debug logs?

**Comment by noah8713** [comment]
@sbellver  did you set debug level following the wiki steps for logging @https://github.com/kanaka/noVNC/wiki/Troubleshooting

**Comment by samhed** [comment]
closing due to no response
