### ISSUE TITLE
when is the next tag?

### ISSUE THREAD

**Issue by prometheanfire** [kanaka/noVNC#575]
Seems to have been a bunch of development since the last release, wondering when the next tag is.

**Comment by DirectXMan12** [comment]
Most likely soon.  There are a couple of open issues that I'd like to get resolved, but I haven't had a lot of time to work on noVNC recently.  There was a pretty major overhaul between the upcoming tag and the last one, so I wanted to give some time for any potential issues to trickle in before release.

**Comment by prometheanfire** [comment]
If it helps I'm using it for nova now (master ask of a couple of days ago).

**Comment by DirectXMan12** [comment]
Thanks.  Let me know if you have any issues.  It looks like most of the problems were worked out, so I intend to tag something new soon.

**Comment by prometheanfire** [comment]
yep, I packaged it :D
