### ISSUE TITLE
WebSocket connection to 'ws://ip:5900/websockify' failed: Error during WebSocket handshake: Invalid status line

### ISSUE THREAD

**Issue by ermarkar** [kanaka/noVNC#576]
Whenever I tried to connect it is showing server disconnect (code :1006) and in console showing

WebSocket connection to 'ws://ip:5900/websockify' failed: Error during WebSocket handshake: Invalid status line.

It also ask for token? what is token here?

**Comment by kanaka** [comment]
Port 5900 is usually where the raw VNC server is running. Generally you run a websockify bridge/proxy and connect to that which in turn connects to the raw VNC.

**Comment by DirectXMan12** [comment]
(although some VNC servers support websockets directly)

**Comment by kanaka** [comment]
@DirectXMan12 hmm, I thought I had written that in my post, but it got missed/dropped somehow. Yes, QEMU and libvncserver (x11vnc) for example support websockets directly. However, with QEMU it's usually not running at port 590*.

**Comment by ermarkar** [comment]
I was trying it with UltraVNC. So now what I have to do to make it running?

**Comment by ermarkar** [comment]
Hi Kanaka,

I cloned project on linux server and ran launch.sh script. It returened me url. Now from my windows machine i hitted that url : 

server_ip:6080/vnc.html

On server side this is output on screen

Warning: could not find self.pem
Using local websockify at /home/techheal_dimensions/myvnc/noVNC/utils/websockify/run
Starting webserver and WebSockets proxy on port 6080
WARNING: no 'numpy' module, HyBi protocol will be slower
WebSocket server settings:
  - Listen on :6080
  - Flash security policy server
  - Web server. Web root: /home/techheal_dimensions/myvnc/noVNC
  - No SSL/TLS support (no cert file)
  - proxying from :6080 to localhost:5901

I tried telnet

my_ip 5900

it returned RFB003.008

and then after a while echoed the message on console "Connection to host lost"
and in taskbar a notification "Could not connect to my_ip"

can you please help ?

**Comment by kanaka** [comment]
If your VNC server is running at my_ip:5900, then you need to start websockify with that address as the target address rather than localhost:5901.

**Comment by ermarkar** [comment]
I have started the launch.sh using 

bash launch.sh --vnc localhost:5901

As websockify get started from launch.sh so that means I need to make changes in launch.sh ? Or still I am getting it wrong ?

**Comment by grandrew** [comment]
I have the same symptoms with x11vnc SSL connection - sometimes it works but sometimes it says "invalid status line" - will investigate

**Comment by grandrew** [comment]
The message seems to come from here:

https://chromium.googlesource.com/chromium/src/net/+/master/websockets/websocket_basic_handshake_stream.cc#545

```c
// A WebSocket server cannot be using HTTP/0.9, so if we see version
        // 0.9, it means the response was garbage.
        // Reporting "Unexpected response code: 200" in this case is not
        // helpful, so use a different error message.
        if (headers->GetHttpVersion() == HttpVersion(0, 9)) {
          set_failure_message(
              "Error during WebSocket handshake: Invalid status line");
        } else {
```

will need to instrument into encrypted messages as wire dump is unreadable
[dump.zip](https://github.com/kanaka/noVNC/files/243514/dump.zip)

**Comment by samhed** [comment]
If you are running websockify on the same server as your VNC server you can start it like this:

    <PATH_TO_WEBSOCKIFY>/run --web <PATH_TO_NOVNC> <PORT_FOR_WEBSOCKIFY> localhost:<VNC_SERVER_PORT>

could for example look like this:

    ~/websockify/run --web ~/noVNC 6080 localhost:5950

Then you surf to the address of your server and the port of websockify. You can of course also use noVNC/utils/launch.sh, but perhaps this clarifies things better.
