### ISSUE TITLE
vnc_playback.html

### ISSUE THREAD

**Issue by kc343** [kanaka/noVNC#579]
1. the documentation asks the user to create a data directory under tests and to put the sample recording files there. However, it is actually loading from the /include. 
2. When I try to run the playback, I receive the error: Invalid server version:  IDAwMy4

![image](https://cloud.githubusercontent.com/assets/17088925/12955399/d7217bf2-cff0-11e5-9f6a-28dc1324d3de.png)

**Comment by DirectXMan12** [comment]
> the documentation asks the user to create a data directory under tests and to put the sample recording files there. However, it is actually loading from the /include. 

Thanks, that should be corrected.

> When I try to run the playback, I receive the error: Invalid server version: IDAwMy4

Where did you get the recorded file?  That looks like something recorded in the old base64 format.  I wrote a script which converts between them here: https://github.com/kanaka/noVNC/blob/refactor/modularized/utils/b64-to-binary.pl

**Comment by kc343** [comment]
I pulled the files from here: https://github.com/kanaka/noVNC/wiki/Performance-notes

**Comment by DirectXMan12** [comment]
Those are quite old, and probably won't entirely work without some modifications by hand (as well as conversion to the binary format).

**Comment by kc343** [comment]
The error which I am having has to do with websockets I believe. the
formatting of the recorded files is an issue that will have to be dealt
with afterwards. The websocket that I get back from the handshake is null.
Am I missing something in the setup? I tried to search for documentation on
the playback, but couldn't find any.

On Wed, Feb 10, 2016 at 1:35 PM, Solly Ross <notifications@github.com>
wrote:

> Those are quite old, and probably won't entirely work without some
> modifications by hand (as well as conversion to the binary format).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kanaka/noVNC/issues/579#issuecomment-182520119>.
>



-- 
kevinkchang2@gmail.com

**Comment by kc343** [comment]
I am curious as to why the rfb protocol is needed to playback a session recording. If so, how can I make the file communicate with my vnc server?

**Comment by DirectXMan12** [comment]
> I am curious as to why the rfb protocol is needed to playback a session recording. If so, how can I make the file communicate with my vnc server?

I'm unclear as to what you are asking here.  The "playback" file is designed to play back a session file recorded by websockify -- it takes the websocket frames that it sends and mirrors them into an array in a javascript file.

At a certain point, we switched noVNC over from working with base64-encoded WebSocket traffic to working with binary WebSocket traffic.  Older recordings were recorded as base64-encoded, while newer recordings record binary WebSocket frames.

Another problem with the older recordings is that that they assume a certain respond from noVNC.  For instance, imagine the given session which is recorded:

Server: I support security types X, Y, and Z
noVNC: use the largest I support, which is Y
Server: [proceed to send Y negotiation]
noVNC: [proceeds to receive Y negotiation]

Now, imagine a newer version of noVNC:

Server recording: I support security types X, Y, and Z
noVNC: use the largest I support, which is Z
Server recording: [proceeds to send Y negotiation]
noVNC: [proceeds to try and receive Z negotiation, gets very confused]

This the second reason why some of the older recordings will not work without a bit of hand-editing.

**Comment by cavac** [comment]
You can try the recording from Issue #571 or these ones: https://cavac.at/admin/pimenu/download/vncrecord_long.zip

BTW, if we need new recordings for the demos, i'm willing to make a few clean ones similar to the old ones (opening a few windows, typing into gedit, googling for noVNC, something like that).

**Comment by DirectXMan12** [comment]
@cavac that would be great.

**Comment by samhed** [comment]
I believe this issue should have been fixed with #677
