### ISSUE TITLE
host and remote are not synchronized

### ISSUE THREAD

**Issue by doggdor** [kanaka/noVNC#580]
Hello,

When I control the host with a remote the screen of the host remain constant. For example: I open a program that I can use wit the remote but the host doesn't show anything. Does anybody know this problem?

I use novnc and tightvnc on a host with raspbian raspbian

Daniel

**Comment by kc343** [comment]
this is because with tightvnc, you are controlling a new X desktop and not your current host. use x11vnc if you wish for the same display to be controlled.

**Comment by doggdor** [comment]
Thank you!
