### ISSUE TITLE
IE11 problem

### ISSUE THREAD

**Issue by oneru** [kanaka/noVNC#591]
There seems to be a strange issue on IE11 that I've uncovered.  In noVNC/include/webutil.js, The return statement for webUtil.injectParamIfMissing is "return elem.pathname.slice(1) + elem.search + elem.hash;"

In my use case, the path there is something like "/shell/etc..."  In IE11, the return value looks like "hell/etc...".  This results in an eventual 404 when trying to start the websocket connection, and a 1006 error presented to the user.  IE versions prior to 10 are known to leave off the leading slash.  When that slash is absent, the slice function is actually trimming the first letter of the path.  It's not clear why IE11 is misbehaving in this way, but I've reproduced it on sever machines in the last few days.

A hackish fix would be to change that return statement so it first checks for the leading slash:

if (elem.pathname.charAt(0) == "/") {
        return elem.pathname.slice(1) + elem.search + elem.hash;
    } else {
        return elem.pathname + elem.search + elem.hash;
    }

If that seems an acceptable fix I can send a pull request.
--Jonathan Bennett

**Comment by DirectXMan12** [comment]
Hi @oneru.   Is is possible the page is operating in compatibility mode?

**Comment by oneru** [comment]
@DirectXMan12 I checked for compatibility mode on a couple of the affected browsers, and it seemed to be turned off.  It's a strange case, but the workaround is so simple I think it's the way to go.  I'll open a PR shortly.
