### ISSUE TITLE
Problems connecting to quemu guests through wss

### ISSUE THREAD

**Issue by igalvez** [kanaka/noVNC#592]
Hi all,
I have a server with Qemu 1.5 and noVNC. The server has a web interface which shows several information about the server status/interfaces/vms, and which should allow the user to connect to the kvm guests through noVNC. 

I'm using lighttpd and all connections to the server should be done using ssl. The problem is that I can't make noVNC work when using https (it won't connect to wss). 

It will display the message "noVNC ready: native WebSockets, canvas rendering" for a long time and then show "Server disconnected (code: 1006)". In chrome the error message shown through the developer tools is: "WebSocket connection to 'wss://192.168.1.110:5700/websockify' failed: Error in connection establishment: net::ERR_TIMED_OUT"; Firefox just says it can't establish a connection to the server.

I have no problem when the connection is not encrypted, it connects fine with ws. Searching the internet I also saw many people having similar errors in which the cause was that the self-signed certificate should be accepted manually  (including this post https://github.com/kanaka/noVNC/issues/268). So I tried to do that, tried putting on the browser https://192.168.1.110:5700/websockify, https://192.168.1.110:5700 and other variants but that didn't help, no certificate appeared, just a message that the page is not available....

I tried everything I could think of, including compiling qemu with tls support and without it but nothing seemed to help!  

Does anyone have a clue of what I might be missing here??

Thanks!

Ingrid

**Comment by igalvez** [comment]
I also tried configuring a TLS certificate for libvirt as explained here http://wiki.libvirt.org/page/TLSCreateCACert. When trying to connect through virsh I get the following error:

```
virsh -c qemu+tls://192.168.1.110/system
error: failed to connect to the hypervisor
error: Unable to read TLS confirmation: Input/output error
```

From libvirt log I see:
```
2016-04-04 11:45:02.219+0000: 3288: warning : virNetTLSContextCheckCertificate:1145 : Certificate check failed Unable to verify TLS peer: No certificate was found.
2016-04-04 11:45:02.219+0000: 3288: error : virNetTLSContextCheckCertificate:1148 : authentication failed: Failed to verify peer's certificate
```
I'm not sure why this is happening as I followed every step described on the link mentioned above both for the CA cert creation and the server cert creation.

**Comment by DirectXMan12** [comment]
It looks like your qemu is trying to verify a peer cert (i.e. it's expecting the browser to send its own certificate).  How is your libvirt daemon configured?

**Comment by samhed** [comment]
Closing due to no response.

**Comment by nvazquez** [comment]
@igalvez I'm facing a similar issue, could you solve this issue?
