### ISSUE TITLE
AltGr not working

### ISSUE THREAD

**Issue by muskelbiber** [kanaka/noVNC#595]
Hello,

i use noVNC over the Sunstone portal from OpenNebula 4.14 to connect to QEMU machines (under iceweasel 38.6.1). I encountered the problem that the AltGr key is not working. When i connect directly via vncviewer, there is no problem with AltGr.

I found out, that commenting out line 414 in keyboard.js (cur.escape = queue[0].escape;) fixes the issue for me. Can somebody please have a closer look on this?

Regards,
Steffen

**Comment by DirectXMan12** [comment]
See also #21

**Comment by danielhb** [comment]
@muskelbiber I've sent a pull request to fix this exact issue as part of #21 

This change is available at https://github.com/danielhb/noVNC in case you want to test it to see if it fixes this issue you're having. I've just checked it with QEMU machine and I have no problems with AltGr, but these changes works only on latest stable Firefox, Chrome and Opera.
