### ISSUE TITLE
Connecting to Windows Server from browser

### ISSUE THREAD

**Issue by picko94** [kanaka/noVNC#605]
I'm trying to connect to Windows Server 2012 through a web browser using noVNC and TightVNC. I have TightVNC Service running on the server and I've tried to set up noVNC using [these](https://github.com/kanaka/websockify/wiki/Compiling-Websockify-as-Windows-Executable) instructions. I installed using Portable Python 2.7 but had same error as #108 so I changed the websocket.py with [this](https://github.com/kanaka/websockify/commit/3ee9ff7f4d5b27c77c75e246d4ac8d642049b02f) workaround.
When I do `run.exe 6080 localhost:6080` I get this:
```
WARNING: no ‘resource’ module, daemonizing is disabled
WebSocket server settings:
- Listen on :6080
- Flash security policy server
- No SSL/TLS support (no cert file)
- Proxying from :6080 to localhost:6080
```
I have the ports for TightVNC and noVNC open in Windows Firewall too.

When I try noVNC in a web browser on my **local machine** with the following details I get Server disconnected (code: 1006)
**Host:** IP address of Windows Server
**Port:** 6080
**Password:** VNC Server Password

When I try noVNC in a web browser on the **server** with the following details I get Server disconnected (code: 1006)
**Host:** localhost
**Port:** 6080
**Password:** VNC Server Password
I get this error in the Windows Command Prompt too:
```
handler exception: Can't pickle <type 'thread.lock'>: it's not found as thread.lock
WARNING: no 'resource' module, daemonizing is disabled
Usage:
    run.exe [options] [source_addr:]source_port [target_addr:target_port]
    run.exe [options] [source_addr:]source_port -- WRAP_COMMAND_LINE
run.exe: error: no such option: --multiprocessing-fork
```

Here is my Base64 Test:
onload
...
FAIL: 'window.btoa(null)' returned 'bnVsbA==', expected ''
...
Tests failed: 1
Tests passed: 27

Any help would be greatly appreciated.

**Comment by mervekaya** [comment]
Did you try with your ip adress instead of localhost ? Some windows machines can not set the localhost with ip .
