### ISSUE TITLE
quick start

### ISSUE THREAD

**Issue by interfaith** [kanaka/noVNC#609]
how does one setup a username/password ?

**Comment by samhed** [comment]
VNC viewers don't need a username and the password is the VNC password of your VNC server.

**Comment by interfaith** [comment]
xstartup seems to be the problem

On Fri, May 6, 2016 at 12:46 AM, Samuel <notifications@github.com> wrote:

> VNC viewers don't need a username and the password is the VNC password of
> your VNC server.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kanaka/noVNC/issues/609#issuecomment-217372615>
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
