### ISSUE TITLE
Unsupported tight subencoding received, filter: 183

### ISSUE THREAD

**Issue by veselins** [kanaka/noVNC#615]
Hi Kanaka,

Very nice plugin thanks a lot to you and to all contributes to project. However, I faced one problem with noVNC opened in Mozzila FireFox. For some reason after while when connection was established, exception has been thrown causes the noVNC to block and freez the screen. The VNC server behind continues to work just fine, and if I restart connection to same server instance, I can continue from point when exception were thrown.

Here is more information about the error message:
```
recv_message, caught exception: 
    name: Error
    message: Unsupported tight subencoding received, filter: 183
RFB.encodingHandlers.display_tight@http://<ip address>:6081/include/rfb.js:1976:31
RFB.encodingHandlers.TIGHT@http://<ip address>:6081/include/rfb.js:1991:37
RFB.prototype._framebufferUpdate@http://<ip address>:6081/include/rfb.js:1170:27
RFB.prototype._normal_msg@http://<ip address>:6081/include/rfb.js:1089:31
RFB.prototype._handle_message@http://<ip address>:6081/include/rfb.js:554:25
Websock.prototype._recv_message@http://<ip address>:6081/include/websock.js:400:21
 util.js:220:43
Util.init_logging/Util.Error() util.js:220
Websock.prototype._recv_message()

```

However, the interesting part, is that when I accessed remote machine via Chrome, there is no a problem. The noVNC just works fine. Maybe it is the way how Chrome handles that exception.

Any suggestion.

Best
Veselin

**Comment by samhed** [comment]
It is probably related to the [TODO](https://github.com/kanaka/noVNC/blob/master/include/rfb.js#L2014
) just above the exception.

Do you run into the same problem if you change it to:

    Util.Error("Unsupported tight subencoding received, filter: " + filterId);

**Comment by veselins** [comment]
Yes, I do still receive the problem. Now even is worst. I am disconnected:
'Disconnected: unsupported encoding 403238093'

Even I had tried to comment the whole line. And it's not working. Again I got unsupported encoding.

**Comment by samhed** [comment]
Apologies, forgot that Util.Error doesn't return false.. you have to use _fail():

    this._fail("Unsupported tight subencoding received, filter: " + filterId);

**Comment by veselins** [comment]
Thanks,
Seems that this resolve the problem or at least there is one workaround.

On FireFox with above fix, it works for none TrueColor connections. But if TrueColor is checked (from noVNC settings menu) I am receiving new type of error and connection is disconnected:
'Unsupported tight subencoding received, filter: 255'

**Comment by samhed** [comment]
Yeah well, both filter 183 and 255 are invalid. Either our code detects the filter-id incorrectly or the server you are running is behaving weird. Do you run into problems when using other VNC clients?

**Comment by veselins** [comment]
I have tried vncclient and it worked well. Also, note that the problem with filter is happens only on FireFox. On Chrome, there is no problem at all. It work smoothly.

**Comment by samhed** [comment]
Yeah well, regarding other VNC clients, we are not expecting crashes here, we are expecting perhaps the same behavior regarding TrueColor and some warnings or errors in the logs?

On Chrome, I suspect you still see the "filter: 183" error in the log, despite the fact that it works?

**Comment by veselins** [comment]
Actually, I don't receive "filter: 183" error on Chrome at all. 

btw: forgot to mentioned that I am useing x11vnc as vnc server. If that makes any differences.

**Comment by patrakov** [comment]
I have the same issue.

I have made a tcpdump of the vnc connection, and then wrote a python script do convert it into a recording suitable for tests/vnc_playback.html. Result: no errors! So it appears we are reading data from the websocket incorrectly, or managing the receive queue incorrectly.

It would be interesting to compare streams of data as captured by tcpdump and as received by Firefox. of course, that requires an environment with zero packet loss or duplication, but I have one :)

**Comment by DirectXMan12** [comment]
Could you possibly post the vnc_playback.html-compatible recording here?

**Comment by patrakov** [comment]
Yes I can, but it plays fine. Let's go to https://appear.in/alexander-patrakov to discuss this face to face

If you go there within the next 15 minutes, we can even negotiate your access to a test server that exhibits the issue.

**Comment by DirectXMan12** [comment]
Unfortunately, I don't have time to discuss face-to-face right now.  Whenever I'm debugging issues like this, I usually end up looking back through the raw byte traffic right around the time the issue occurs.  Can you compare the buffer during playback with the buffer during real-time (i.e. add a breakpoint on the `_fail` method, and then look at the sequence of bytes in the buffer and see if there's a difference?  If there is, you can either post it here or look at the RFB proto documentation to see if there's something obviously incorrect).  One alternative explanation is that we're missing one of the `retry later if we don't have enough bytes read` check.

**Comment by patrakov** [comment]
I will try that. However, this may not be practical, as the issue is usually several megabytes into the stream.

**Comment by patrakov** [comment]
OK, now I have a vnc_playback.html-compatible recording, obtained by logging directly from _decode_message. Attached. The last big frame was added manually as a difference between what's in tcpdump and what has been logged.

Please also note that there was an exception that I don't understand:

```
missed 7: function bound () {
    [native code]
}
```

[debug.5.js.zip](https://github.com/kanaka/noVNC/files/392440/debug.5.js.zip)

**Comment by patrakov** [comment]
Note that, in order to debug this, I had to remove the try-catch block:

```
                var handler = this._encHandlers[this._FBU.encoding];
                try {
                    //ret = this._encHandlers[this._FBU.encoding]();
                    ret = handler();
                } catch (ex)  {
                    console.log("missed " + this._FBU.encoding + ": " + handler);
                    ret = this._encHandlers[this._FBU.encoding]();
                }
```

Note that this block does not make much sense to me: it looks like we are calling the handler twice if there is an exception, and we also swallow errors.

**Comment by patrakov** [comment]
Dear maintainers,

This issue already contains a vnc_playback.html-compatible reproducer and a [trivial one-line fix](https://github.com/patrakov/noVNC/commit/6024677ffaf9dcd3ada1d5771bd7c41ad3003df0), but the fix has not been reviewed yet. Could you please allocate some time to it?

**Comment by DirectXMan12** [comment]
Done, thanks!
