### ISSUE TITLE
Desktop Cursor not working

### ISSUE THREAD

**Issue by kmishra9** [kanaka/noVNC#620]
Essentially I'm having this issue:
https://github.com/shadowcodex/c9.ide.desktop/issues/3

when using a plugin for Cloud9, a cloud IDE. The mouse pointer simply disappears when moved within the window.

**Comment by kmishra9** [comment]
Update, was able to make slight progress on this issue by getting the mouse to show up by checking the "Local mouse" checkbox on the screen where you connect (right after you hit "Start desktop"). However, now I can't right click, even though I can now see my mouse

<img width="960" alt="cloud9 cursor fix" src="https://cloud.githubusercontent.com/assets/10662252/15877321/072ee256-2cc8-11e6-9490-1431fa6b08d4.PNG">

**Comment by kmishra9** [comment]
Now, this works on Edge but not on Chrome. I seem to have played with all the settings and done just about everything but it refuses to register my mouse clicks in Chrome. This works in Chrome on other machines, however... Just not mine. Ideas?

**Comment by samhed** [comment]
What version of Chrome do you run into problems with? Do you see any errors in the JavaScript console?

W.r.t the right-click issue, can you enable debug-logging and see if the mouse events are sent from noVNC?

**Comment by kmishra9** [comment]
I was running Chrome 50 originally, now I've updated to 51, same issue.

Here are the console errors 
![console errors](https://cloud.githubusercontent.com/assets/10662252/15908699/d29e9ae4-2d77-11e6-99ee-d4fa6cda5f68.PNG)

**Comment by samhed** [comment]
And noVNC works in Chrome 50 works on another computer you say?

Not a single line of that console output comes from noVNC. Also, as I asked previously, could you please enable debug-logging and see if the mouse events are sent?

**Comment by kmishra9** [comment]
Mkay. It looks like there are some issues occurring: 

This occurs when I open noVNC
<img width="960" alt="opening_novnc" src="https://cloud.githubusercontent.com/assets/10662252/16096024/fdf9e2be-32fb-11e6-812f-9e78050b0113.PNG">

This starts to happen once the desktop view is open within Cloud9
<img width="960" alt="x11vnc unable to start" src="https://cloud.githubusercontent.com/assets/10662252/16096061/2728907c-32fc-11e6-979c-a74de2ac1f0f.PNG">


And this happens whenever I click (3 of the unexpected processes):
<img width="960" alt="click_event_unexpected_process" src="https://cloud.githubusercontent.com/assets/10662252/16096066/2e1e34d6-32fc-11e6-88df-c5aba700eb43.PNG">

**Comment by samhed** [comment]
Just like before, these logs are not useful since it's not noVNC writing them. I can not reproduce your problem with Chrome 50. Could you set up a VNC server of your own and connect using noVNC with the problematic machine?

**Comment by samhed** [comment]
Closing due to no response

**Comment by jw42** [comment]
Just want to say I had the same issue.   Long story short, I have a touch screen on my laptop, and Chrome was enabling touch screen events in NoVNC.  You can see the extra buttons at the top of kmishra9's screen shot of NoVNC like which mouse button, keyboard, Ctrl/Atl/Del etc.

Fix:
Open chrome://flags/#touch-events
Set Touch Events API to Disabled

Now the mouse works!

**Comment by vikkmaugli** [comment]
> Just want to say I had the same issue. Long story short, I have a touch screen on my laptop, and Chrome was enabling touch screen events in NoVNC. You can see the extra buttons at the top of kmishra9's screen shot of NoVNC like which mouse button, keyboard, Ctrl/Atl/Del etc.
> 
> Fix:
> Open chrome://flags/#touch-events
> Set Touch Events API to Disabled
> 
> Now the mouse works!

Thanks for the hint! 
While this solution didn't solve my issue at least pushed me to the right direction. I figured that I have the same issue in Firefox and Edge as well, however, does not have it in an Ubunut box. So, disabling the touch screen driver on Windows (or disable touch in BIOS) solved my issue finally.

**Comment by adityashewale** [comment]
when you doing vncpasswd use option "no"
example:
[admin@boot1 ~]$ vncpasswd
Password:
Verify:
Would you like to enter a view-only password (y/n)? n
A view-only password is not used

it works for me
