### ISSUE TITLE
WebSockify with noVNC and Nginx

### ISSUE THREAD

**Issue by vittoriop77** [kanaka/noVNC#624]
Hello,
I'm trying to connect to a guest console of VMware ESX using noVNC and websockify following this guide: https://github.com/kanaka/noVNC/wiki/Proxying-with-nginx

When I try to connect, websockify log this:
_VittoNB - - [13/Jun/2016 15:03:14] 192.168.1.98: SSL/TLS (wss://) WebSocket connection
VittoNB - - [13/Jun/2016 15:03:14] 192.168.1.98: Version hybi-13, base64: 'False'
VittoNB - - [13/Jun/2016 15:03:14] 192.168.1.98: Path: '/ticket/ae78b5719e45fe5d'
VittoNB - - [13/Jun/2016 15:03:14] connecting to: ESXHOST01:443
VittoNB - - [13/Jun/2016 15:03:40] code 400, message
Bad request syntax
('\x88\x8f\x822T\x14\x81\xda\x00u\xf0U1`\xa2Q8{\xf1W0')_

ESXHOST01 is the VMware ESX host that I used when I launch websockify
_/opt/nginx/html/noVNC/utils/launch.sh  --cert /tmp/cert.pem  --vnc ESXHOST01:443_

Do anybody know what mean code 400 ?

Thanks

Vittorio

**Comment by samhed** [comment]
Sorry for the late response, but was your VNC server really running on ESXHOST01:443? I suspect that you confused things here. The address that follows the _--vnc_ paramater is supposed to be the address and port to the VNC server.

You will be getting that error if you tell websockify to listen to itself for example.
