### ISSUE TITLE
Does a vnc server for android exist

### ISSUE THREAD

**Issue by kkoci** [kanaka/noVNC#627]

**Comment by kkoci** [comment]
Hi

Sorry for my original post, I hit enter before actually writing

I just want to know, if anyone has tried this with some vnc server to control an android device?

I just need a simple vnc server to use with noVNC from desktop, I mean control the android device from noVNC client.

Any ideas?

Thanks in advance!

**Comment by samhed** [comment]
A fast search says "VMLite VNC Server" and "droid VNC server". The latter seems to require a rooted device however. I have personally not tested any of these though.
