### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by kviktor** [kanaka/noVNC#628]
These 2 versions doesn't match:

https://github.com/kanaka/noVNC/blob/master/package.json

https://github.com/kanaka/noVNC/blob/master/docs/VERSION

**Comment by DirectXMan12** [comment]
ah, thanks, good catch.  I missed that by accident when I published the other day.  We don't actually publish to NPM yet, so hopefully it won't cause to much of a problem, but I'll fix it.
