### ISSUE TITLE
Does vnc connects to multiple vnc server in a single html page

### ISSUE THREAD

**Issue by Mutz2** [kanaka/noVNC#630]
i have a scenario where i need to show multiple device's vnc server. Is it possible and please give me idea how to implement it.

ex: in a single html page i want to see android device 1, android device 2, android device 3. how can i do that or is there a limitation for how much vnc server the novnc client can connect

**Comment by DirectXMan12** [comment]
you should be able to embed multiple copies of noVNC in a single page, using multiple copies of the `RFB` constructor on different canvases.  This would probably require writing your own UI portion.  Alternatively, you could embed multiple different iframes hosting `vnc_auto.html` in a single page as well.

**Comment by DirectXMan12** [comment]
If you have more specific questions, feel free to ask them here.  I'm closing this for now, however.
