### ISSUE TITLE
Firefox 48 STRG+W Problem

### ISSUE THREAD

**Issue by gj12** [kanaka/noVNC#636]
Hi,

before Firefox 48 I could use STRG+W and it got send to the remote VNC. Now with Firefox 48 the noVNC tab closes. The remote machine dosen't receive the STRG+W.

Im using Firefox 48 under Linux x64

**Comment by gj12** [comment]
Output from tests/input.html:

```
raw key event keydown (key: 17, char: 0, which: 17)input.html:45:13
RFB keypress down keysym: 65507 key name: 65507input.html:45:13
RFB keypress  up  keysym: 65507 key name: 65507input.html:45:13
raw key event keyup (key: 87, char: 0, which: 87)
[Browser window closes]
```

`event.preventDefault();` could fix this
https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault

**Comment by patrakov** [comment]
@gj12 in Keyboard.prototype._handleKeyDown() there is already a call to Util.stopEvent(e) which does a preventDefault(). As follows from your bug report, this is not sufficient. If you have already fixed the bug locally, please tell where exactly you inserted the extra preventDefault() call.

**Comment by gj12** [comment]
This must be a bug in firefox. Before firefox 48 CTRL+W gets captured. I tried multiple things. Nothing works. I posted a bug report in the mozilla bugzilla.

**Comment by patrakov** [comment]
It would be helpful if you posted here the URL of the issue you filed to the mozilla bugzilla

**Comment by gj12** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1302080

**Comment by gj12** [comment]
Related:
https://bugzilla.mozilla.org/show_bug.cgi?id=1291706
https://bugzilla.mozilla.org/show_bug.cgi?id=380637

**Comment by patrakov** [comment]
@gj12 I think that this should not be simply dismissed as a "firefox bug". Chrome also closes the tab on Ctrl+W. So, in my opinion, the real bug is in noVNC, namely that it doesn't provide a way to send Ctrl+something key combinations to the remote server by alternative means.

Also, note that a similar problem exists in many desktop clients, e.g. in RealVNC on linux. E.g. if you press Alt+F2 there, it will be handled by the host and not sent to the remote server. Thus, they provide the alternative UI: you can press F8, then check the "alt" checkbox, then press F2, then F8 and uncheck the box. I.e. the remote system gets Alt+F2 even though Alt+F2 was never pressed locally.

![realvnc](https://cloud.githubusercontent.com/assets/2943163/18562005/ea9451c8-7ba3-11e6-8d53-a30c0bf8c84a.png)

**Comment by samhed** [comment]
> So, in my opinion, the real bug is in noVNC, namely that it doesn't provide a way to send Ctrl+something key combinations to the remote server by alternative means.

What do you mean? vnc.html provides a way to do this.
https://github.com/kanaka/noVNC/blob/master/include/ui.js#L1197

**Comment by samhed** [comment]
My bad, I've been working on #653 for too long.. 

You are correct, currently noVNC does not provide any way to send keys such as CTRL generally. The functions I referred to in my comment above are currently only used on touch devices.

However, when we get #653 merged into master, these keys will always be available.

**Comment by gj12** [comment]
@patrakov even if you send the CTRL+W to the remote server chrome (>=crome4) and firefox(>=48) will stil close the tab.
https://bugs.chromium.org/p/chromium/issues/detail?id=33056 (WontFix)

**Comment by samhed** [comment]
@gj12 I have a hard time believing that.. The browser has no way of knowing if we send a key over the VNC protocol:

 1. Press a "toggle CTRL" button in the noVNC UI
 2. Press W on your physical keyboard

The browser would only see the W press. While the server receives CTRL+W

**Comment by gj12** [comment]
@samhed yes thats true. I meant only if you press the keys on your keyboard.

**Comment by samhed** [comment]
The fact that browsers hijack certain keys and or combinations is probably not going to change. The only way we have to work around this is to provide another way for the user to send such keys.

#653 is merged now which means that the UI for sending the keys Ctrl, Alt, Tab and Esc alongside the already existing Ctrl-Alt-Del is available on all platforms.
