### ISSUE TITLE
noVnc windows server 2008

### ISSUE THREAD

**Issue by ankitj1611** [kanaka/noVNC#637]
Hello,

I have just registered here as i have already used noVnc on vps accounts but never setup it.So sorry if i posted wrongly but i am tired searching and confused a lot.There are no guides to how to setup or maybe i dont know where to look .Please help me

I have amazon ec2 windows server 2008.I have installled tightvnc and successfully able to access it via tightvnc viewer using public ip.I want to setup noVnc on it so that i can access via browser.Please guide me in steps how to setup??

I will be very very thankfull.So sorry if i posted wrongly.I really need to setup but dont know where to reach and look

**Comment by kanaka** [comment]
@ankitj1611 https://github.com/kanaka/noVNC/wiki/Advanced-usage covers that pretty well. Basically, you need to run a websockify instance to bridge between the browser (websockets) and tightvnc because tightvnc doesn't speak websockets.
