### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by ankitj1611** [kanaka/noVNC#638]
i have been able to generate dist folder.now when i run run.exe 5901 localhost:5900 this error comes.pleas tell me how to easily setup no vnc ..I am done now.this novnc is com
![run](https://cloud.githubusercontent.com/assets/20925775/17642080/b6e59c54-6156-11e6-9245-00b88cde9646.png)
plicated

@kanaka

**Comment by samhed** [comment]
Everyone that uses noVNC and Websockify, that I know of, use Linux and not Windows. I know there has been some people trying to get websockify running on Windows, but I don't know if they succeeded. See:

https://github.com/kanaka/websockify/issues/66
https://github.com/kanaka/websockify/issues/117
https://github.com/kanaka/websockify/issues/203
https://github.com/kanaka/websockify/issues/211
https://github.com/kanaka/websockify/issues/233
https://github.com/kanaka/websockify/issues/234

etc...

**Comment by DirectXMan12** [comment]
closing as duplicate/misfiled
