### ISSUE TITLE
Invalid server version 005.000

### ISSUE THREAD

**Issue by si458** [kanaka/noVNC#639]
Im getting 'Invalid server version 005.000'
when connecting to RealVNC running on my raspberry pi 3
im using the latest RealVNC 5.3.6 version out

**Comment by kanaka** [comment]
Apparently RealVNC has bumped the VNC version to 005.000. They have shown a pattern of bumping the version at will and not publishing the protocol differences (if any). The highest version that we currently support is 004.001. You can try searching the include/rfb.js file for 004.001 and add another fall-through case for 005.001 and see if it works for you.

**Comment by si458** [comment]
i added the line into rfb.js and it didnt work at first
i kept getting 'Unsupported auth scheme: 13' but then i realised thats because im using username and password authentication not just standard password authentication

**Comment by samhed** [comment]
https://www.realvnc.com/docs/index.html links to https://tools.ietf.org/html/rfc6143 which hasn't been touched since 2011.

It's difficult for us to support a server that isn't interested in being supported by open source clients..

**Comment by DirectXMan12** [comment]
I think we'd accept a patch that added support for RealVNC, assuming they'd documented the protocol differences.  I unfortunately don't have time to work on such a think right now.

**Comment by DirectXMan12** [comment]
We should now at the very least recognize the `005.000` protocol version and send back a "hey, actually just use 003.008 instead" message (as of https://github.com/kanaka/noVNC/commit/49aa5b81c725f883b63a1fe191da6ed81b8123b3), so I'm closing this.

**Comment by jsrober** [comment]
I wish noVNC and RealVNC would work together.

**Comment by jsrober** [comment]
noVNC branch stable/v0.6 does NOT work with RealVNC

noVNC master DOES work with RealVNC

This is great! I'm happy that noVNC can work. The only problem is that the scrollbars don't show up. I'm not sure why. Any ideas?

**Comment by samhed** [comment]
As I asked in the other thread were you posted the same message, please open a new issue for the scrollbar problem.
