### ISSUE TITLE
noVNC copy paste

### ISSUE THREAD

**Issue by richiedjohnson** [kanaka/noVNC#641]
I have installed Xen on an Ubuntu Server. I am not able to "copy paste" from/to my VMs from my host system when I use noVNC launch.sh script. Is there any additional configuration which I have to do to make it work for Xen?

**Comment by DirectXMan12** [comment]
You shouldn't need any extra configuration, but your VNC server will have to support copy and paste.  You're just trying to use the noVNC clipboard area?

**Comment by richiedjohnson** [comment]
Yes. The VNC is provided by Qemu which is pre-configured with Xen

**Comment by DirectXMan12** [comment]
While I have not confirmed it, I suspect that qemu's VNC server does not support the clipboard extension, since the clipboard is OS-specific.

**Comment by richiedjohnson** [comment]
Is there any way I can fix it? or a work around?

**Comment by DirectXMan12** [comment]
If Xen's QEmu's VNC server doesn't support the clipboard extension, there's not much we can do here.  You could potentially have noVNC send the series of keystrokes directly (as if you "pasted" into the keyboard on the remote machine) instead of trying to "copy" into the remote machine's clipboard (which does not exist).

**Comment by wolneykien** [comment]
> Is there any way I can fix it? or a work around?

`xdotool type "$(xclip -o -selection clipboard)"` will **type out** the clipboard contents into the currently active X11 window (i.e. the window that is currently under the keyboard focus).

Taken from: https://forum.proxmox.com/threads/novnc-copy-paste-not-works.19773/#post-101013
