### ISSUE TITLE
Grabbing keyboard and mouse in "View Only" mode

### ISSUE THREAD

**Issue by bravegnu** [kanaka/noVNC#644]
Currently if noVNC "View Only" mode, the keyboard and mouse is still grabbed. This seems to deter functionality of the keyboard without providing any additional benefit. Can this be modified so that the keyboard and mouse is not grabbed in "View Only" mode?

**Comment by samhed** [comment]
You are right! Can you test #645 and see if that works for you?

**Comment by bravegnu** [comment]
@samhed triend this with vnc_auto.html and the viewer seems to "crash". My suspicion is that the the  _keyboard and _mouse attributes remain null and when grab() or other methods are called on them, the program crashes.

**Comment by samhed** [comment]
Can you please test with vnc.html? I assume you are getting the problem in #646 ?

**Comment by bravegnu** [comment]
Here is my understanding. The thing with vnc.html is that it does not set the view_only flag in the constructor, but rather through the setter method. But since the 'if' check you have added is in the constructor, and the default value for the view_only flag is null, the _keyboard and _mouse attributes are initialized.

The vnc_auto.html sets the flag in the constructor and hence if view_only flag is true, the _keyboard and _mouse attributes are not initialized resulting in the crash.

**Comment by samhed** [comment]
The value for view_only is taken from the setting once the RFB object is initiated, see line 729. The RFB object is initiated by the UI at connect. The default value for view_only is not null, its false, but either way "if (null)" also results in false. :P

Lastly, I'm not getting the crash with the keyboard which you are talking about.. Can you paste the output from the console?

**Comment by samhed** [comment]
Forget what I said, I wrote to you last night when I was tired. See #649
