### ISSUE TITLE
Channeling only selected windows to noVNC display

### ISSUE THREAD

**Issue by mukulagrawal78** [kanaka/noVNC#655]
I am not sure if this is an existing capability of noVNC. Otherwise I will like to start a request for feature (if technologically possible).
Instead of transporting the full desktop view to remote display can user select which graphical windows on the serer side he wants to show on the remote display? On the remote display, I would like to have an empty canvas and then only a few selected windows that are created by applications started under specific DISPLAY number that is connected to noVNC will show up on empty canvas . Is this possible?

**Comment by samhed** [comment]
This is not a question for the client, it's all up to your VNC server. A normal test setup I use for noVNC is only a terminal, i.e. not a desktop, so from noVNC's point of view, yes this is possible.

**Comment by samhed** [comment]
You could for example use:

~/tigervnc/Xvnc :50 -SecurityTypes=None
~/noVNC/utils/launch.sh --vnc localhost:5950
DISPLAY=:50 xterm

**Comment by mukulagrawal78** [comment]
Thank you for your reply, that's awesome! 
I am connecting to a headless Ubuntu Xenial terminal.Can you please recommend :-1. A vnc server that will work with noVnc and will let me achieve mentioned goal in the previous email?2. How do I start/configure the vnc server to work without installing any desktop environment. And for vnc server to just grab the windows that are specifically channeled into specified display number.

Thanks in advance.
 
 

    On Wednesday, September 7, 2016 11:50 PM, Samuel Mannehed <notifications@github.com> wrote:
 

 You could for example use:~/tigervnc/Xvnc :50 -SecurityTypes=None
~/noVNC/utils/launch.sh --vnc localhost:5950
DISPLAY=:50 xterm—

**Comment by samhed** [comment]
You should be able to do this with most of the common VNC servers. I personally use TigerVNC the most:

https://github.com/TigerVNC/tigervnc

What I wrote in my last response includes both how to start the server and how to start applications on that display.

**Comment by mukulagrawal78** [comment]
Thanks for your suggestions.I tried your suggested setup.
Things sever-client setup works, but I cannot move windows around on the HTML client nor I can rescale them.For example, If I start 3 different applications :-DISPLAY=:50 xterm &DISPLAY=:50 xeyes &DISPLAY=:50 xlogo &
All the three corresponding windows pop-up on the top-right corner of the HTML and I dont have any control to move these three windows around or rescale them or close them. Am I doing something wrong or missing something here ?
 Regards, 
Mukul ( https://sites.google.com/site/mukulagrawal ) 

    On Thursday, September 8, 2016 1:15 PM, Samuel Mannehed <notifications@github.com> wrote:
 

 You should be able to do this with most of the common VNC servers. I personally use TigerVNC the most:https://github.com/TigerVNC/tigervncWhat I wrote in my last response includes both how to start the server and how to start applications on that display. —

**Comment by samhed** [comment]
These things are handled by window managers, which is what you are missing. You could use a lightweight one like openbox or metacity:

    DISPLAY=:50 metacity && DISPLAY=:50 xterm

**Comment by mukulagrawal78** [comment]
Thx, this worrked great!Two last questions for bit more advanced setup :-
1. How do I get this to work over secure connection using https/wss instead of http/ws ?
2. Is it possible to proxy several vnc sessions through single http or https port?
[There are a couple of applications running and sending there graphics into different display channels and I like to acess them through separate and simultaneous vnc sessions without openning multiple ports.] Regards, 
Mukul ( https://sites.google.com/site/mukulagrawal ) 

    On Friday, September 30, 2016 12:22 PM, Samuel Mannehed <notifications@github.com> wrote:
 

 These things are handled by window managers, which is what you are missing. You could use a lightweight one like openbox or metacity:DISPLAY=:50 metacity && DISPLAY=:50 xterm

**Comment by samhed** [comment]
1. https://github.com/kanaka/websockify/wiki/Encrypted-Connections

2. I dont know

**Comment by mukulagrawal78** [comment]
Thanks Samuel. Regarding #2 question below, I saw an old thread (see below) requesting same feature.I cannot confirm if this feature is part of the latest release of novnc/websockify. Any help?


Multiple targets support (pending: AJAX query API) · Issue #3 · kanaka/websockify
  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
Multiple targets support (pending: AJAX query API) · Issue #3 · kanaka/webs...
 Instead of just having a single target host:port, it would be useful to be able to specify multiple host:port ta...  |   |

  |

  |

 

 Regards, Mukul ( https://sites.google.com/site/mukulagrawal ) 

    On Wednesday, October 5, 2016 4:46 PM, Samuel Mannehed <notifications@github.com> wrote:
 

    
   - https://github.com/kanaka/websockify/wiki/Encrypted-Connections
   - I dont know

**Comment by samhed** [comment]
Have you even tried the method explained by Joel in that post?

**Comment by mukulagrawal78** [comment]
I am using TigerVNC and Metacity with noVNC as described by you below.There is one issue I am running into.
If I minimize a graphics window ... it just disappers. 
I see that application is still running .... its not killed. I simply do not see the iconized window anywhere on the canvas.Is it an issue with canvas size?Any idea how to fix it?

Thanks in advance!

Regards, 
Mukul 

    On Friday, September 30, 2016 7:22 PM, Samuel Mannehed <notifications@github.com> wrote:
 

 These things are handled by window managers, which is what you are missing. You could use a lightweight one like openbox or metacity:DISPLAY=:50 metacity && DISPLAY=:50 xterm

**Comment by samhed** [comment]
sounds like you want a desktop environment

**Comment by mukulagrawal78** [comment]
Thanks for your reply Samuel.

No, I don't really want the desktop environment.This works great for me for all other aspects. 
Only problem is that windows do have iconization/minimization buttons (one with "-" sign on it).But when I click on it ... windows just disappeared.I was hoping there is some way around that?Is there no way to have iconified windows sitting somewhere on the html5 canvas?
If this is not possible then  alternatively, is it possible to disable the minimization buttons on the windows?

 Regards, 
Mukul 

    On Monday, January 2, 2017 7:57 PM, Samuel Mannehed <notifications@github.com> wrote:
 

 sounds like you want a desktop environment—

**Comment by samhed** [comment]
> Is there no way to have iconified windows sitting somewhere on the html5 canvas?

no

> is it possible to disable the minimization buttons on the windows?

probably, but this is all way out of scope of noVNC

**Comment by astrand** [comment]
> If this is not possible then  alternatively, is it possible to disable the minimization buttons on the windows?

As Samuel said, this is out of scope, but what you need is a window manager that is designed for this use case. (In ThinLinc, we are using a slightly modified version of OpenBox with a special configuration, packaged as tl-single-app, see https://www.cendio.com/resources/docs/tag/commands.html)

**Comment by mukulagrawal78** [comment]
Dear noVNC Team:
Is there any documentation that can help me setup TigerVNC and websockify inside a docker container running on Linux and then connect to it using noVNC?
 Regards, Mukul ( https://sites.google.com/site/mukulagrawal ) 

    On Monday, January 2, 2017 11:37 PM, astrand <notifications@github.com> wrote:
 

 
If this is not possible then  alternatively, is it possible to disable the minimization buttons on the windows?
As Samuel said, this is out of scope, but what you need is a window manager that is designed for this use case. (In ThinLinc, we are using a slightly modified version of OpenBox with a special configuration, packaged as tl-single-app, see https://www.cendio.com/resources/docs/tag/commands.html)—

**Comment by mukulagrawal78** [comment]
Sorry, I did not frame my question correctly.What I want to do is to run vnc server as well as websockify outside docker container. I would like applications running inside multiple different containers to be able to send their graphics to vnc server which in turn is connected to novnc HTML5 across internet.
Is this doable? Thanks in advance for any pointers.
Sent from Yahoo Mail on Android 
 
  On Tue, Jul 18, 2017 at 11:42 AM, Mukul Agrawal<mukulagrawal78@yahoo.com> wrote:   Dear noVNC Team:
Is there any documentation that can help me setup TigerVNC and websockify inside a docker container running on Linux and then connect to it using noVNC?
 Regards, Mukul ( https://sites.google.com/site/mukulagrawal ) 

    On Monday, January 2, 2017 11:37 PM, astrand <notifications@github.com> wrote:
 

 
If this is not possible then  alternatively, is it possible to disable the minimization buttons on the windows?
As Samuel said, this is out of scope, but what you need is a window manager that is designed for this use case. (In ThinLinc, we are using a slightly modified version of OpenBox with a special configuration, packaged as tl-single-app, see https://www.cendio.com/resources/docs/tag/commands.html)—

**Comment by DirectXMan12** [comment]
*maybe*.  If I'm reading you correctly, you want to have a single VNC server with multiple applications in different containers having their windows appear in that VNC server.

You could, on Linux, use one of the VNC servers that's backed by it's own X server.  Then, since X is actually a network protocol (almost?), you could have multiple applications connect to the central X server to display their windows (you probably want to do it over SSH X forwarding, for security).

Note that this would all be a bit hacky, and you'd have to "trust" each application, since once an application has access to X, it has access to everything else running in that X session.

**Comment by mukulagrawal78** [comment]
Dear noVNC community.
A follow up question on the this topic.Is it possible to do something similar for MS Windows system (2016 server)?I would like not to expose the full desktop.Can vncserver on MS Windows connect to some sort of dummy display server and then client connect to that dummy server?  Regards, Mukul ( https://sites.google.com/site/mukulagrawal ) 

    On Wednesday, September 7, 2016 11:50 PM, Samuel Mannehed <notifications@github.com> wrote:
 

 You could for example use:~/tigervnc/Xvnc :50 -SecurityTypes=None
~/noVNC/utils/launch.sh --vnc localhost:5950
DISPLAY=:50 xterm—

**Comment by DirectXMan12** [comment]
Unfortunately, I can't really help you on that one, but I suspect it's a bit harder.  The design of X is a bit unique from that perspective...
