### ISSUE TITLE
Connection from VNC server to the client

### ISSUE THREAD

**Issue by larytet** [kanaka/noVNC#656]
Hi,

I am trying to reverse the connection using UltraVNC SC_II_RC23 server. I have patched the websockify code see https://github.com/larytet/websockify/commit/0647e21552f1b67f0b8c19aff284437e04a68aa3
and added a small patch in the tfb.js https://github.com/larytet/noVNC/commit/dce94ec5847879f27051837bebbd5147f7f87f7c

I am getting "Disconnected: unsupported encoding 16" in the WEB browser. 
What am I missing? 
Thanks

P.S. I am running UltraVNC from http://www.uvnc.com/SCIII/winvnc_SCII_RC23.exe
`.\winvnc_SCII_RC23.exe -connect 192.168.0.111:5901 -noregistry`

**Comment by samhed** [comment]
That error means that noVNC received a FramebufferUpdate message which specified a type of encoding that isn't supported. You can find the list of supported encodings in noVNC here: https://github.com/kanaka/noVNC/blob/master/include/rfb.js#L39

**Comment by larytet** [comment]
Is this._encodings[] a dictionary with an integer key?

**Comment by larytet** [comment]
This is what UltraVNC has in the 
`#define rfbEncodingZRLE 16`
code https://github.com/larytet/UltraVNC-SC/blob/master/rfb/rfbproto.h#L306

Will you have any tips for me?

**Comment by larytet** [comment]
I have printed little bit more and the data looks alright : encoding 16,x=0,y=0,width=1368,height=1047  It probably means that the frame is Ok.

**Comment by samhed** [comment]
Perhaps this helps:

https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#zrle-encoding

**Comment by larytet** [comment]
I have forced UltraVNC to use HexT and it works
https://github.com/larytet/UltraVNC-SC/commit/882b3c2be385ad536d24550f69cb129f094e3fbf
