### ISSUE TITLE
Keyboard and Mouse not working on emulator

### ISSUE THREAD

**Issue by Thunder19** [kanaka/noVNC#657]
Hi,
I am trying to access android emulator from browser . Display works fine but I am not able to control it using mouse and keyboard.

**Comment by ssbtoday** [comment]
Hi Thunder19,

Can you post some more information on this issue?
What Phone?
Android Version:
What VNC Server are you using? DroidVNC, VMLite VNC Server, Server Pack Ultimate?
Is View-Mode Only turned on?
Does the issue persist when you use a normal VNC Client such as TightVNC or UltraVNC?

Do you receive any error messages in your browser console?

**Comment by Thunder19** [comment]
Hi ssbtoday,

I am using Android Version 5.0 /API Level 21 .
VNC Server used is TightVNC in CentOS 6.5 .
View Mode is turned off .  Issue persists with normal VNC Client such as Real VNC as well.
There were no error messages in browser console .

**Comment by samhed** [comment]
> Issue persists with normal VNC Client such as Real VNC as well

That would suggest that this isn't an issue with noVNC but with your server instead :)

**Comment by ssbtoday** [comment]
Yep, it's an issue with the method in which you are attempting to control
the emulator. Run the VNC server on Android directly and you won't have an
issue.
