### ISSUE TITLE
Nginx reverse proxy timeout

### ISSUE THREAD

**Issue by johnmarcou** [kanaka/noVNC#658]
Hello,

I had an issue when proxing the websocket with Nginx that the session would disconnect after 2 or 3 minutes of inactivity.

It seems to happen if Nginx doesn't see any pixels change (websocket binary stream) for 60s by default.

So if you have a clock on the screen with a minute indicator, there is a race condition which makes the chance of disconnect random. I experience after 2min, sometimes 3min, sometimes 4min...

The solution was to add the following parameter, greater than 61s, to my nginx config:
```
proxy_read_timeout 3600s;
```
It might be helpful to add this line to the [Proxying-with-nginx](https://github.com/kanaka/noVNC/wiki/Proxying-with-nginx) wiki page.

**Comment by DirectXMan12** [comment]
Thanks.  You should be able to edit the wiki yourself to add that, I think.

**Comment by samhed** [comment]
@johnmarcou I would add it to our wiki page if I knew under what part of the configuration to put it? I haven't used nginx myself.

**Comment by samhed** [comment]
I took some time to look into this and updated the wiki. Thanks for reporting

**Comment by johnmarcou** [comment]
Hi @samhed, I used this timeout parameter inside the location block, just after Connection "upgrade". You can probably add a comment like "VNC connection timeout".

"proxy_buffering off" seems to be important as well, since we don't need any cache on the vnc stream.

**Comment by samhed** [comment]
@johnmarcou okay, thanks, I changed that
