### ISSUE TITLE
Why I have no Desktop while connecting successfully？

### ISSUE THREAD

**Issue by ruiruige** [kanaka/noVNC#659]
I am testing noVNC on my PC , with no Openstack environment
I have installed vncserver and novnc:

```
apt-get install tightvncserver
 git clone https://github.com/kanaka/noVNC
 cd noVNC
 ./utils/launch.sh --vnc localhost:5901
```

then I run:
```
root@ubuntu:/home/rrg1# vncserver

New 'X' desktop is ubuntu:1

Starting applications specified in /root/.vnc/xstartup
Log file is /root/.vnc/ubuntu:1.log


root@ubuntu:/home/rrg1/noVNC# ./utils/launch.sh --vnc localhost:5901
Warning: could not find self.pem
Using installed websockify at /usr/bin/websockify
Starting webserver and WebSockets proxy on port 6080
WebSocket server settings:
  - Listen on :6080
  - Flash security policy server
  - Web server. Web root: /home/rrg1/noVNC
  - No SSL/TLS support (no cert file)
  - proxying from :6080 to localhost:5901



Navigate to this URL:

    http://ubuntu:6080/vnc.html?host=ubuntu&port=6080

Press Ctrl-C to exit

```

When I visit 127.0.0.1:6080, I enter password and can log in, howerver it was all grey and no desktop

like this:
![Uploading image.png…]()

**Comment by ruiruige** [comment]
![novnc](https://cloud.githubusercontent.com/assets/8370100/18480067/e22183e4-7a09-11e6-9f23-e8a11a78cd82.jpg)

sorry the img is here

**Comment by samhed** [comment]
what are you expecting? Are you running any applications on the VNC server display?

**Comment by ruiruige** [comment]
@samhed  I thought there would be a ubuntu desktop just like directlly operation the real machine

**Comment by ruiruige** [comment]
So now I guess if I want a desktop on the web page, I need to do some other things? Could you tell me how can I get a desktop on the website?

**Comment by samhed** [comment]
You need to run a desktop environment on the VNC display :)

**Comment by kanaka** [comment]
@ruiruige you can also use x11vnc which shares an existing desktop. However, you probably won't want to display the same desktop where you are running the browser for noVNC otherwise you will get an infinite hallway effect.

**Comment by ruiruige** [comment]
Sorry I forget to reply.
I installed XCFE4 then everything is ok
