### ISSUE TITLE
Screen Share using noVNC

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [kanaka/noVNC#676]
Notify: @kanaka 

Challenge: Need a way for Customer Support Person to help a new Ubuntu User

I have a docker container with Ubuntu Desktop and kanaka/noVNC,  [https://github.com/fcwu/docker-ubuntu-vnc-desktop]

One USER logs into the docker container using noVNC from browser - Works perfectly fine.

Question 1:
I now need another person (a Customer Support Person) to see the same screen (read only mode) as USER and guide the person appropriately in case the USER needs help to use the system.
I need help on how to configure the system so that the Customer Support Person can see the screen (duplicate the display?)

Question 2: 
If the USER tries to login from a Mobile Phone, the USER is unable to connect.
Do I need to change any settings?
Are there any minimum mobile browser versions for connectivity from Mobile Devices

**Comment by dukechem** [comment]
I also had Question 1 when trying to run another instance got error 1000/1008. If I tried again sometimes it would work. I think I got it to work like so... 
First Verify you can run two instances of vncviewer at same time (thru ssh tunnel)
If not, try tweaks something like these where you start the vncserver
vncserver -alwaysshared
If you need more help, paste in the result of this command:  ps -ef | grep -i vnc

**Comment by kanaka** [comment]
The shared setting should be the default that the client requests. As @dukechem mentioned the VNC server will also need to support shared sessions (typically this is some sort of startup configuration of the server).

For question 2 you're going to need to be more specific about what mobile device you are using. Also, do you see any connection attempts from the server/websockify?

**Comment by VinayaSathyanarayana** [comment]
@kanaka @dukechem - Thanks for your answers

1.  Can you please provide directions on where to find  the configuration settings

2. Mobile Devices _ I am looking at Android Phones (Android Lollipop and above)

**Comment by samhed** [comment]
> Can you please provide directions on where to find the configuration settings

That is not related to noVNC, you should be looking at configuring your VNC server. noVNC is a VNC client.

> Mobile Devices _ I am looking at Android Phones (Android Lollipop and above)

With regards to noVNC it should work from the get go, there are no specific settings you need to tweak in order to make it work on Android devices.

> Are there any minimum mobile browser versions for connectivity from Mobile Devices

You should mainly look at the first versions of the browsers that support the following HTML5 features:
* Canvas
* WebSockets
* TypedArrays

Generally however, the noVNC team focuses on the most recent releases of browsers.
