### ISSUE TITLE
disconnect

### ISSUE THREAD

**Issue by pcs3rd** [kanaka/noVNC#679]
I can successfully connect to my ubuntu "xenial" machine locally (on the machine itself). But I cannot connect from a client other than the host machine. On the client side it says disconnection timeout. i have the same problem on other devices to. It is also the same problem with using Lubuntu "xenial".

**Comment by pcs3rd** [comment]
edit: i am able to connect through a mobile client. (my kindle). but it will not display the desktop. the novnc background still shows.
i am having the problem with only desktop clients(except for the host )

**Comment by samhed** [comment]
Are you using the most recent code from master of noVNC? Is this a new issue that you haven't ran into before?

**Comment by samhed** [comment]
@pcs3rd do you think you have more time to look further into this and provide more information?

**Comment by samhed** [comment]
Closing due to no response.
