### ISSUE TITLE
Integration problem: where is include/ subdirectory?

### ISSUE THREAD

**Issue by fcjxxl** [kanaka/noVNC#681]
In https://github.com/kanaka/noVNC/wiki/Integration it says "All files necessary for integrating noVNC are in the include/ subdirectory of the project."
but where can I find the include/ subdirectory?

**Comment by DirectXMan12** [comment]
Ah, sorry, that wiki page hasn't been updated yet.  We recently merged a major refactor with split the `include/` directory into `core/` (the core libraries needed for embedding noVNC) and `app/` (files specific to the two noVNC "apps" included as part of the noVNC project -- `vnc.html` and `vnc_auto.html`).

**Comment by DirectXMan12** [comment]
I'm going to leave this open until I get a chance to fix the wiki page.  Thanks for the report.

**Comment by DirectXMan12** [comment]
Fixed, although we should also fix https://github.com/kanaka/noVNC/wiki/ModulesAPI.  I'll open another issue.
