### ISSUE TITLE
blank page on firefox/chrome android

### ISSUE THREAD

**Issue by yftelperu** [kanaka/noVNC#682]
Does NoVnc can work in android 4?
I can login and work on firefox/chrome on windows, linux, but when i try to access the vnc system through an android tablet/phone usign firefox (49) /chrome(53) after a sucessfull login a blank page appear
do i need to run this apps with special parameters?
I'm using this settings
./launch.sh --vnc localhost:5901
Here is the log for an android phone using above browsers
xxxxx - - [10/Oct/2016 09:47:11] xxxxxx: Plain non-SSL (ws://) WebSocket connection
xxxxx - - [10/Oct/2016 09:47:12] xxxxxx: Version hybi-13, base64: 'False'
xxxxx - - [10/Oct/2016 09:47:12] xxxxxx: Path: '/websockify'
xxxxx - - [10/Oct/2016 09:47:12] connecting to: localhost:5901

Thanks

**Comment by samhed** [comment]
It should work without any special configuration. I have recently myself used noVNC successfully on Android 4.3 in both Firefox and Chrome.

Can you connect your android device to a computer and use Chrome's or Firefox's remote debugging? If so, are you seeing any errors in the JavaScript console?

**Comment by yftelperu** [comment]
Dear Samhed
Thanks for your reply, Chrome's Remote debugging nothing appear 
Please see the picture, i've andorid 4.4.4 on samsung esm-e500m device
![novnc_android-debug](https://cloud.githubusercontent.com/assets/13142805/19245732/573ea1f0-8ee8-11e6-9652-19d21c4380b0.png)

**Comment by samhed** [comment]
Reload the page while the debugging tools are open, even if you won't get an error, you should at least see something.

**Comment by yftelperu** [comment]
Dear Samhed
Here is the new output after reloading chrome browser on andorid

![novnc_android-debugv2](https://cloud.githubusercontent.com/assets/13142805/19249676/499b1d58-8efc-11e6-83fb-5acba2e335d2.png)

**Comment by yftelperu** [comment]
Here another screen captured

![novnc_android-debugv3](https://cloud.githubusercontent.com/assets/13142805/19251137/77de7dca-8f03-11e6-9b40-2a3052acaed0.png)

Your help is appreciated
Thanks

**Comment by yftelperu** [comment]
another pictures

![novnc_android-debugv6](https://cloud.githubusercontent.com/assets/13142805/19251881/3e79360c-8f07-11e6-8552-df171df0059d.png)
![novnc_android-debugv5](https://cloud.githubusercontent.com/assets/13142805/19251883/3e8d96ba-8f07-11e6-8896-6507ddf729d7.png)

could you please tell me what is the issue with the android mobile phone?
Thanks for your help

**Comment by yftelperu** [comment]
No errors on Java Script console
![novnc_android-debugv7](https://cloud.githubusercontent.com/assets/13142805/19252037/31dded38-8f08-11e6-991b-3937b8946003.png)

Regards

**Comment by samhed** [comment]
Your second screenshot indicates that you are using Chrome Data Saver. I have a suspicion that it will work if you disable that :)

**Comment by yftelperu** [comment]
Hi Samehd
the same blank page appear on firefox, 
I've decide to use: vnc_auto.html page,is working now, but i cannot use keyboard inside that page
Regards

**Comment by samhed** [comment]
Looking at your screenshots from Chrome's developer tools, my guess is that your issue was that you didn't get all of the content from your server. For example, in your 3rd screenshot you seem to only get 2 images while there in practice are almost 30 images you should get at page load. You should start by looking at if your connection to the server works properly.

With regards to the keyboard issue, can you look over the other issues reported and see if any of the descriptions seem to fit this issue. If not, please open a new issue for that.
