### ISSUE TITLE
How to give 'file_only = true' to websockify ?

### ISSUE THREAD

**Issue by jtkoerting** [kanaka/noVNC#684]
Maybe I've overseen this, but where/how can I give/set serversettings like file_only at all?
It seems it can't be set thrue launch.sh etc. nor with the ./websockify call itself.

**Comment by DirectXMan12** [comment]
Currently, `file_only` can only be set if you use websockify as a library.  We'd accept a PR to websockify to add a command line flag as well, but you might also just consider consuming websockify as a library and baking in the requisite settings, and/or using websockify in non-web mode (e.g. only WebSocket proxy mode) and serving files using an actual webserver.
