### ISSUE TITLE
win7 cannot access to the noVNC successfully

### ISSUE THREAD

**Issue by Linda679** [kanaka/noVNC#690]
I run tigervnc as the vncserver on my rhel server, then start the novnc...  I can access to it from a remote Linux system successfully, everything looks fine. But when I try to access to the novnc page from a remote win7 client with the same browser of the Linux, the connection page hang on "Sent ProtocolVersion: 003.008" state.
I tried from other boxes,,, but no windows can secceed(have the same problem) only linux can,,, why this happen? Is there any difference between window and linux to access novnc as client? how to fix it?

The .js log as follow:
ReferenceError: assignment to undeclared variable XK_ugrave keysym.js:370:1
ReferenceError: assignment to undeclared variable XK_uacute keysym.js:371:1
ReferenceError: assignment to undeclared variable XK_ucircumflex keysym.js:372:1
ReferenceError: assignment to undeclared variable XK_udiaeresis keysym.js:373:1
ReferenceError: assignment to undeclared variable XK_yacute keysym.js:374:1
ReferenceError: assignment to undeclared variable XK_thorn keysym.js:375:1
ReferenceError: assignment to undeclared variable XK_ydiaeresis keysym.js:376:1
New state 'loaded', was 'disconnected'. Msg: noVNC ready: native WebSockets, canvas rendering util.js:110:53
Error in parsing value for 'width'.  Declaration dropped. vnc.html
Firefox can't establish a connection to the server at ws://localhost:17523/. websock.js:285:36
New state 'connect', was 'loaded'. util.js:110:53
New state 'ProtocolVersion', was 'connect'. Msg: Starting VNC handshake util.js:110:53
New state 'Security', was 'ProtocolVersion'. Msg: Sent ProtocolVersion: 003.008 util.js:110:53
Firefox can't establish a connection to the server at ws://localhost:17523/. websock.js:285:36

**Comment by samhed** [comment]
Those errors look very wierd.. I get the feeling your browser on the windows client is trying to run code that is stuck in some sort of in-between state. Did you try to clear the browser cache?

**Comment by Linda679** [comment]
Hi @samhed, 
I tried but it doesn't work, still hang on "Sent ProtocolVersion: 003.008" status with the same output...

**Comment by samhed** [comment]
And you are using the most recent code from the master branch of noVNC?

**Comment by samhed** [comment]
> New state 'loaded', was 'disconnected'.
> New state 'connect', was 'loaded'. util.js:110:53
> New state 'ProtocolVersion', was 'connect'.
> New state 'Security', was 'ProtocolVersion'.

You must have a fucked up or modified version noVNC which your browser is trying to access. These above states do not even exist anymore.

**Comment by Linda679** [comment]
Hi, @samhed 
I never do anything that fucked up the noVNC version!!! The above “New state 'loaded...'”  msg really exist in code include/rfb.js I have checked...  I don't understand why you close my issue  AND can not believe your subjective judgment is my fault(maybe there are some misunderstandings..), I feel shock !

But anyway, I have solved this problem by using a self ssl certification, I don't know why,,, and why this issue only exist on windows...

**Comment by samhed** [comment]
> I never do anything that fucked up the noVNC version!!!

I do not know where you have gotten your code from, I never said that you have done anything. But you do clearly not have the recent code from master. Can you please update your code and open a new issue if you run into problems with the real code.

> The above “New state 'loaded...'” msg really exist in code include/rfb.js I have checked... I don't understand why you close my issue AND can not believe your subjective judgment is my fault(maybe there are some misunderstandings..), I feel shock !

There is no subjective judgement here, please don't misunderstand me. It's a fact that your issue does not exist in the current code. And I can't remember any older version of the code having these problems either. You must accept that in order to help people we must be able to expect them to use the proper code.
