### ISSUE TITLE
handler exception: [Errno 57] Socket is not connected

### ISSUE THREAD

**Issue by adarwash** [kanaka/noVNC#693]
I ran launch.sh script in terminal and then i tried to connect to a Mac and i get error 1006 in the console and the terminal i get this

10.1.1.95 - - [19/Oct/2016 22:07:00] 10.1.1.95: Plain non-SSL (ws://) WebSocket connection
10.1.1.95 - - [19/Oct/2016 22:07:00] 10.1.1.95: Version hybi-13, base64: 'False'
10.1.1.95 - - [19/Oct/2016 22:07:00] 10.1.1.95: Path: '/websockify'
10.1.1.95 - - [19/Oct/2016 22:07:00] connecting to: localhost:5900
handler exception: [Errno 57] Socket is not connected

**Comment by DirectXMan12** [comment]
what does your setup look like?  Is websockify (via launch.sh) pointed at the right port for your VNC server?  What VNC server are you using?

**Comment by samhed** [comment]
Closing due to no response.

**Comment by copremesis** [comment]
can you re-open I'm seeing this issue here ☝️

**Comment by copremesis** [comment]
```handler exception: [Errno 57] Socket is not connected```

**Comment by copremesis** [comment]
![screen shot 2019-02-04 at 2 39 28 pm](https://user-images.githubusercontent.com/611899/52235802-bfcd2000-288a-11e9-91e6-2ab4feb31a6e.png)

**Comment by copremesis** [comment]
> Is websockify (via launch.sh) pointed at the right port for your VNC server? 

I have it pointing to localhost:5901 ... 

and running VNC using tigerVNC

**Comment by samhed** [comment]
@copremesis your screenshot shows "ERR_NAME_NOT_RESOLVED" which indicates that noVNC can't resolve that websocket proxy server name.
