### ISSUE TITLE
screen streching

### ISSUE THREAD

**Issue by geostant** [kanaka/noVNC#694]
Hey,

I've 1 issue that I've encountered during my integration of noVNC in my system.

It seem that there is an issue with the html screen,
I can see the vnc canvas screen well in the middle, but I can also scroll down a long way and see partial parts of the main screen repeating (I can add gif clip or some screenshots to illustrate the issue)

**Comment by DirectXMan12** [comment]
can you please indicate browser and OS version, version of noVNC (git commit, etc), VNC server.  IIRC, one of the VNC servers has a feature that does this (I can't recall which one ATM) as part of an optimization that only it understands.

**Comment by samhed** [comment]
@geostant Why is "keyboard capture" in the title? Could you explain that part as well please?

**Comment by samhed** [comment]
It sounds like you could be encountering the same behavior as @boistordu describes in #672

**Comment by boistordu** [comment]
yes it is the same. @geostant I would gladly liek that you link a gif if you can.... to compare with my problem

**Comment by samhed** [comment]
Don't use the x11vnc option "-ncache"
