### ISSUE TITLE
Resize display when the video mode changes

### ISSUE THREAD

**Issue by jeffforbes** [kanaka/noVNC#698]
We are using noVNC in an iframe to connect to a qemu-kvm virtual. When the boot process is viewed, the noVNC screen size is set to 720x400 from the boot screen. Once the VM is fully booted, the screen size is typically 1024x768, so it does not scale properly in the 720x400 display. If the page is reloaded, then the connection is regenerated to the correct size. Is there a way to detect the underlying video mode and then resize the noVND frame buffer and display so that the scaling will work correctly in an iframe?

**Comment by samhed** [comment]
The size of the frame buffer can only be set by the server. However, there is an extension that allows a client to request a new size: https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#extendeddesktopsize-pseudo-encoding

This extension is implemented in noVNC, but as far as I know, it's not implemented in QEMU's VNC server. An example of a server that implements this extension is TigerVNC.

**Comment by samhed** [comment]
Hopefully your question was answered. Closing
