### ISSUE TITLE
SysRq/Print and Break/Pause keys not working

### ISSUE THREAD

**Issue by anhammer** [kanaka/noVNC#703]
I wanted to test if a VNC server supports RFB extended key event messages, so I tried to connect with noVNC.

Everything worked fine, except the named keys. I checked with tcpdump if noVNC sends data, and it did in fact send the expected data:

```
Pause -> 0xE045 -> 0xC5
PrintScreen -> 0xE037 -> 0xb7
```

After some playing around, I got the keys to work with changing the XT scancodes in noVNC to:

```
"Pause":` 0xE046, // was 0xE045
"PrintScreen": 0x0054, // was 0xE037
```

Later I found out that the used keymap by the server seems\* to match the column "XT KBD" in [this table](https://git.gnome.org/browse/gtk-vnc/tree/src/keymaps.csv) in gtk-vnc. The 2-byte XT codes in noVNC start with 0xE0, for example 0xE047 (Home). In the gtk-vnc table, longer values start with 0x01, so 0xE047 boils down to 0x147. Keeping this in mind, the noVNC and gtk-vnc values checked by me only differ in the two named keys.

_( \* Unfortunately, I wasn't motivated enough to go through all the scancodes :) )_

So I wonder, what the standard for XT scancodes is, I googled a bit and didn't find much. Could this be a bug in noVNC or in the server implementation / gtk-vnc?

edit: So I found [this link](https://www.win.tue.nl/~aeb/linux/kbd/scancodes-1.html) which states:

> The keys PrtSc/SysRq and Pause/Break are special. The former produces scancode e0 2a e0 37 when no modifier key is pressed simultaneously, e0 37 together with Shift or Ctrl, but 54 together with (left or right) Alt. (And one gets the expected sequences upon release. But see below.) The latter produces scancode sequence e1 1d 45 e1 9d c5 when pressed (without modifier) and nothing at all upon release. However, together with (left or right) Ctrl, one gets e0 46 e0 c6, and again nothing at release. It does not repeat.

But the [RFB protocol](http://vncdotool.readthedocs.io/en/latest/rfbproto.html#qemu-extended-key-event-message) only defines the conversion of codes that have only one byte or start with 0xE0. So I assume that gtk-vnc just uses the most fitting keycodes that these keys can generate.

edit again:
After some thinking about the issue, I think that my used VNC server is at fault. Assuming that the interpretation of the irregular XT codes (just use the LSBs) is correct, the server should recognise them (which it doesn't). Also, other keycodes can be sent when hitting Print/SysRq/Pause/Break using a modifier key, so those keycodes should also be supported by the server (which they are). So I will dig a bit into the server implementation and qemu...

So from my side, the issue can be closed. But it would probably be good if somebody with more insight than myself could have a look at it before.

**Comment by DirectXMan12** [comment]
What VNC server are you using?

**Comment by anhammer** [comment]
It is a very simple implementation, that just handles keyboard and mouse, and no display. The implementation uses g_hid and the headers of [gtk-vnc](https://git.gnome.org/browse/gtk-vnc/tree/src/keymaps.csv#n150) for the mapping of vnc/rfb/usb codes.

The server was patched to map the rfb codes 0xb7 to usb code 0x46 and 0xc5 to 0x48.

Also, there is a [QEMU patch](https://lists.nongnu.org/archive/html/qemu-devel/2016-10/msg07506.html) that adds the support for these codes.

**Comment by samhed** [comment]
Thank you @anhammer for taking your time to look at this! Really appreciated!

I have been believing that PrtScn/SysRq and Pause/Break didn't work due to limitations in the browsers. But anyway, let's close this for now. Don't hesitate to reopen if you find any indications on bad behavior from the clientside of things.
