### ISSUE TITLE
F10 key in firefox shows menu instead of sending F10 key to client application

### ISSUE THREAD

**Issue by geocode** [kanaka/noVNC#705]
We are having an issue when we are using NoVNC from firefox.

The F10 key shows the firefox menu instead of just being sent to the application we are running in the No VNC session.  It is tricky because it doesn't happen on every firefox instance and sometimes installing an extension like firebug will make the problem go away but not always -- other  times removing a profile and starting from scratch may fix it, but not always... Some times starting with a fresh profile makes the problem appear.  It seems like a firefox bug, but of course we are unsure.

Is there anyway to suppress sending the F10 key to firefox when No VNC is running?  We have not come up with a work around for this.  Is anyone familiar with this issue or similar?  If anyone has any suggestions or code they would like us to try we can patch our version and give it a try to help.

**Comment by samhed** [comment]
I can not reproduce your problem, F10 works great in Firefox for me

**Comment by DirectXMan12** [comment]
if you're still experiencing this, can you indicate browser version and operating system as well?

**Comment by samhed** [comment]
Closing due to no response and not being able to reproduce.
