### ISSUE TITLE
IE11 not working

### ISSUE THREAD

**Issue by strgue** [kanaka/noVNC#706]
hello,
i tried various versions (also the last one 0.6.1.166) of novnc with firefox and had no problems.
but when i use internet explorer 11 with windows 7 it does not work.
the menue does not appear.
the browser reqirements says ie9+.
is there anything to configuer in ie11?
exist a novnc-version that is working with ie11?
kr guenter

**Comment by samhed** [comment]
No special configuration needed for IE11. It works just fine for me.

> the menue does not appear.

Could you elaborate? A screenshot perhaps

**Comment by strgue** [comment]
thx for response.
on the left side should appear the menu for opening the connection & settings.
attached a screenshot with ie11 and another with firefox.
hope you can see it.
in the ie11.png is the menue missing.

![firefox](https://cloud.githubusercontent.com/assets/23237020/20002932/c4fb88d0-a283-11e6-9447-9ebb0ba3af69.png)
![ie11](https://cloud.githubusercontent.com/assets/23237020/20002933/c4fc2dda-a283-11e6-9785-2bc45e8979d1.png)

**Comment by samhed** [comment]
Ok, are you seeing any errors in the JavaScript console? Are you running the latest master?

**Comment by samhed** [comment]
Ok, are you seeing any errors in the JavaScript console? Are you running the latest master?

**Comment by samhed** [comment]
Ok, are you seeing any errors in the JavaScript console? Are you running the latest master?

**Comment by strgue** [comment]
i use novnc kanaka-noVNC-v0.6.1-166-gef887cd.zip.
but i had also problems with older versions.
attached a screenshot with an error.
its in german. i hope you can understand it.
here a translation:
The "getItem" property of an undefined or null reference can not be retrieved.

![ie11-error](https://cloud.githubusercontent.com/assets/23237020/20003907/55a51806-a289-11e6-8e58-f13872be6134.png)

**Comment by samhed** [comment]
I see now that you are browsing directly to the vnc.html file... That will not work and isn't supported. Set up a Websockify server please.

**Comment by strgue** [comment]
thx
