### ISSUE TITLE
Touch Keyboard Stays Hidden 

### ISSUE THREAD

**Issue by Coder206** [kanaka/noVNC#707]
When clicking on the terminal of my OS through noVNC, I expected it to load my smartphone's virtual keyboard but instead, it seems to just focus on the application and nothing happens. 

Steps to reproduce,

- Start a noVNC session with a Linux computer (I think I was using Xbuntu) on Firefox For Android on a Nexus 6P

- Try sending commands to the Terminal.

**Comment by samhed** [comment]
noVNC doesn't know what you have clicked on inside your session. You will have to click on the keyboard button in noVNC's interface.
