### ISSUE TITLE
connection timeout at bad connection

### ISSUE THREAD

**Issue by zwick88** [kanaka/noVNC#709]
Hi everyone, 

i have a problem with the noVNC Server. I want to connect to server by a connection like dyndns, but i cant connect to them. I think its an connection timeout error. If i try to click the connect button each time, the the connection didnt established, at the 5. time (or so) the connection is established. Is there any parameter i can change for connection timeout?

Pleas someone help me

and sorry for my bad english

**Comment by samhed** [comment]
We had an issue where we would hit the disconnect timeout too often. Please try again with the latest master and see which error you get now?

**Comment by samhed** [comment]
Closing due to no response and due to the fact that is likely fixed.
