### ISSUE TITLE
IE11 not working 2.

### ISSUE THREAD

**Issue by strgue** [kanaka/noVNC#710]
ok i should setup a websockify server...
i'm a beginner concerning this topic and web programming alltogether.
maybe i understand somthing wrong:

1. i use libvncserver that does not need a websockify server as stated in the readme file. and with firefox its working without. with firefox i only load the webpage vnc.html and fill in address and port.

2. the online version (http://kanaka.github.io/noVNC/noVNC/vnc.html) is working with ie11 without websokify server

3. as far as i understand i have to load first of all the webpage vnc.html in the browser and there i can fill in the address and port

4. i downloaded a version of websokify server for windows (https://github.com/kanaka/websockify/downloads) and copied it on my client-pc (windows 7) and started it like:
websockify :5901 192.168.1.167:5900
how should i go on to start the connection (in case i really need the websockify)?
can you please help me?

thx in advance.

**Comment by samhed** [comment]
As stated in #706 don't open the html page from disk..
