### ISSUE TITLE
Russian letters displayed improperly

### ISSUE THREAD

**Issue by diboanches** [kanaka/noVNC#714]
When I created a file using russian letters in vnc it displayed like " ????? "
Is there any way to fix it? 

Thanks

**Comment by DirectXMan12** [comment]
can you clarify?  What, exactly, do you mean?  Is this when you are trying to type russian letters?  What VNC server are you using?

**Comment by diboanches** [comment]
Sure! 
We are using noVNC on Proxmox Virtual Environment. If I connected via terminal Ubuntu\Putty I can type Russian and can see correctly. But When I connected via VNC on Proxmox I can't see letters except of question marks. Also I am not able to type Russian at all

**Comment by DirectXMan12** [comment]
Ah, ok, this may be due to the difficulty dealing with keymaps in the browser.  What keymap are you using?  Also, it looks like Promox is based on KVM and Qemu.  In that case, the Qemu VNC extensions should be kicking in.  Can you figure out what options qemu is being run with (e.g. do a `ps -Alf | grep qemu` and report one of the result lines?)

**Comment by diboanches** [comment]
Yes, I can do that, I think. I will report as soon as I can! Thank you!

**Comment by diboanches** [comment]
Hello again! 
I am going to show you an example of output 
http://joxi.ru/Dr8O44ni9QZPA6

Proxmox version: 
pve-manager/4.3-10/7230e60f (running kernel: 4.4.21-1-pve)

ps -Alf | grep qemu
0 S root      8143 23106  0  80   0 -  3497 pipe_w 22:20 pts/4    00:00:00 grep qemu

Also, I realized that I don't really know how to check my keymap. So I used this one: 
localectl list-keymaps
Couldn't find any console keymaps. 

Maybe I should use another command?

**Comment by CendioOssman** [comment]
This looks like a server side issue. It seems like you are running with a locale that doesn't support Russian characters. Run the command `locale` in the terminal and see what it says. It should specify `<something>.UTF-8` or things won't work.

Fixing this is a matter of starting your session with the proper locale. How that is done depends entirely on how your session is started.

**Comment by DirectXMan12** [comment]
ah, yeah, if it's not from you typing, then it's not a noVNC issue.

**Comment by diboanches** [comment]
@CendioOssman   
I did that command on my server and the output included ru_RU.UTF-8. 
BUT. I did the same thing on my AWS server and the output was: 
~ $  locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

and I can write and see any russian symbols on aws server though there are no any ru_RU.UTF-8
But when I use VNC in my browser I cant do anything of that. 

@DirectXMan12 
Based on my words is it still could be not a vnc issues?  I don't know, you guys could try on your own just copy Russian letters and name something and watch :)

**Comment by CendioOssman** [comment]
> I did that command on my server and the output included ru_RU.UTF-8.

In that case my next guess would be that you haven't got the locale files for Russian properly installed. The fact that the ls output isn't translated also suggests that.

> Based on my words is it still could be not a vnc issues?

No. There is no difference between text and images from VNC's point of view. So text rendered incorrectly is entirely a server issue independent of VNC.

**Comment by diboanches** [comment]
okay then, I have to deal with my server then :) 
Thanks all of you!  Have a nice day!

**Comment by romkus** [comment]
Hello, diboanches. Can You tell how You solved this problem? I believe it maybe not a VNC issue, but I can setup desired locales in direct console, also I can see all characters correctly in SSH and SPICE, but not in noVNC. The font in noVNC shell of ProxMox doesn't affected by settings in 'locales' package.

**Comment by diboanches** [comment]
Hi,@romkus! 
Unfortunately, I do not remember a thing. I actually do not even remember did I resolve the issue or not.
