### ISSUE TITLE
It works in chrome and edge, but not in firefox 49.0.2

### ISSUE THREAD

**Issue by StefanHoutzager** [kanaka/noVNC#716]
Hi,

I'm already using noVNC for some time, I find it a wonderful product. Some time ago it suddenly stopped working in firefox, maybe at the moment a new firefox version was downloaded.  So I stepped over to chrome. Yesterday I downloaded the newest noVNC sources here, but it still doesn's work in firefox version 49.0.2 (the latest version, from oct 20 2016). 

![image](https://cloud.githubusercontent.com/assets/6817215/20298333/9de47424-ab15-11e6-8474-088e3dc600c3.png)

Thanks for your great work!

**Comment by CendioOssman** [comment]
This looks like a problem with websockify rather than noVNC. Can you check the network tab and see if there are any more details about the failure to establish the websocket connection?

**Comment by StefanHoutzager** [comment]
Thanks for your reaction and pointing me to the real problem. I'll see what I can do about websockify. Nothing of interest on the networktab it seems to me:
![image](https://cloud.githubusercontent.com/assets/6817215/20299244/5d1f8ea6-ab1a-11e6-9611-61a392178f91.png)

**Comment by CendioOssman** [comment]
Opening the right side bar and selecting the request should provide more details.

**Comment by StefanHoutzager** [comment]
Thanks, you mean this sidebar? Maybe this is not the right websockify?
![image](https://cloud.githubusercontent.com/assets/6817215/20303018/c2db83c6-ab29-11e6-9763-32e853550304.png)

**Comment by CendioOssman** [comment]
That's the one. Looks ok so far. Could you do the same for the websocket request?

**Comment by StefanHoutzager** [comment]
For some reason that I do not understand I get a connection now, so I cannot reproduce the error anymore. Tried a couple of times.  Thanks for your interest! For completeness I add the websocket.js request

![image](https://cloud.githubusercontent.com/assets/6817215/20305370/7e5cc686-ab35-11e6-8c59-c3eb73bc5ade.png)
