### ISSUE TITLE
Double right click opens browser context menu

### ISSUE THREAD

**Issue by gj12** [kanaka/noVNC#717]
Double right click opens browser context menu. 

![vnc1](https://cloud.githubusercontent.com/assets/8588565/20304413/5afbff0e-ab30-11e6-84da-e74a26206c2b.png)

And you can easily hit the "View Image" and noVNC disconnects and shows the last frame.

![vnc2](https://cloud.githubusercontent.com/assets/8588565/20304497/d5c94818-ab30-11e6-887e-7098a5cf9a9f.png)

This was not always the case. Some older noVNC versions do not have this (minor) bug.

Browser: Firefox 49

**Comment by samhed** [comment]
Can not reproduce using Firefox 49 nor in Chrome..?

**Comment by gj12** [comment]
Sorry, my bad. One of my addons was causing this.
