### ISSUE TITLE
clipboard panel with textarea disappeared?

### ISSUE THREAD

**Issue by StefanHoutzager** [kanaka/noVNC#719]
I updated noVNC with the sources here a couple of days ago, but the clipboard button allas disappeared. 
Can I cut and paste from outside noVNC to inside in another way?

![image](https://cloud.githubusercontent.com/assets/6817215/20386676/fc62dc54-acbc-11e6-9489-d9419931aee9.png)

**Comment by samhed** [comment]
Click the little handle on the left side to expand the control bar.

**Comment by StefanHoutzager** [comment]
Great! Thanks for the quick reply.
