### ISSUE TITLE
keyboard input has no response in chrome and Firefox, and was ok on safari

### ISSUE THREAD

**Issue by blaketairan** [kanaka/noVNC#721]
The last edition doesn't work well on:
chrome 53.0.2785.143
firefox 45.4.0

but on safari was ok.
safari  9.1.2 (11601.7.7)

**Comment by samhed** [comment]
What platform are you using? Are you seeing any errors in the JavaScript console?

**Comment by pcs3rd** [comment]
are you on a mobile or desktop. Honestly, I even have problems accessing it with anything on windows 7, but none on 10 or linux. i use chrome53.0.2785.143 (Developer Build) on linux

**Comment by geostant** [comment]
We are suffering from the same issue,
On OSX it works perfectly and on Windows PC (Windows 7 + Latest chrome) it open the canvas and we can see the desktop but we can input anything.

I'm not using the latest noVNC (we are actually using an old pull that suits us well.)

**Comment by samhed** [comment]
First, I have not ever seen any behavior like this. Secondly, if you want assistance you should be running the latest master version..

Are you people getting any errors in the javascript console?

**Comment by geostant** [comment]
@samhed 
I've pulled the latest and using `vnc_auto.html` as my endpoint
seems to be ok now in terms of keyboard and mouse on most PCs (we still got 2-3 PCs that have no response).

Now the new issue is that autoscaling doesn't work as before, but that require another issue to be opened.

**Comment by samhed** [comment]
@geostant vnc_auto.html has never had autoscaling afaik.

Closing this.
