### ISSUE TITLE
svg issues with libvncserver

### ISSUE THREAD

**Issue by strgue** [kanaka/noVNC#723]
chrome & opera does not correctly display the entries in the menue on the left side.
see screenshots.
![chrome-1](https://cloud.githubusercontent.com/assets/23237020/20619657/046c3622-b2f6-11e6-84e2-8449631e2ef6.png)
![chrome-2](https://cloud.githubusercontent.com/assets/23237020/20619658/047f7e30-b2f6-11e6-9b6e-64bd93e08e1d.png)
![opera-1](https://cloud.githubusercontent.com/assets/23237020/20619660/049f5ec6-b2f6-11e6-85d2-70eb5a62335f.png)
![opera-2](https://cloud.githubusercontent.com/assets/23237020/20619659/04979196-b2f6-11e6-81f5-246ad65154dd.png)

**Comment by CendioOssman** [comment]
Looks like libvncserver again. It's built in web server doesn't send SVGs properly.

**Comment by samhed** [comment]
Yeah, I'll keep this open for visibility, but there is nothing we can do from our part here (other than to stop using svg images, which we don't want to do). It looks like the libvncserver people will fix this.

**Comment by samhed** [comment]
Fixed in libvncserver now.
