### ISSUE TITLE
kodi bug

### ISSUE THREAD

**Issue by pcs3rd** [kanaka/noVNC#724]
If i go into Kodi media center and go in any menu while the host is on the same net(my pc isn't on the www) the client gets butted from the session and the novnc terminal gives this back
Socket connection
192.168.0.59 - - [26/Nov/2016 09:01:31] 192.168.0.59: Version hybi-13, base64: 'False'
192.168.0.59 - - [26/Nov/2016 09:01:32] 192.168.0.59: Path: '/websockify'
192.168.0.59 - - [26/Nov/2016 09:01:32] connecting to: localhost:5900
192.168.0.59 - - [26/Nov/2016 09:01:34] code 400, message Bad HTTP/0.9 request type ('\x88\x8f@E\x9epC\xad\xca\x112"\xfb\x04`&\xf2\x1f3')
and x11vnc gives this
26/11/2016 09:02:00 Got connection from client 127.0.0.1
26/11/2016 09:02:00   other clients:
26/11/2016 09:02:00      127.0.0.1
26/11/2016 09:02:00 Normal socket connection
26/11/2016 09:02:00 incr accepted_client=4 for 127.0.0.1:38814  sock=13
26/11/2016 09:02:00 Client Protocol Version 3.8
26/11/2016 09:02:00 Protocol version sent 3.8, using 3.8
26/11/2016 09:02:00 rfbProcessClientSecurityType: executing handler for type 1
26/11/2016 09:02:00 rfbProcessClientSecurityType: returning securityResult for client rfb version >= 3.8
26/11/2016 09:02:00 -dontdisconnect: Not shared & existing client
26/11/2016 09:02:00   refusing new client 127.0.0.1
26/11/2016 09:02:00 client_count: 1
26/11/2016 09:02:00 Client 127.0.0.1 gone
26/11/2016 09:02:00 Statistics             events    Transmit/ RawEquiv ( saved)
26/11/2016 09:02:00  TOTALS              :      0 |         0/        0 (  0.0%)
26/11/2016 09:02:00 Statistics             events    Received/ RawEquiv ( saved)
26/11/2016 09:02:00  TOTALS              :      0 |         0/        0 (  0.0%)
26/11/2016 09:02:06 XDAMAGE is not working well... misses: 110/219
26/11/2016 09:02:06 Maybe an OpenGL app like Beryl or Compiz is the problem?
26/11/2016 09:02:06 Use x11vnc -noxdamage or disable the Beryl/Compiz app.
26/11/2016 09:02:06 To disable this check and warning specify -xdamage twice.
26/11/2016 09:03:30 XDAMAGE is not working well... misses: 60/201
26/11/2016 09:03:30 Maybe an OpenGL app like Beryl or Compiz is the problem?
26/11/2016 09:03:30 Use x11vnc -noxdamage or disable the Beryl/Compiz app.
26/11/2016 09:03:30 To disable this check and warning specify -xdamage twice.
26/11/2016 09:05:12 XDAMAGE is not working well... misses: 98/201
26/11/2016 09:05:12 Maybe an OpenGL app like Beryl or Compiz is the problem?
26/11/2016 09:05:12 Use x11vnc -noxdamage or disable the Beryl/Compiz app.
26/11/2016 09:05:12 To disable this check and warning specify -xdamage twice.
26/11/2016 09:07:02 idle keyboard:   turning X autorepeat back on.
26/11/2016 09:07:30 XDAMAGE is not working well... misses: 184/216
26/11/2016 09:07:30 Maybe an OpenGL app like Beryl or Compiz is the problem?
26/11/2016 09:07:30 Use x11vnc -noxdamage or disable the Beryl/Compiz app.
26/11/2016 09:07:30 To disable this check and warning specify -xdamage twice.
This gives me a feeling that x11vnc is the problem and it doesn't thwart the program, but instead still lets it run, letting novnc catch it. In order for it to work again, i have to restart both programs

**Comment by pcs3rd** [comment]
it is almost like kodi is causing x11vnc to basically panic and crash, but doesn't stop

**Comment by samhed** [comment]
I find it very unlikely that noVNC is the issue here. Can you verify this through testing a different VNC client?

**Comment by samhed** [comment]
Closing due to no response and the unlikelihood that this is an issue with noVNC.
