### ISSUE TITLE
updateState callback function not reporting when a connection fails

### ISSUE THREAD

**Issue by jeffforbes** [kanaka/noVNC#728]
The updateState callback function reports when it is in the connecting mode; however, when the connection fails there are only  messages in the console:
state = connecting                                           virtDis...sVNC.js (line 159)
Firefox can’t establish a connection to the server at wss://rnd.nacon.com:8080/?token=EF3255EF.  websock.js (line 278, col 30)
WebSocket on-error event       util.js (line 42)
WebSocket on-close event

I am testing this by blocking the port that websockify listens on.

We have java viewer code that we want to fallback to. Our code was monitoring the state changes in the updateState to determine when to go to the java view. This no longer works

what it the best way to programatically determine when the connection fails?

**Comment by samhed** [comment]
Yes, this was recently changed. The plan was to properly announce the API changes when we finish the 0.7 release.

The updateState callback should tell you about changes to the connection states. You should be looking for the onDisconnected callback if you want a reason for the disconnection.

https://github.com/kanaka/noVNC/blob/master/core/rfb.js#L164

**Comment by jeffforbes** [comment]
Sorry, the  onDisconnected callback is not reached when the error I reported above is received.
That could be due to a connection never being made. Nevertheless, we need some mechanism for
knowing when a connection is not made as was previously available.

**Comment by samhed** [comment]
Hm, okay, it's really wierd that you're not getting a websocket close.., I'll try to take a look tomorrow

**Comment by kanaka** [comment]
@samhed that rings a bell. I think part of the complexity of the originally close/disconnect/timeout logic was to deal with this situation where the close event was not very reliable. As I recall this might be a security feature in some browsers to reduce the ability to use WebSockets for port scanning, but memory is a bit fuzzy so I could be wrong.

**Comment by samhed** [comment]
@kanaka hm, ok. But actually:

> state = connecting virtDis...sVNC.js (line 159)
> Firefox can’t establish a connection to the server at wss://rnd.nacon.com:8080/?token=EF3255EF.websock.js (line 278, col 30)
> WebSocket on-error event util.js (line 42)
> WebSocket on-close event

The log excerpt in the first post says that @jeffforbes did in fact get a close event.. There is no code path from a websocket close that doesn't lead to the disconnected state. And the disconnected state should always call the onDisconnect callback.

Now I'm even more confused. Are you sure that you aren't getting the onDisconnect callback??

**Comment by jeffforbes** [comment]
```javascript
rfb = new RFB({
                        'target':         $("#vmViewer"+vmID).get(0),   // VNC display rendering Canvas object
                        'encrypt':        vncEncrypt,                   // Use TLS/SSL/wss encryption
                        'repeaterID':     '',
                        'true_color':     true,                         // Request true color pixel data
                        'local_cursor':   true,                         // Request locally rendered cursor
                        'shared':         true,                         // Request shared mode
                        'view_only':      viewOnly,                     // Disable client mouse/keyboard
                        'onUpdateState':  updateState,
                        'onNotification': notification,
                        'onDisconnected': disconnected,
                        'onFBUComplete':  FBUComplete,
                        'onDesktopName':  updateDesktopName
                });
       function disconnected(rfb, reason) {
        console.log("Inside Disconnected callback");
            var vmID=$(rfb.get_target()).attr("id").substring(8);
            if (typeof(reason) !== 'undefined') {
                updateStatus (vmID, reason, "error");
            }
        }
```
I increased the logging level to debug and below is the firebug console output:
>> RFB.constructor
util.js (line 38)
>> Display.constructor
util.js (line 38)
User Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0
util.js (line 38)
Browser: gecko 19
util.js (line 38)
Setting viewport to full display region
util.js (line 38)
Data URI scheme cursor supported
util.js (line 40)
<< Display.constructor
util.js (line 38)
>> Keyboard.allKeysUp
util.js (line 38)
<< Keyboard.allKeysUp
util.js (line 38)
Using native WebSockets, render mode: canvas rendering
util.js (line 40)
<< RFB.constructor
util.js (line 38)
Inside updateStatus -> state = Connecting level = normal
virtDis...sVNC.js (line 106)
previousState = undefinedstate = connecting
virtDis...sVNC.js (line 159)
New state 'connecting', was ''.
util.js (line 38)
>> RFB.connect
util.js (line 38)
connecting to wss://rnd.nacon.com:8080/?token=EF3255EF
util.js (line 40)
Detected binaryType support in WebSockets
util.js (line 40)
<< RFB.connect
util.js (line 38)
Inside updateStatus -> state = undefined level = normal
virtDis...sVNC.js (line 106)
Firefox can’t establish a connection to the server at wss://rnd.nacon.com:8080/?token=EF3255EF.
	

websock.js (line 278, col 30)
>> WebSock.onerror: [object Event]
util.js (line 38)
WebSocket on-error event
util.js (line 42)
<< WebSock.onerror: [object Event]
util.js (line 38)
>> WebSock.onclose
util.js (line 38)
WebSocket on-close event
util.js (line 42)


While there is a socket close event, the onDisconnect callback is never reached.

**Comment by samhed** [comment]
> While there is a socket close event, the onDisconnect callback is never reached.

Are you running the latest master? I can't see any code path that doesn't transition a on-close event to the 'disconnected' state.

All the conditions where a call to __updateConnectionState('disconnected')_ doesn't call the onDisconnected callback should write an error to the log as far as I can see..

**Comment by jeffforbes** [comment]
I am running the code from the master as of yesterday.

**Comment by jeffforbes** [comment]
Could be a problem with the latest version of firefox. Here is the console log from chrome:

>> RFB.constructor
>> Display.constructor
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36
Browser: webkit 537.36
Setting viewport to full display region
Data URI scheme cursor supported
<< Display.constructor
>> Keyboard.allKeysUp
<< Keyboard.allKeysUp
Using native WebSockets, render mode: canvas rendering
<< RFB.constructor
Inside updateStatus -> state = Connecting level = normal
previousState = undefinedstate = connecting
New state 'connecting', was ''.
>> RFB.connect
connecting to wss://rnd.nacon.com:8080/?token=EF3255EF
Detected binaryType support in WebSockets
<< RFB.connect
Inside updateStatus -> state = undefined level = normal
WebSocket connection to 'wss://rnd.nacon.com:8080/?token=EF3255EF' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT
>> WebSock.onerror: [object Event]
WebSocket on-error event
<< WebSock.onerror: [object Event]
>> WebSock.onclose
WebSocket on-close event
Failed when connecting: Failed to connect to server ( (code: 1006))
Inside updateStatus -> state = Disconnecting level = normal
previousState = normalstate = disconnecting
New state 'disconnecting', was 'connecting'.
>> RFB.disconnect
>> Keyboard.allKeysUp
<< Keyboard.allKeysUp
Encoding stats for this connection:
Encoding stats since page load:
    COPYRECT: 0 rects
    TIGHT: 0 rects
    TIGHT_PNG: 0 rects
    HEXTILE: 0 rects
    RRE: 0 rects
    RAW: 0 rects
    JPEG_quality_med: 0 rects
    compress_hi: 0 rects
    DesktopSize: 0 rects
    last_rect: 0 rects
    Cursor: 0 rects
    QEMUExtendedKeyEvent: 0 rects
    ExtendedDesktopSize: 0 rects
    xvp: 0 rects
    Fence: 0 rects
    ContinuousUpdates: 0 rects
<< RFB.disconnect
Inside updateStatus -> state = Disconnected level = normal
previousState = disconnectingstate = disconnected
New state 'disconnected', was 'disconnecting'.
Clearing disconnect timer
Inside Disconnected callback
Inside updateStatus -> state = Failed to connect to server level = error
<< WebSock.onclose

**Comment by jeffforbes** [comment]
Looks like firebug is the culprit. When I turn off firebug, my code completes as expected.

**Comment by samhed** [comment]
Ok. Closing then
