### ISSUE TITLE
Hiding the top control bar's buttons

### ISSUE THREAD

**Issue by geostant** [kanaka/noVNC#730]
Hey,

I'm trying to remove the buttons in the top control bar,
it seems that if I remark out the whole TD section the VNC session won't start (probably it's expecting it ?)

```
<td width="1%"><div id="noVNC_buttons">
                        <input type=button value="Send CtrlAltDel"
                            id="sendCtrlAltDelButton">
                        <span id="noVNC_xvp_buttons">
                        <input type=button value="Shutdown"
                            id="xvpShutdownButton">
                        <input type=button value="Reboot"
                            id="xvpRebootButton">
                        <input type=button value="Reset"
                            id="xvpResetButton">
                        </span>
                    </div></td>
                </tr>
```

I do want to top bar that says that I'm connected to the host,
I just don't want the control buttons.

Will appreciate help here :)

Thanks

**Comment by samhed** [comment]
There's obviously code that defines what should happen when you click the buttons? I don't know what you are expecting.. I can offer to look into actual issues with our code, or help with general questions regarding noVNC.
