### ISSUE TITLE
Mouse events not passed to x11vnc

### ISSUE THREAD

**Issue by shadeslayer** [kanaka/noVNC#733]
Hi
I'm using x11vnc and novnc from Debian testing and launching it with the following command
```
websockify -D --ssl-target --web /usr/share/novnc/ 5900 -- x11vnc -forever -shared -find -unixpw -avahi -loop
```

While keyboard events are properly forwarded to x11vnc, mouse events seem to be lost. x11vnc by itself works just fine with a regular VNC client.

**Comment by shadeslayer** [comment]
I seem to have hit https://groups.google.com/forum/#!topic/novnc/bOpKeuZCd7s

**Comment by samhed** [comment]
So you are saying that you have a device with both a mouse and a touch screen? This case is fixed in the latest master of noVNC.

**Comment by shadeslayer** [comment]
Indeed. Ah ok, this can be closed then :)
